import { trackNameAliasKey } from "@/lib/live/track-name";

const TRACK_MEDIA_PATHS = new Map<string, string>([
  ["angle park", "/images/tracks/angle-park/venue-20260724.webp"],
  ["ballarat", "/images/tracks/ballarat/venue-20260724.webp"],
  ["bendigo", "/images/tracks/bendigo/venue-20260724.webp"],
  ["bet nation townsville", "/images/tracks/townsville/master.webp"],
  ["betdeluxe capalaba", "/images/tracks/capalaba/venue-20260724.webp"],
  ["betdeluxe rockhampton", "/images/tracks/rockhampton/venue-20260724.webp"],
  ["bulli", "/images/tracks/bulli/venue-20260724.webp"],
  ["cannington", "/images/tracks/cannington/venue-20260724.webp"],
  ["casino", "/images/tracks/casino/master.webp"],
  ["darwin", "/images/tracks/darwin/venue-20260724.webp"],
  ["dubbo", "/images/tracks/dubbo/venue-20260724.webp"],
  ["gawler", "/images/tracks/gawler/venue-20260724.webp"],
  ["geelong", "/images/tracks/geelong/venue-20260724.webp"],
  ["gosford", "/images/tracks/gosford/master.webp"],
  ["goulburn", "/images/tracks/goulburn/master.webp"],
  ["grafton", "/images/tracks/grafton/master.webp"],
  ["gunnedah", "/images/tracks/gunnedah/master.webp"],
  ["healesville", "/images/tracks/healesville/master.webp"],
  ["hobart", "/images/tracks/hobart/master.webp"],
  ["horsham", "/images/tracks/horsham/master.webp"],
  ["ladbrokes gardens", "/images/tracks/ladbrokes-gardens/master.webp"],
  ["ladbrokes q straight", "/images/tracks/q-straight/master.webp"],
  ["ladbrokes q1 lakeside", "/images/tracks/q1-lakeside/venue-20260724.webp"],
  ["ladbrokes q2 parklands", "/images/tracks/q2-parklands/venue-20260724.webp"],
  ["launceston", "/images/tracks/launceston/master.webp"],
  ["maitland", "/images/tracks/maitland/master.webp"],
  ["mandurah", "/images/tracks/mandurah/master.webp"],
  ["meadows", "/images/tracks/the-meadows/venue-20260724.webp"],
  ["mount gambier", "/images/tracks/mount-gambier/master.webp"],
  ["murray bridge", "/images/tracks/murray-bridge/master.webp"],
  [
    "murray bridge straight",
    "/images/tracks/murray-bridge-straight/master.webp",
  ],
  ["northam", "/images/tracks/northam/master.webp"],
  ["nowra", "/images/tracks/nowra/master.webp"],
  ["richmond", "/images/tracks/richmond/master.webp"],
  ["richmond straight", "/images/tracks/richmond-straight/master.webp"],
  ["sale", "/images/tracks/sale/master.webp"],
  ["sandown", "/images/tracks/sandown-park/venue-20260724.webp"],
  ["shepparton", "/images/tracks/shepparton/master.webp"],
  ["taree", "/images/tracks/taree/master.webp"],
  ["temora", "/images/tracks/temora/master.webp"],
  ["traralgon", "/images/tracks/traralgon/master.webp"],
  ["wagga", "/images/tracks/wagga/master.webp"],
  ["warragul", "/images/tracks/warragul/master.webp"],
  ["warrnambool", "/images/tracks/warrnambool/master.webp"],
  ["wentworth park", "/images/tracks/wentworth-park/venue-20260724.webp"],

  // Venue identity stays stable when mutable sponsor or programme labels change.
  ["capalaba", "/images/tracks/capalaba/venue-20260724.webp"],
  ["gardens", "/images/tracks/ladbrokes-gardens/master.webp"],
  ["the gardens", "/images/tracks/ladbrokes-gardens/master.webp"],
  ["meadows (mep)", "/images/tracks/the-meadows/venue-20260724.webp"],
  ["q straight", "/images/tracks/q-straight/master.webp"],
  ["q1 lakeside", "/images/tracks/q1-lakeside/venue-20260724.webp"],
  ["q2 parklands", "/images/tracks/q2-parklands/venue-20260724.webp"],
  ["rockhampton", "/images/tracks/rockhampton/venue-20260724.webp"],
  ["sandown (sap)", "/images/tracks/sandown-park/venue-20260724.webp"],
  ["sandown park", "/images/tracks/sandown-park/venue-20260724.webp"],
  ["tabtouch cannington", "/images/tracks/cannington/venue-20260724.webp"],
  ["tabtouch mandurah", "/images/tracks/mandurah/master.webp"],
  ["tabtouch northam", "/images/tracks/northam/master.webp"],
  ["the meadows", "/images/tracks/the-meadows/venue-20260724.webp"],
  ["townsville", "/images/tracks/townsville/master.webp"],
]);

export function trackMediaPathForName(trackName: string) {
  return TRACK_MEDIA_PATHS.get(trackNameAliasKey(trackName)) ?? null;
}
