import type { RegistryEvidence, VerificationStatus } from "./shared";

export type AuditEventContract = {
  eventId: string;
  traceIds: string[];
  eventName: string;
  persistence: "application-log" | "audit-log" | "domain-record" | "missing";
  actor: string;
  target: string;
  safeFields: string[];
  prohibitedFields: string[];
  sourceFiles: string[];
  sourceSymbols: string[];
  evidence: RegistryEvidence[];
  owner: string;
  verificationStatus: VerificationStatus;
};

export const AUDIT_EVENTS = [
  {
    eventId: "AUDIT.AUTH.CALLBACK.FAILED",
    traceIds: ["AUTH.CALLBACK.RECOVER", "AUTH.CALLBACK.COMPLETE"],
    eventName: "auth.callback_failed",
    persistence: "application-log",
    actor: "anonymous authentication attempt",
    target: "authentication callback",
    safeFields: [
      "reason",
      "referenceId",
      "requestId",
      "traceId",
      "severity",
      "message",
      "event",
      "service",
      "environment",
      "region",
      "revision",
    ],
    prohibitedFields: ["authorization code", "session token", "provider payload"],
    sourceFiles: ["src/app/callback/route.ts"],
    sourceSymbols: ["GET.onError"],
    evidence: [
      {
        sourceFile: "src/app/callback/route.ts",
        sourceSymbol: "GET.onError",
        note: "Only the allowlisted reason and generated UUID are supplied as event context; the structured logger adds its fixed correlation and service envelope.",
      },
    ],
    owner: "identity-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.AUTH.CALLBACK.LOCAL_ACCEPTANCE_FAILED",
    traceIds: ["AUTH.CALLBACK.COMPLETE"],
    eventName: "auth.callback_sync_failed",
    persistence: "application-log",
    actor: "AuthKit callback subject; identity fields are intentionally absent from log context",
    target: "local user/profile/outbox acceptance transaction",
    safeFields: [
      "errorCode",
      "errorClass",
      "requestId",
      "traceId",
      "severity",
      "message",
      "event",
      "service",
      "environment",
      "region",
      "revision",
    ],
    prohibitedFields: [
      "email",
      "WorkOS user ID",
      "authorization code",
      "session token",
      "cookie",
      "provider payload",
      "request body",
      "raw error",
      "exception message",
    ],
    sourceFiles: ["src/app/callback/route.ts", "src/lib/logger.ts"],
    sourceSymbols: ["GET.onSuccess", "logRequestError"],
    evidence: [
      {
        sourceFile: "src/app/callback/route.ts",
        sourceSymbol: "GET.onSuccess",
        note: "The route discards the caught exception, logs only fixed errorCode/errorClass values and a stable event name, then throws a generic local-acceptance sentinel.",
      },
      {
        sourceFile: "src/lib/logger.ts",
        sourceSymbol: "logRequestError",
        note: "The structured logger adds fixed severity, message, service, environment, region, revision and correlation fields; the callback never supplies the raw database error.",
      },
    ],
    owner: "identity-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.BILLING.WEBHOOK.RECEIVED",
    traceIds: ["BILLING.WEBHOOK.PROCESS"],
    eventName: "stripe webhook event record",
    persistence: "domain-record",
    actor: "Stripe",
    target: "WebhookEvent",
    safeFields: ["provider event ID", "event type", "status", "payload hash"],
    prohibitedFields: ["webhook secret", "signature header in logs"],
    sourceFiles: ["src/lib/billing/stripe-webhooks.ts"],
    sourceSymbols: ["ingestStripeWebhook"],
    evidence: [
      {
        sourceFile: "src/lib/billing/stripe-webhooks.ts",
        sourceSymbol: "ingestStripeWebhook",
        note: "A unique provider event record is created before reduction.",
      },
    ],
    owner: "billing-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.PULSE.CONVERSATION.BLOCK",
    traceIds: ["PULSE.CONVERSATION.BLOCK"],
    eventName: "conversation.block",
    persistence: "audit-log",
    actor: "current database user",
    target: "conversation",
    safeFields: ["actorId", "targetId", "action"],
    prohibitedFields: ["message content", "participant private content"],
    sourceFiles: ["src/lib/conversation-service.ts"],
    sourceSymbols: ["setConversationBlock"],
    evidence: [
      {
        sourceFile: "src/lib/conversation-service.ts",
        sourceSymbol: "setConversationBlock",
        note: "createAuditLog is called after the block transaction and realtime revocation.",
      },
    ],
    owner: "community-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.MEDIA.DELETE",
    traceIds: ["MEDIA.ASSET.DELETE"],
    eventName: "media.delete",
    persistence: "audit-log",
    actor: "current database user",
    target: "media",
    safeFields: ["actorId", "mediaId", "generated storage coordinates"],
    prohibitedFields: ["file bytes", "signed URL", "upload token"],
    sourceFiles: ["src/lib/media-service.ts"],
    sourceSymbols: ["deleteMediaForCurrentUser"],
    evidence: [
      {
        sourceFile: "src/lib/media-service.ts",
        sourceSymbol: "deleteMediaForCurrentUser",
        note: "The delete flow records media.delete after storage cleanup attempts.",
      },
    ],
    owner: "media-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ACCOUNT.DELETION.REQUESTED",
    traceIds: ["ACCOUNT.DELETION.EXECUTE"],
    eventName: "user.delete",
    persistence: "audit-log",
    actor: "current database user",
    target: "current user",
    safeFields: [
      "actorId",
      "targetId",
      "status",
      "graceDays",
      "requestedAt",
      "request IP",
      "user agent",
    ],
    prohibitedFields: ["prior email", "session token", "provider credentials"],
    sourceFiles: ["src/lib/account-service.ts"],
    sourceSymbols: ["requestAccountDeletion"],
    evidence: [
      {
        sourceFile: "src/lib/account-service.ts",
        sourceSymbol: "requestAccountDeletion",
        note: "The current-user update and user.delete audit insert share one request-context transaction.",
      },
    ],
    owner: "privacy-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ACCOUNT.DELETION.FINALIZED",
    traceIds: ["ACCOUNT.DELETION.EXECUTE"],
    eventName: "user.delete.finalize",
    persistence: "audit-log",
    actor: "internal system",
    target: "deleted user",
    safeFields: [
      "targetId",
      "requestedAt",
      "finalizedAt",
      "anonymized counts",
      "remote provider reference-retention statuses",
    ],
    prohibitedFields: [
      "prior email",
      "message content",
      "provider credentials",
      "session tokens",
    ],
    sourceFiles: ["src/lib/account-service.ts"],
    sourceSymbols: ["runAccountDeletionMaintenance"],
    evidence: [
      {
        sourceFile: "src/lib/account-service.ts",
        sourceSymbol: "runAccountDeletionMaintenance",
        note: "The per-user finalization transaction inserts user.delete.finalize with counts and provider-reference status, not provider secrets.",
      },
    ],
    owner: "privacy-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ACCOUNT.DELETION.STORAGE",
    traceIds: ["ACCOUNT.DELETION.EXECUTE"],
    eventName: "user.delete.storage or user.delete.storage_failed",
    persistence: "audit-log",
    actor: "internal system",
    target: "deletion job",
    safeFields: ["targetId", "status", "objectsDeleted", "safe error code"],
    prohibitedFields: ["storage object bytes", "storage credentials", "raw exception"],
    sourceFiles: ["src/lib/account-service.ts"],
    sourceSymbols: ["runAccountStorageDeletionJobs"],
    evidence: [
      {
        sourceFile: "src/lib/account-service.ts",
        sourceSymbol: "runAccountStorageDeletionJobs",
        note: "Storage completion and failure create audit rows; failures are reduced to an allowlisted error-code shape.",
      },
    ],
    owner: "privacy-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ACCOUNT.DATA_EXPORT.DOWNLOADED",
    traceIds: ["ACCOUNT.DATA_EXPORT.DOWNLOAD"],
    eventName: "user.export",
    persistence: "audit-log",
    actor: "current database user",
    target: "current user",
    safeFields: [
      "actorId",
      "targetId",
      "format",
      "schemaVersion",
      "sizeBytes",
      "collection counts",
      "request IP",
      "user agent",
    ],
    prohibitedFields: [
      "export body",
      "message content",
      "provider identifiers",
      "storage paths",
      "agent inputs or outputs",
    ],
    sourceFiles: [
      "src/app/api/users/me/export/route.ts",
      "src/lib/account-service.ts",
    ],
    sourceSymbols: ["GET", "createAuditLog"],
    evidence: [
      {
        sourceFile: "src/app/api/users/me/export/route.ts",
        sourceSymbol: "GET",
        note: "The audit payload contains format, schema version, byte size and counts, not the export archive; it records generation before the response and does not prove browser receipt.",
      },
    ],
    owner: "privacy-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ACCOUNT.PRIVACY.MARKETING_CHANGED",
    traceIds: [],
    eventName: "marketing_preference.update",
    persistence: "audit-log",
    actor: "current database user",
    target: "current user",
    safeFields: ["actorId", "targetId", "channel", "optedIn"],
    prohibitedFields: ["email address", "session token", "request body"],
    sourceFiles: ["src/app/api/users/me/marketing-preferences/route.ts"],
    sourceSymbols: ["POST"],
    evidence: [
      {
        sourceFile: "src/app/api/users/me/marketing-preferences/route.ts",
        sourceSymbol: "POST",
        note: "The owner-scoped preference upsert and marketing_preference.update AuditLog insert share one request-context transaction.",
      },
    ],
    owner: "privacy-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ADMIN.USER.ACCESS_CHANGED",
    traceIds: [],
    eventName: "admin.user.access_update",
    persistence: "audit-log",
    actor: "administrator",
    target: "user",
    safeFields: ["actorId", "targetId", "role", "verified", "banned", "reason"],
    prohibitedFields: ["session token", "password", "provider credentials"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["updateAdminUserAccess", "logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "updateAdminUserAccess",
        note: "Role, verification and suspension changes execute with last-admin checks and persist AdminAction plus AuditLog rows in the same transaction.",
      },
    ],
    owner: "administration-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ADMIN.TEAM.INVITATION.CREATED",
    traceIds: [],
    eventName: "admin.invitation.create",
    persistence: "audit-log",
    actor: "administrator",
    target: "organization invitation",
    safeFields: ["actorId", "targetId", "organizationId", "role", "reason"],
    prohibitedFields: ["plain invitation token", "plain invited email", "session token"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["createAdminInvitation", "logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "createAdminInvitation",
        note: "Invitation creation stores a hashed email and token and records the organization, role, actor, target and reason in the privileged mutation audit path.",
      },
    ],
    owner: "administration-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.MARKETPLACE.LISTING.MODERATED",
    traceIds: [],
    eventName: "listing.approve/listing.reject/listing.remove",
    persistence: "audit-log",
    actor: "moderator or administrator",
    target: "marketplace listing",
    safeFields: ["actorId", "targetId", "action", "reason"],
    prohibitedFields: ["buyer enquiry content", "private seller details", "session token"],
    sourceFiles: ["src/lib/listing-service.ts"],
    sourceSymbols: ["approveListingForModerator", "rejectListingForModerator", "removeListingForModerator", "auditListingModeration"],
    evidence: [
      {
        sourceFile: "src/lib/listing-service.ts",
        sourceSymbol: "auditListingModeration",
        note: "Approve, reject and remove transitions create AdminAction, ListingModerationAction and AuditLog records; approval is the publication decision.",
      },
    ],
    owner: "marketplace-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.DOG.OWNERSHIP.VERIFICATION_DECIDED",
    traceIds: [],
    eventName: "dog.ownership.approve/dog.ownership.reject",
    persistence: "audit-log",
    actor: "moderator or administrator",
    target: "dog ownership claim",
    safeFields: ["actorId", "targetId", "decision", "reason"],
    prohibitedFields: ["claimant credentials", "private support content", "session token"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["approveDogOwnership", "rejectDogOwnership", "logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "approveDogOwnership/rejectDogOwnership",
        note: "Only pending claims can be decided; each approval or rejection records actor, target, explicit reason and decision in AdminAction and AuditLog.",
      },
    ],
    owner: "racing-identity-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.BILLING.PAYMENT.CHANGED",
    traceIds: [],
    eventName: "admin.paymentRecord.update",
    persistence: "audit-log",
    actor: "administrator",
    target: "payment record",
    safeFields: ["actorId", "targetId", "status", "reason"],
    prohibitedFields: ["card number", "payment secret", "provider payload"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["updateAdminResourceStatus", "logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "updateAdminResourceStatus(paymentRecord)",
        note: "The allowlisted payment-record status mutation records the administrator, payment target, next status and mandatory reason in both privileged audit tables.",
      },
    ],
    owner: "billing-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.BILLING.ENTITLEMENT.CHANGED",
    traceIds: [],
    eventName: "admin.entitlement.upsert",
    persistence: "audit-log",
    actor: "administrator",
    target: "plan entitlement",
    safeFields: ["actorId", "targetId", "planId", "featureKey", "reason"],
    prohibitedFields: ["payment credentials", "session token", "provider payload"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["upsertAdminEntitlement", "logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "upsertAdminEntitlement",
        note: "The entitlement mutation and its reasoned AuditLog/AdminAction evidence execute in one administrator transaction.",
      },
    ],
    owner: "billing-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ADMIN.PRIVILEGED_MUTATION",
    traceIds: [],
    eventName: "logAdminMutation",
    persistence: "audit-log",
    actor: "administrator",
    target: "allowlisted administration resource",
    safeFields: ["actorId", "targetType", "targetId", "action", "reason"],
    prohibitedFields: ["password", "session token", "provider secret"],
    sourceFiles: ["src/lib/admin-service.ts"],
    sourceSymbols: ["logAdminMutation"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "logAdminMutation",
        note: "Every caller supplies an explicit action, target and cleaned reason; the helper creates AdminAction and AuditLog rows inside the caller transaction.",
      },
    ],
    owner: "administration-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.AI.TOOL.MUTATION",
    traceIds: [],
    eventName: "agent.run/dog_card.generate",
    persistence: "audit-log",
    actor: "current user or agent",
    target: "agent run or generated dog card",
    safeFields: ["actorId", "targetId", "agentType", "run status", "output media id"],
    prohibitedFields: ["provider API key", "prompt body", "generated image bytes"],
    sourceFiles: ["src/lib/agent-service.ts", "src/lib/dog-card-service.ts"],
    sourceSymbols: ["createAgentRun", "generateDogCard"],
    evidence: [
      {
        sourceFile: "src/lib/agent-service.ts",
        sourceSymbol: "createAgentRun",
        note: "Starting an agent run persists agent.run with the user, run target and bounded metadata.",
      },
      {
        sourceFile: "src/lib/dog-card-service.ts",
        sourceSymbol: "generateDogCard",
        note: "Successful provider-backed card generation persists dog_card.generate without logging the prompt body, API key or image bytes.",
      },
    ],
    owner: "ai-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ADMIN.POLICY.CHANGED",
    traceIds: [],
    eventName: "admin.retention_policy.upsert/platform_setting.update",
    persistence: "audit-log",
    actor: "administrator",
    target: "retention or platform policy",
    safeFields: ["actorId", "targetId", "policy code", "target type", "reason"],
    prohibitedFields: ["secret setting values", "session token", "provider credentials"],
    sourceFiles: ["src/lib/admin-service.ts", "src/lib/platform-settings.ts"],
    sourceSymbols: ["upsertAdminRetentionPolicy", "updatePlatformSetting"],
    evidence: [
      {
        sourceFile: "src/lib/admin-service.ts",
        sourceSymbol: "upsertAdminRetentionPolicy",
        note: "Retention-policy changes persist the actor, target, policy code/type and mandatory reason through logAdminMutation.",
      },
      {
        sourceFile: "src/lib/platform-settings.ts",
        sourceSymbol: "updatePlatformSetting",
        note: "Platform-setting changes persist a separate platform_setting.update audit event while excluding the setting value from audit metadata.",
      },
    ],
    owner: "platform-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.ORGANIZATION.OWNERSHIP.TRANSFERRED",
    traceIds: ["ACCOUNT.TEAM.CHANGE_ROLE"],
    eventName: "team.owner.transfer",
    persistence: "audit-log",
    actor: "current organization owner",
    target: "organization",
    safeFields: [
      "actorId",
      "targetId",
      "traceId",
      "previousOwnerId",
      "nextOwnerId",
      "result",
    ],
    prohibitedFields: [
      "member profile data",
      "invitation token",
      "session token",
    ],
    sourceFiles: ["src/lib/organization-team-service.ts"],
    sourceSymbols: ["changeOrganizationTeamMemberRole", "writeTeamAudit"],
    evidence: [
      {
        sourceFile: "src/lib/organization-team-service.ts",
        sourceSymbol: "changeOrganizationTeamMemberRole",
        note: "The transaction demotes the prior owner, promotes the target, updates organization.ownerId and writes a bounded team.owner.transfer audit record.",
      },
    ],
    owner: "organization-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.CUSTOM_PAGE.DELETED",
    traceIds: [],
    eventName: "custom_page.delete",
    persistence: "audit-log",
    actor: "current database user",
    target: "owned custom page and its actor conversations",
    safeFields: ["actorId", "targetId", "action"],
    prohibitedFields: ["page body", "conversation content", "session token"],
    sourceFiles: ["src/lib/custom-page-service.ts"],
    sourceSymbols: ["deleteCustomPage"],
    evidence: [
      {
        sourceFile: "src/lib/custom-page-service.ts",
        sourceSymbol: "deleteCustomPage",
        note: "The owned page and its actor conversations are removed in one request-context operation, followed by a redacted custom_page.delete audit record.",
      },
    ],
    owner: "community-security",
    verificationStatus: "Partially verified",
  },
  {
    eventId: "AUDIT.FRIENDSHIP.MUTATION",
    traceIds: [],
    eventName: "friend.request.decline/friend.remove",
    persistence: "audit-log",
    actor: "current database user",
    target: "friendship",
    safeFields: ["actorId", "targetId", "action"],
    prohibitedFields: ["profile private data", "session token"],
    sourceFiles: ["src/lib/friend-service.ts"],
    sourceSymbols: ["respondToFriendRequest", "removeFriend"],
    evidence: [
      {
        sourceFile: "src/lib/friend-service.ts",
        sourceSymbol: "respondToFriendRequest/removeFriend",
        note: "Declining a pending request and removing an accepted relationship both emit a bounded friendship audit record after the owner-scoped mutation.",
      },
    ],
    owner: "community-security",
    verificationStatus: "Partially verified",
  },
] as const satisfies readonly AuditEventContract[];
