const DATABASE_QUERY_RECORD_EVIDENCE = [
  "security/database-query-records.ts",
  "security/database-query-records.test.ts",
  "security/database-operations.ts",
  "security/traces.ts",
  "security/registry.test.ts",
] as const;

export const DATABASE_QUERY_RECORD_FIELD_BINDINGS = {
  "security.database-query-record.field.query-id": "queryId",
  "security.database-query-record.field.trace-id": "traceId",
  "security.database-query-record.field.triggering-user-action": "triggeringUserAction",
  "security.database-query-record.field.server-handler": "serverHandler",
  "security.database-query-record.field.service": "service",
  "security.database-query-record.field.repository": "repository",
  "security.database-query-record.field.orm-or-driver": "ormOrDriver",
  "security.database-query-record.field.orm-operation": "ormOperation",
  "security.database-query-record.field.normalised-sql": "normalisedSql",
  "security.database-query-record.field.bound-parameter-names": "boundParameterNames",
  "security.database-query-record.field.database": "database",
  "security.database-query-record.field.schema": "schema",
  "security.database-query-record.field.database-role": "databaseRole",
  "security.database-query-record.field.tables": "tables",
  "security.database-query-record.field.views": "views",
  "security.database-query-record.field.columns-read": "columnsRead",
  "security.database-query-record.field.columns-written": "columnsWritten",
  "security.database-query-record.field.tenant-predicate": "tenantPredicate",
  "security.database-query-record.field.ownership-predicate": "ownershipPredicate",
  "security.database-query-record.field.visibility-predicate": "visibilityPredicate",
  "security.database-query-record.field.row-level-policy": "rowLevelPolicy",
  "security.database-query-record.field.expected-rows": "expectedRows",
  "security.database-query-record.field.maximum-rows": "maximumRows",
  "security.database-query-record.field.pagination": "pagination",
  "security.database-query-record.field.transaction": "transaction",
  "security.database-query-record.field.isolation": "isolation",
  "security.database-query-record.field.locks": "locks",
  "security.database-query-record.field.concurrency-strategy": "concurrencyStrategy",
  "security.database-query-record.field.indexes": "indexes",
  "security.database-query-record.field.constraints": "constraints",
  "security.database-query-record.field.triggers": "triggers",
  "security.database-query-record.field.timeout": "timeout",
  "security.database-query-record.field.sensitive-data": "sensitiveData",
  "security.database-query-record.field.returned-shape": "returnedShape",
  "security.database-query-record.field.cache-interaction": "cacheInteraction",
  "security.database-query-record.field.not-found-behaviour": "notFoundBehaviour",
  "security.database-query-record.field.unauthorised-behaviour": "unauthorisedBehaviour",
  "security.database-query-record.field.conflict-behaviour": "conflictBehaviour",
  "security.database-query-record.field.failure-behaviour": "failureBehaviour",
  "security.database-query-record.field.tests": "tests",
  "security.database-query-record.field.evidence": "evidence",
} as const;

export const DATABASE_QUERY_RECORD_MASTER_EVIDENCE = Object.fromEntries(
  Object.keys(DATABASE_QUERY_RECORD_FIELD_BINDINGS).map((id) => [
    id,
    {
      status: "verified" as const,
      evidence: DATABASE_QUERY_RECORD_EVIDENCE,
    },
  ]),
);
