import type { DatabaseOperationContract } from "./database-operations";
import type { SecurityTraceContract } from "./traces";

type DatabaseOperationsFor = (traceId: string) => DatabaseOperationContract[];

const FOCUSED_TEST =
  "security/mandatory-public-racing-trace-evidence.test.ts";

/**
 * Builds the eight source-static mandatory trace records that precede trace 10.
 * Runtime security, deployed-role parity, SQL plans and load behavior remain
 * explicitly partial and are not promoted by these records.
 */
export function buildMandatoryPublicRacingTraceRecords(
  databaseOperationsFor: DatabaseOperationsFor,
): SecurityTraceContract[] {
  return [
    {
      traceId: "PUBLIC.HOME.READ",
      userStoryIds: ["PUBLIC.STORY.HOME"],
      productArea: "Public website",
      routePatterns: ["/"],
      screenIds: ["screen:/"],
      actionName: "Open the public homepage and read today's race summary",
      actionType: "read",
      actors: ["public visitor", "signed-in member"],
      authentication: "public",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: [],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/page.tsx", "src/components/meeting-card.tsx"],
        components: ["HomePage", "TodaysRacesSection", "MeetingCard"],
        eventHandlers: ["Open race explorer Link", "open loaded race Link"],
        forms: [],
        fields: [],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/",
        contentType: "text/html",
        credentialMode: "No credential required; incidental cookies are not used for authorization",
        requiredHeaders: [],
        csrfControl: "Not applicable to a read-only navigation",
        corsPolicy: "Browser document navigation; no cross-origin data API is exposed by this page",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/page.tsx", "src/lib/queries.ts"],
        handlers: ["HomePage", "TodaysRacesSection", "getTodaysMeetings"],
        middlewareOrder: [
          "HomePage renders the public shell",
          "TodaysRacesSection calls getTodaysMeetings",
          "getTodaysMeetings constrains the current Australia/Sydney race day",
          "getRaceExplorerMeetings projects public racing rows",
        ],
        authenticationFunction: "none (public route)",
        sessionValidationFunction: "not applicable (public route)",
        authorizationPolicy: "Public racing reference-data read; no account entitlement is required.",
        objectAuthorizationPolicy: "Only racing rows inside the calculated current race-day window are requested.",
        propertyAuthorizationPolicy: "The query projects racing reference fields and does not request account data.",
        requestValidationSchema: "No body; fixed / route and server-calculated race-day window.",
        outputSchema: "Server-rendered homepage with meeting cards or the explicit no-meetings state.",
        businessService: "getTodaysMeetings",
        repositoryMethods: ["getRaceExplorerMeetings"],
        rateLimitPolicy: "No page-specific limiter is implemented; edge/global controls are outside this source trace.",
        idempotencyPolicy: "Read-only GET.",
      },
      databaseOperations: databaseOperationsFor("PUBLIC.HOME.READ"),
      cacheOperations: [],
      backgroundOperations: [],
      externalOperations: [],
      response: {
        successStatus: 200,
        responseSchema: "HTML document containing public product content and today's race-card projection.",
        permittedFields: [
          "public product copy",
          "meeting count",
          "race count",
          "track identity",
          "race-card navigation identifiers",
        ],
        cachePolicy: "force-dynamic page; explicit CDN/browser Cache-Control was not captured in this batch",
        frontendSuccessState: "Meeting cards render, or the visitor receives the no-meetings recovery link.",
      },
      failureModes: [
        {
          condition: "Racing database read fails or returns no meetings",
          externalStatus: 200,
          safeUserMessage: "No meetings are available for this race day yet.",
          serverLogEvent: "No dedicated homepage query-failure event is implemented",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Public product content", "Public racing reference data"],
      auditEvents: [],
      securityControls: [
        "date-scoped server query",
        "explicit meeting/race/runner-group/video row caps",
        "public-read racing RLS policies",
        "explicit empty state",
        "no account-data projection",
      ],
      threats: [
        "bounded partial-day rendering above the reviewed cap",
        "cache-miss origin load",
        "silent safeQuery degradation",
      ],
      tests: [
        FOCUSED_TEST,
        "src/components/screen-contracts/public-racing-user-stories.test.ts",
      ],
      evidence: [
        "Source path: src/app/page.tsx#HomePage -> TodaysRacesSection -> src/lib/queries.ts#getTodaysMeetings -> getRaceExplorerMeetings -> rendered meeting cards or explicit empty state.",
        "Database proof: output/database-audit/home-race-meetings-read.json schema v1 captures five bounded/parent-key-bounded SELECTs, anonymous RLS replay, cost plans, the latest-video projection, no mutation and empty-state behavior as non-BYPASSRLS greyhoundiq_runtime.",
        "Residual: representative-volume planning, production deployment parity, page-level overload controls and query-failure telemetry remain unverified.",
      ],
      owner: "public-racing-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "SUPPORT.TICKET.CREATE",
      userStoryIds: ["PUBLIC.STORY.CONTACT"],
      productArea: "Member support",
      routePatterns: ["/contact", "src/app/actions.ts#createSupportTicket"],
      screenIds: ["screen:/contact"],
      actionName: "Submit an authenticated support ticket",
      actionType: "create",
      actors: ["signed-in member"],
      authentication: "required",
      allowedRoles: ["member", "moderator", "admin"],
      allowedTiers: ["free", "pro", "pro_plus"],
      requiredPermissions: ["authenticated account with a local profile"],
      requiredRelationships: ["created ticket userId equals current.dbUserId"],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/contact/page.tsx"],
        components: ["ContactPage", "SubmitButton"],
        eventHandlers: ["Next Server Action form submission"],
        forms: ["CONTACT.FORM.TICKET -> createSupportTicket"],
        fields: ["category", "body"],
        clientValidationSchemas: [
          "native required category",
          "native body minLength=20 maxLength=5000",
        ],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js Server Action",
        method: "POST",
        pathOrProcedure: "src/app/actions.ts#createSupportTicket",
        contentType: "Next Server Action form encoding",
        credentialMode: "WorkOS AuthKit session cookie resolved server-side",
        requiredHeaders: [],
        csrfControl: "Next Server Action origin/host enforcement; deployed framework parity is not tested in this batch",
        corsPolicy: "Same-origin form action",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: [
          "src/app/contact/page.tsx",
          "src/app/actions.ts",
          "src/lib/auth.ts",
          "src/lib/db-context.ts",
        ],
        handlers: ["createSupportTicket"],
        middlewareOrder: [
          "requireCurrentUserProfile",
          "checkRateLimit(support:<dbUserId>, 3, 1 hour)",
          "supportTicketSchema.parse",
          "withDbRequestContext transaction",
          "supportTicket.create",
          "cleanText(body) and supportMessage.create",
          "revalidatePath and redirect",
        ],
        authenticationFunction: "requireCurrentUserProfile",
        sessionValidationFunction: "WorkOS withAuth inside requireCurrentUserProfile",
        authorizationPolicy: "Only a caller with a current local profile reaches ticket creation.",
        objectAuthorizationPolicy: "Both inserted userId values are server-bound to current.dbUserId.",
        propertyAuthorizationPolicy: "category is allowlisted and body is bounded by supportTicketSchema; the body is sanitized by cleanText before persistence.",
        requestValidationSchema:
          "supportTicketSchema: category=general|billing|technical|feedback; body=trimmed string 20..5000",
        outputSchema: "Redirect only; no SupportTicket or SupportMessage record is serialized to the browser.",
        businessService: "createSupportTicket",
        repositoryMethods: ["tx.supportTicket.create", "tx.supportMessage.create"],
        rateLimitPolicy: "Fail closed at 3 submissions per current.dbUserId per 60 minutes.",
        idempotencyPolicy: "No idempotency key; repeated permitted submissions create distinct tickets.",
      },
      databaseOperations: databaseOperationsFor("SUPPORT.TICKET.CREATE"),
      cacheOperations: [],
      backgroundOperations: [],
      externalOperations: [],
      response: {
        successStatus: "redirect",
        responseSchema: "Redirect to /account/support?ticket=created after the transaction commits.",
        permittedFields: ["Location redirect only"],
        cachePolicy: "Mutation response is not an application response cache entry.",
        frontendSuccessState: "Account support opens with the ticket-created state.",
      },
      failureModes: [
        {
          condition: "No valid WorkOS session/local profile",
          externalStatus: "Server Action error",
          safeUserMessage: "Sign in to create a ticket.",
          serverLogEvent: "auth.unauthorized",
          retryPermitted: true,
        },
        {
          condition: "Per-user rate limit exceeded",
          externalStatus: "Server Action error",
          safeUserMessage: "Support request limit reached. Try again later.",
          serverLogEvent: "support.rate_limit",
          retryPermitted: true,
        },
        {
          condition: "Category/body validation fails",
          externalStatus: "Server Action validation error",
          safeUserMessage: "Check the category and enter a message between 20 and 5000 characters.",
          serverLogEvent: "Zod validation error; safe structured logging is not captured",
          retryPermitted: true,
        },
        {
          condition: "Request-context transaction fails",
          externalStatus: "Server Action error",
          safeUserMessage: "Your support request could not be created.",
          serverLogEvent: "No dedicated support-ticket transaction event is implemented",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Account identifier", "Support message content", "Potential PII"],
      auditEvents: [],
      securityControls: [
        "server-side authentication before side effects",
        "per-user fail-closed rate limit",
        "Zod allowlist and length bounds",
        "NUL/angle-bracket sanitization",
        "request-context transaction",
        "owner-bound insert RLS",
      ],
      threats: [
        "unauthenticated ticket spam",
        "stored markup injection",
        "cross-account ticket creation",
        "duplicate submission",
        "support-content log leakage",
      ],
      tests: [
        FOCUSED_TEST,
        "src/components/screen-contracts/screen-permission-evidence.test.ts",
        "src/components/screen-contracts/production-screen-member-support-interactions.test.ts",
        "scripts/check-rls-policies.ts",
      ],
      evidence: [
        "Source path: src/app/contact/page.tsx form -> src/app/actions.ts#createSupportTicket -> requireCurrentUserProfile -> checkRateLimit -> supportTicketSchema -> request-context two-write transaction -> redirect.",
        "Database proof: output/database-audit/support-ticket-create.json schema v1 captures the exact two-write transaction as non-BYPASSRLS greyhoundiq_runtime, both-row rollback, sanitization, permitted duplicate semantics, cost plans and hardened cross-account message denial.",
        "Residual: no idempotency key, dedicated persisted audit event, byte-level request cap, deployed Server Action integration proof or safe support-specific log-envelope test is captured.",
      ],
      owner: "member-support-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "AUTH.SIGN_IN.START",
      userStoryIds: ["PUBLIC.STORY.AUTH-ERROR"],
      productArea: "Authentication",
      routePatterns: ["/sign-in"],
      screenIds: [],
      actionName: "Start WorkOS hosted sign-in and preserve a safe internal return path",
      actionType: "authentication",
      actors: ["public visitor", "signed-out member"],
      authentication: "public",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: [],
      featureFlags: ["full-access demo bypass when explicitly enabled"],
      frontend: {
        sourceFiles: ["src/components/site-header.tsx", "src/app/auth/error/page.tsx"],
        components: ["SiteHeader", "AuthErrorPage"],
        eventHandlers: ["same-origin sign-in Link navigation"],
        forms: [],
        fields: ["returnTo", "plan", "interval"],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS redirect to WorkOS AuthKit hosted UI",
        method: "GET",
        pathOrProcedure: "/sign-in?returnTo&plan&interval",
        contentType: "redirect response",
        credentialMode: "No existing session required; AuthKit owns provider state/cookies",
        requiredHeaders: [],
        csrfControl: "Read-only initiation; callback state verification is delegated to AuthKit",
        corsPolicy: "Browser navigation; return destination must pass the internal-path allowlist",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/sign-in/route.ts", "src/lib/workos-redirect.ts"],
        handlers: ["GET", "resolveWorkosReturnTo", "resolveWorkosRedirectUri"],
        middlewareOrder: [
          "read plan/interval/returnTo query values",
          "resolveWorkosReturnTo rejects external, encoded-slash, callback and sign-in-loop destinations",
          "optional full-access demo redirect",
          "resolveWorkosRedirectUri validates the callback origin",
          "getSignInUrl builds the AuthKit hosted sign-in URL",
          "redirect to AuthKit",
        ],
        authenticationFunction: "WorkOS getSignInUrl initiation (no prior session required)",
        sessionValidationFunction: "not applicable until /callback",
        authorizationPolicy: "Public sign-in initiation only; no authenticated operation occurs on this route.",
        objectAuthorizationPolicy: "No application object is read or mutated.",
        propertyAuthorizationPolicy: "returnTo is restricted to a same-origin internal path; plan and interval are allowlisted.",
        requestValidationSchema: "resolveWorkosReturnTo and resolveWorkosRedirectUri allowlists",
        outputSchema: "Redirect to the generated WorkOS hosted sign-in URL, or a same-origin demo return path.",
        businessService: "WorkOS AuthKit getSignInUrl",
        repositoryMethods: ["No application datastore operation: redirect initiation only"],
        rateLimitPolicy: "No route-specific limiter is implemented; provider/edge abuse controls are outside this source trace.",
        idempotencyPolicy: "GET initiation creates no GreyhoundIQ datastore state.",
      },
      databaseOperations: databaseOperationsFor("AUTH.SIGN_IN.START"),
      cacheOperations: [],
      backgroundOperations: [],
      externalOperations: [
        {
          provider: "WorkOS AuthKit",
          operation: "Generate and redirect to hosted sign-in URL",
          credentialScope: "Server-held WorkOS client/configuration; exact provider scope is not captured",
          requestSchema: "{ redirectUri?: validated callback URI, returnTo: validated internal path }",
          responseSchema: "Hosted sign-in URL string",
          timeoutPolicy: "SDK URL-generation/provider timing is not independently captured",
          retryPolicy: "No automatic application retry",
          circuitBreakerPolicy: "No application circuit breaker",
          webhookFollowUp: "Authentication resumes through /callback, covered by AUTH.CALLBACK.COMPLETE",
        },
      ],
      response: {
        successStatus: "redirect",
        responseSchema: "Location redirect; no identity/provider payload is returned in the page body.",
        permittedFields: ["Location redirect"],
        cachePolicy: "No explicit route Cache-Control contract captured.",
        frontendSuccessState: "The visitor reaches WorkOS hosted sign-in and later returns through /callback.",
      },
      failureModes: [
        {
          condition: "returnTo/plan/interval is invalid or unsafe",
          externalStatus: "redirect",
          safeUserMessage: "Continue to sign in.",
          serverLogEvent: "No security event for rejected returnTo is implemented",
          retryPermitted: true,
        },
        {
          condition: "WorkOS SDK/provider initiation fails",
          externalStatus: 500,
          safeUserMessage: "Sign-in could not be started. Try again.",
          serverLogEvent: "Provider error handling/log envelope not captured",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Authentication navigation metadata"],
      auditEvents: [],
      securityControls: [
        "same-origin return-path allowlist",
        "encoded slash/backslash/control-character rejection",
        "sign-in/callback loop rejection",
        "validated callback origin",
        "WorkOS AuthKit hosted authentication",
      ],
      threats: [
        "open redirect",
        "authentication loop",
        "credential-stuffing initiation flood",
        "identity-provider outage",
      ],
      tests: [FOCUSED_TEST, "src/lib/workos-redirect.test.ts"],
      evidence: [
        "Source path: GET /sign-in -> resolveWorkosReturnTo/resolveWorkosRedirectUri -> WorkOS getSignInUrl -> redirect; unsafe return paths are deterministically tested.",
        "No application database step exists on sign-in initiation; session creation/resumption is a separate /callback trace.",
        "Residual: provider runtime, route-specific rate limiting, safe failure logging and deployed callback-origin parity remain unverified.",
      ],
      owner: "identity-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "ACCOUNT.PROTECTED.SIGNED_OUT_DENY",
      userStoryIds: ["ACCOUNT.STORY.NOTIFICATIONS"],
      productArea: "Account security",
      routePatterns: ["/account/notifications"],
      screenIds: ["screen:/account/notifications"],
      actionName: "Deny a signed-out attempt to open a protected account route",
      actionType: "read",
      actors: ["signed-out visitor"],
      authentication: "required",
      allowedRoles: ["member", "moderator", "admin"],
      allowedTiers: ["free", "pro", "pro_plus"],
      requiredPermissions: ["valid WorkOS session and local profile"],
      requiredRelationships: ["notification and preference reads belong to current.dbUserId"],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/account/notifications/page.tsx"],
        components: ["AccountNotificationsPage"],
        eventHandlers: ["document navigation to protected route"],
        forms: [],
        fields: [],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/account/notifications",
        contentType: "text/html redirect response",
        credentialMode: "WorkOS AuthKit session cookie",
        requiredHeaders: [],
        csrfControl: "Not applicable to the denied read-only navigation",
        corsPolicy: "Browser document navigation",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/account/notifications/page.tsx", "src/lib/auth.ts"],
        handlers: ["AccountNotificationsPage", "requireNotificationsProfile", "requireCurrentUserProfile"],
        middlewareOrder: [
          "AccountNotificationsPage calls requireNotificationsProfile before protected reads",
          "requireCurrentUserProfile calls WorkOS withAuth",
          "missing user throws auth.unauthorized before syncAuthUser or page queries",
          "requireNotificationsProfile catches only auth.unauthorized and redirects to /sign-in",
          "all other failures are rethrown",
        ],
        authenticationFunction: "requireCurrentUserProfile",
        sessionValidationFunction: "WorkOS withAuth",
        authorizationPolicy: "A missing session fails closed before account-scoped notification or marketing-preference reads.",
        objectAuthorizationPolicy: "No protected object query is executed on the signed-out branch.",
        propertyAuthorizationPolicy: "No account fields are returned on the signed-out branch.",
        requestValidationSchema: "Fixed protected route; no body or user-controlled object identifier.",
        outputSchema: "Redirect to /sign-in without account data.",
        businessService: "requireNotificationsProfile",
        repositoryMethods: ["No application datastore operation on the signed-out denial path"],
        rateLimitPolicy: "No page-specific limiter; the branch performs only session validation and redirect.",
        idempotencyPolicy: "Read-only denied navigation.",
      },
      databaseOperations: databaseOperationsFor("ACCOUNT.PROTECTED.SIGNED_OUT_DENY"),
      cacheOperations: [],
      backgroundOperations: [],
      externalOperations: [
        {
          provider: "WorkOS AuthKit",
          operation: "Resolve the optional current session with withAuth",
          credentialScope: "Session cookie verification; provider implementation details not independently captured",
          requestSchema: "Incoming request session cookies",
          responseSchema: "{ user } or no user",
          timeoutPolicy: "AuthKit runtime timeout not captured",
          retryPolicy: "No application retry",
          circuitBreakerPolicy: "No application circuit breaker",
          webhookFollowUp: "None",
        },
      ],
      response: {
        successStatus: "redirect",
        responseSchema: "Location: /sign-in; no protected payload.",
        permittedFields: ["Location redirect"],
        cachePolicy: "Protected response data is never produced on this branch.",
        frontendSuccessState: "The signed-out visitor reaches sign-in.",
      },
      failureModes: [
        {
          condition: "WorkOS returns no current user",
          externalStatus: "redirect",
          safeUserMessage: "Sign in to continue.",
          serverLogEvent: "auth.unauthorized is converted to a redirect; no audit event is emitted",
          retryPermitted: true,
        },
        {
          condition: "Authentication fails for a reason other than missing session",
          externalStatus: 500,
          safeUserMessage: "Account notifications are temporarily unavailable.",
          serverLogEvent: "Error is rethrown; safe structured event not captured",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Authentication state"],
      auditEvents: [],
      securityControls: [
        "server-side authentication before protected reads",
        "exact auth.unauthorized handling",
        "fail closed for other authentication errors",
        "no signed-out datastore query",
      ],
      threats: [
        "signed-out protected-data disclosure",
        "fail-open error handling",
        "cache leakage",
        "identity-provider outage",
      ],
      tests: [
        FOCUSED_TEST,
        "src/components/screen-contracts/production-screen-admin-access-state-evidence.test.ts",
      ],
      evidence: [
        "Source path: /account/notifications -> requireNotificationsProfile -> requireCurrentUserProfile -> missing user throws before syncAuthUser/page reads -> exact auth.unauthorized catch -> /sign-in redirect.",
        "No application database step exists on the signed-out branch; signed-in notification reads are intentionally outside this denial trace.",
        "Residual: live WorkOS session/redirect integration, exact redirect status and safe identity-provider failure telemetry remain unverified.",
      ],
      owner: "identity-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "RACING.RACE.SEARCH",
      userStoryIds: ["RACING.STORY.RACE-EXPLORER"],
      productArea: "Racing intelligence",
      routePatterns: ["/races?q&date&state&status&sort"],
      screenIds: ["screen:/races"],
      actionName: "Search and filter public racecards",
      actionType: "read",
      actors: ["racing visitor", "signed-in racing member"],
      authentication: "optional",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: [],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/races/page.tsx"],
        components: ["RacesPage", "AutoSubmitSelect", "RaceMeetingPanel", "RaceRowLink"],
        eventHandlers: ["GET search form", "date/state/status filter Links", "sort auto-submit"],
        forms: ["GET /races search", "GET /races date jump", "GET /races sort"],
        fields: ["q", "date", "state", "status", "sort"],
        clientValidationSchemas: ["native date input and server-owned normalizers"],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/races?q&date&state&status&sort",
        contentType: "text/html",
        credentialMode: "No credential required; a session does not expand the public projection",
        requiredHeaders: [],
        csrfControl: "Not applicable to a read-only GET",
        corsPolicy: "Same-origin browser navigation",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/races/page.tsx", "src/lib/queries.ts"],
        handlers: ["RacesPage", "getRaceExplorerData", "fetchRaceExplorerData"],
        middlewareOrder: [
          "firstParam reduces repeated query values to one value",
          "getRaceExplorerData normalizes q/date/state/status/sort",
          "q is trimmed, whitespace-collapsed and capped at 80 characters",
          "ranked search IDs are capped at 120 with dog/runner fallback caps of 80/48",
          "public race projections and summary data are loaded",
          "RacesPage renders results or the explicit empty state",
        ],
        authenticationFunction: "none required (optional session is not consumed)",
        sessionValidationFunction: "not applicable to public race search",
        authorizationPolicy: "Public racing reference-data search with the same projection for every actor.",
        objectAuthorizationPolicy: "Only race IDs returned by normalized public search/date/state/status filters are rendered.",
        propertyAuthorizationPolicy: "The explorer projection excludes account and raw provider payload fields.",
        requestValidationSchema:
          "normaliseRaceSearchParam(max80), normaliseRaceDateInput, state membership check, status allowlist, sort allowlist",
        outputSchema: "RaceExplorerData with normalized filters, summaries, meetings and bounded replay cards.",
        businessService: "getRaceExplorerData",
        repositoryMethods: [
          "findRankedRaceSearchIds",
          "findRunnerRaceSearchIds",
          "getRaceExplorerMeetings",
          "getRaceDateSummary",
        ],
        rateLimitPolicy: "No page-specific limiter is implemented; query/result bounds are the source-level cost controls.",
        idempotencyPolicy: "Read-only GET.",
      },
      databaseOperations: databaseOperationsFor("RACING.RACE.SEARCH"),
      cacheOperations: [
        {
          operation: "process-local metadata caches",
          keyShape: "race states | dataset stats | recent race dates",
          includesSecurityContext: false,
          ttlSeconds: 60,
          invalidationTriggers: ["TTL expiry", "process restart"],
        },
      ],
      backgroundOperations: [],
      externalOperations: [],
      response: {
        successStatus: 200,
        responseSchema: "HTML race explorer using normalized public RaceExplorerData.",
        permittedFields: [
          "normalized filters",
          "public dataset summary",
          "meeting and track identity",
          "race times/distances/grades",
          "runner counts",
          "replay availability",
        ],
        cachePolicy: "Filtered/search views bypass the shared default-view cache; one-minute metadata caches remain process-local.",
        frontendSuccessState: "Matching racecards render by track, or the explicit no-racecards state renders.",
      },
      failureModes: [
        {
          condition: "Search has no matching public race rows",
          externalStatus: 200,
          safeUserMessage: "No races match these filters.",
          serverLogEvent: "No dedicated no-result event (expected condition)",
          retryPermitted: true,
        },
        {
          condition: "One or more safeQuery stages fail",
          externalStatus: 200,
          safeUserMessage: "Some race data is temporarily unavailable.",
          serverLogEvent: "Partial-degradation telemetry is not captured",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Public racing reference data", "Public search terms"],
      auditEvents: [],
      securityControls: [
        "query length normalization",
        "date/status/sort allowlists",
        "parameterized Prisma and tagged-template queries",
        "ranked result caps",
        "SQL-enforced state/meeting/race/replay collection caps",
        "presentation-only replay projection",
        "public-read RLS",
        "explicit empty state",
      ],
      threats: [
        "expensive search abuse",
        "wildcard/query-complexity amplification",
        "cache-miss attack",
        "database saturation",
        "raw provider data disclosure",
      ],
      tests: [
        FOCUSED_TEST,
        "scripts/check-race-search-postgres.test.ts",
        "src/lib/queries.test.ts",
        "src/components/search-filter-controls.test.ts",
      ],
      evidence: [
        "Source path: GET /races forms -> RacesPage -> getRaceExplorerData/fetchRaceExplorerData -> normalized and capped search/read bundle -> meeting cards or empty state.",
        "Disposable runtime-role proof exercises default/date, global-dog, date-field and complete miss fallbacks; it captures 31 exact SQL variants with sanitized plans, anonymous replay, raw-provider canary exclusion, unchanged rows and exact cleanup without provider contact.",
        "Residual: no per-IP/user page limiter, deployed-environment parity, representative-volume p99 benchmark or partial-degradation alert is captured.",
      ],
      owner: "racing-data-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "RACING.RACE.OPEN",
      userStoryIds: ["RACING.STORY.RACE-DETAIL"],
      productArea: "Racing intelligence",
      routePatterns: ["/races/[id]"],
      screenIds: ["screen:/races/[id]"],
      actionName: "Open a public race detail with runners, results and safe replay resolution",
      actionType: "read",
      actors: ["racing visitor", "signed-in racing member"],
      authentication: "optional",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: [],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/races/[id]/page.tsx"],
        components: ["RacePage", "RaceReplayPlayer", "RunnerRow"],
        eventHandlers: ["open runner/dog Link", "play resolved current or previous replay"],
        forms: [],
        fields: ["race id path parameter"],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/races/[id]",
        contentType: "text/html",
        credentialMode: "No credential required",
        requiredHeaders: [],
        csrfControl: "Not applicable to a read-only GET",
        corsPolicy: "Same-origin document navigation; external replay pages/streams are server-resolved and constrained",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: [
          "src/app/races/[id]/page.tsx",
          "src/lib/queries.ts",
          "src/lib/live/race-replay.ts",
          "src/lib/live/thedogs-replay.ts",
          "src/lib/live/replay-proxy.ts",
        ],
        handlers: [
          "RacePage",
          "getRaceById",
          "getPreviousRaceVideoRunners",
          "resolveRaceVideoReplay",
          "resolveProviderRaceReplay",
          "proxiedStreamPath",
        ],
        middlewareOrder: [
          "read route race id",
          "getRaceById and notFound on null",
          "resolve stored/provider replay with host/protocol controls and 15-second fetch timeouts",
          "sign an allowed HTTPS stream into a 10-minute same-origin replay capability",
          "load at most 24 previous runner rows and resolve at most two previous replay candidates",
          "render public race, runner, result and replay fields",
        ],
        authenticationFunction: "none required (public race detail)",
        sessionValidationFunction: "not applicable",
        authorizationPolicy: "Public racing reference-data detail with no account entitlement.",
        objectAuthorizationPolicy: "The dynamic route ID is bound to getRaceById; a missing race returns not-found.",
        propertyAuthorizationPolicy: "The page renders selected public racing/replay fields and never returns provider raw JSON.",
        requestValidationSchema: "Prisma unique race id lookup; no separate path-format schema is implemented.",
        outputSchema: "Server-rendered race summary, runners/results and constrained replay presentation.",
        businessService: "getRaceById plus replay resolvers",
        repositoryMethods: ["prisma.race.findUnique", "prisma.runner.findMany"],
        rateLimitPolicy: "No page-specific limiter; replay provider calls are capped by candidate count and timeout.",
        idempotencyPolicy: "Read-only GET.",
      },
      databaseOperations: databaseOperationsFor("RACING.RACE.OPEN"),
      cacheOperations: [
        {
          operation: "React request memoization",
          keyShape: "race detail by route id",
          includesSecurityContext: false,
          ttlSeconds: null,
          invalidationTriggers: ["end of server render/request"],
        },
      ],
      backgroundOperations: [],
      externalOperations: [
        {
          provider: "The Dogs / Racing Queensland / approved replay providers",
          operation: "Resolve current and at most two previous public replay sources",
          credentialScope: "Public provider endpoints; no user credential",
          requestSchema: "provider/source identifiers and host-pinned or normalized public replay URL",
          responseSchema: "ResolvedRaceReplay metadata; stream becomes an encrypted same-origin capability only for allowlisted HTTPS hosts",
          timeoutPolicy: "15 seconds per source fetch",
          retryPolicy: "No automatic retry",
          circuitBreakerPolicy: "No application circuit breaker",
          webhookFollowUp: "None",
        },
      ],
      response: {
        successStatus: 200,
        responseSchema: "HTML race detail and constrained replay metadata/capability.",
        permittedFields: [
          "public race/track fields",
          "public runner/dog/result fields",
          "safe replay title/status/embed or same-origin capability path",
        ],
        cachePolicy: "force-dynamic page; provider fetches use no-store; explicit document Cache-Control not captured",
        frontendSuccessState: "Race detail renders with replay controls only when a safe source resolves.",
      },
      failureModes: [
        {
          condition: "Race id is missing from the public dataset",
          externalStatus: 404,
          safeUserMessage: "Race not found.",
          serverLogEvent: "No dedicated race-not-found event (expected condition)",
          retryPermitted: false,
        },
        {
          condition: "Replay provider is unavailable, times out or returns an unsafe URL",
          externalStatus: 200,
          safeUserMessage: "Replay is unavailable.",
          serverLogEvent: "Resolver catches provider failures; dedicated dependency event not captured",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Public racing reference data", "Public replay metadata"],
      auditEvents: [],
      securityControls: [
        "unique route-id lookup and notFound",
        "public-read RLS",
        "provider host/protocol validation",
        "15-second external fetch timeout",
        "two-candidate replay resolve cap",
        "HTTPS stream-host allowlist",
        "encrypted expiring same-origin replay capability",
      ],
      threats: [
        "ID-based data overexposure",
        "SSRF through provider URLs",
        "unsafe replay embed",
        "slow provider concurrency exhaustion",
        "provider URL/credential leakage",
      ],
      tests: [
        FOCUSED_TEST,
        "scripts/check-race-detail-postgres.test.ts",
        "src/components/screen-contracts/production-screen-public-racing-interactions.test.ts",
        "src/lib/live/replay-proxy.test.ts",
      ],
      evidence: [
        "Source path: /races/[id] -> getRaceById/notFound -> bounded previous-race lookup -> host/protocol-constrained replay resolvers -> encrypted same-origin replay capability or no replay -> rendered detail.",
        "Disposable runtime-role proof captures 20 exact generated SQL variants, sanitized non-ANALYZE plans, anonymous RLS replay, bounded per-dog/per-race LATERAL reads, raw-provider canary exclusion, unchanged fixture rows and exact cleanup without provider contact.",
        "Residual: representative production volume, deployed-environment parity, sustained-load p99, external dependency circuit breaker/telemetry and complete replay-provider runtime matrix remain unverified.",
      ],
      owner: "racing-data-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "RACING.DOG.OPEN",
      userStoryIds: ["RACING.STORY.DOG-DETAIL"],
      productArea: "Racing intelligence",
      routePatterns: ["/dogs/[id]"],
      screenIds: ["screen:/dogs/[id]"],
      actionName: "Open a public dog profile with form, pedigree and viewer-scoped ownership state",
      actionType: "read",
      actors: ["racing visitor", "signed-in racing member"],
      authentication: "optional",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: ["claimant-only ownership status belongs to current.profileId"],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/dogs/[id]/page.tsx"],
        components: ["DogProfilePage", "PedigreeChart", "FinishBadge"],
        eventHandlers: ["open pedigree dog Link", "open replay Link", "ownership claim form is a separate mutation trace"],
        forms: [],
        fields: ["dog id path parameter"],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/dogs/[id]",
        contentType: "text/html",
        credentialMode: "Optional WorkOS session; public detail remains available signed out",
        requiredHeaders: [],
        csrfControl: "Not applicable to the read-only page trace",
        corsPolicy: "Same-origin document navigation",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/dogs/[id]/page.tsx", "src/lib/queries.ts", "src/lib/pedigree.ts", "src/lib/auth.ts"],
        handlers: ["DogProfilePage", "getDogById", "getCurrentUser", "getDogPedigree", "getMyDogOwnership"],
        middlewareOrder: [
          "read route dog id",
          "load getDogById, optional getCurrentUser and getDogPedigree in parallel",
          "notFound on missing dog",
          "filter public ownership to approved rows",
          "only a complete current user/profile may call getMyDogOwnership under request context",
          "render public profile plus viewer-scoped claim state",
        ],
        authenticationFunction: "getCurrentUser (optional); requireCurrentUserProfile is reserved for the separate claim mutation",
        sessionValidationFunction: "WorkOS withAuth inside getCurrentUser when demo bypass is disabled",
        authorizationPolicy: "Public dog/racing detail; claimant-only state requires a complete current profile.",
        objectAuthorizationPolicy: "The dynamic dog id is bound to getDogById; missing rows return not-found; getMyDogOwnership uses dogId+current.profileId.",
        propertyAuthorizationPolicy: "Only approved ownership is presented publicly; pending/rejected status is read through the current-profile compound key.",
        requestValidationSchema: "Prisma unique dog id lookup; no separate path-format schema is implemented.",
        outputSchema: "Server-rendered public dog profile with optional current-claim status.",
        businessService: "getDogById, getDogPedigree and optional getMyDogOwnership",
        repositoryMethods: ["prisma.dog.findUnique/findMany", "tx.dogOwnership.findUnique"],
        rateLimitPolicy: "No page-specific limiter; read sizes are partly capped by recent-form/runner and pedigree limits.",
        idempotencyPolicy: "Read-only GET.",
      },
      databaseOperations: databaseOperationsFor("RACING.DOG.OPEN"),
      cacheOperations: [
        {
          operation: "React request memoization",
          keyShape: "dog detail/pedigree by route id",
          includesSecurityContext: false,
          ttlSeconds: null,
          invalidationTriggers: ["end of server render/request"],
        },
      ],
      backgroundOperations: [],
      externalOperations: [],
      response: {
        successStatus: 200,
        responseSchema: "HTML dog profile, form, pedigree, public ownership and optional current-claim state.",
        permittedFields: [
          "public dog/trainer/form/pedigree fields",
          "public racing history",
          "approved ownership display fields",
          "current claimant role/status/rejection reason when authorized",
        ],
        cachePolicy: "force-dynamic page; viewer-aware ownership state prevents a shared full-page cache contract",
        frontendSuccessState: "Dog detail renders, with a sign-in, claim, pending, rejected or approved ownership state as applicable.",
      },
      failureModes: [
        {
          condition: "Dog id is missing or the root read fails closed to null",
          externalStatus: 404,
          safeUserMessage: "Greyhound profile not found.",
          serverLogEvent: "No dedicated dog-read failure event is implemented",
          retryPermitted: true,
        },
        {
          condition: "Viewer-scoped ownership read fails",
          externalStatus: 200,
          safeUserMessage: "Ownership claim status is unavailable.",
          serverLogEvent: "safeQuery degrades to null; dedicated event not captured",
          retryPermitted: true,
        },
      ],
      dataClassification: [
        "Public racing reference data",
        "Viewer-scoped ownership status",
        "Approved-owner display name, kennel name and state",
      ],
      auditEvents: [],
      securityControls: [
        "unique route-id lookup and notFound",
        "public racing and approved-ownership RLS",
        "current-profile compound-key ownership lookup",
        "64/20/20/16 form/profile-form/runner/approved-owner caps",
        "five-generation pedigree bound",
        "presentation-only owner projection with no User join",
        "viewer-aware force-dynamic render",
      ],
      threats: [
        "cross-profile ownership disclosure",
        "query amplification across nested public racing relations",
        "public/private cache leakage",
        "raw provider data disclosure",
      ],
      tests: [
        FOCUSED_TEST,
        "scripts/check-dog-public-detail-postgres.test.ts",
        "src/components/screen-contracts/production-screen-public-racing-interactions.test.ts",
        "scripts/check-rls-policies.ts",
      ],
      evidence: [
        "Source path: /dogs/[id] -> parallel getDogById/getCurrentUser/getDogPedigree -> notFound -> approved public ownership plus optional request-context getMyDogOwnership -> viewer-aware render.",
        "Disposable runtime-role proof captures the 21 generated SELECT variants, sanitized plans, anonymous and unrelated-claimant RLS replay, approved-only owner output, bounded aggregates, five-generation clamp, galtd bridge and exact cleanup without provider contact.",
        "Residual: representative production volume, deployed-role parity, page overload controls, sustained-load p99 and dedicated query-failure telemetry remain open.",
      ],
      owner: "racing-data-platform",
      verificationStatus: "Partially verified",
    },
    {
      traceId: "RACING.TRACK.OPEN",
      userStoryIds: ["RACING.STORY.TRACK-DETAIL"],
      productArea: "Racing intelligence",
      routePatterns: ["/tracks/[id]"],
      screenIds: ["screen:/tracks/[id]"],
      actionName: "Open a public track profile with recent meetings and results",
      actionType: "read",
      actors: ["racing visitor", "signed-in racing member"],
      authentication: "optional",
      allowedRoles: [],
      allowedTiers: [],
      requiredPermissions: [],
      requiredRelationships: [],
      featureFlags: [],
      frontend: {
        sourceFiles: ["src/app/tracks/[id]/page.tsx"],
        components: ["TrackDetailPage"],
        eventHandlers: ["return to tracks Link", "open loaded race Link"],
        forms: [],
        fields: ["track id path parameter"],
        clientValidationSchemas: [],
        clientStateStores: [],
        sensitiveBrowserStorage: [],
      },
      transport: {
        protocol: "HTTPS Next.js server-component navigation",
        method: "GET",
        pathOrProcedure: "/tracks/[id]",
        contentType: "text/html",
        credentialMode: "No credential required",
        requiredHeaders: [],
        csrfControl: "Not applicable to a read-only GET",
        corsPolicy: "Same-origin document navigation",
        maximumRequestBytes: null,
        timeoutMilliseconds: null,
      },
      server: {
        entryFiles: ["src/app/tracks/[id]/page.tsx", "src/lib/queries.ts"],
        handlers: ["TrackDetailPage", "getTrackById"],
        middlewareOrder: [
          "read route track id",
          "getTrackById selects one public track, then bounded meeting/race/runner stages",
          "compose at most eight meetings, sixteen races per meeting and twelve runners per race",
          "notFound on null",
          "render track profile, recent meetings, races and box-win context",
        ],
        authenticationFunction: "none required (public track detail)",
        sessionValidationFunction: "not applicable",
        authorizationPolicy: "Public racing reference-data detail with no account entitlement.",
        objectAuthorizationPolicy: "The dynamic track id is bound to getTrackById; a missing track returns not-found.",
        propertyAuthorizationPolicy: "The query selects public track/meeting/race/runner/dog/result fields and no account data.",
        requestValidationSchema: "Prisma unique track id lookup; no separate path-format schema is implemented.",
        outputSchema: "Server-rendered track profile and recent meeting/race projections.",
        businessService: "getTrackById",
        repositoryMethods: [
          "prisma.track.findUnique",
          "prisma.meeting.findMany (take 8)",
          "prisma.race.findMany (take 128; compose at most 16 per meeting)",
          "prisma.runner.findMany with Dog/Result (take 1536; compose at most 12 per race)",
        ],
        rateLimitPolicy:
          "No page-specific limiter; database work is bounded to one track, 8 meetings, 128 races and 1,536 runners before per-parent composition caps.",
        idempotencyPolicy: "Read-only GET.",
      },
      databaseOperations: databaseOperationsFor("RACING.TRACK.OPEN"),
      cacheOperations: [
        {
          operation: "React request memoization",
          keyShape: "track detail by route id",
          includesSecurityContext: false,
          ttlSeconds: null,
          invalidationTriggers: ["end of server render/request"],
        },
      ],
      backgroundOperations: [],
      externalOperations: [],
      response: {
        successStatus: 200,
        responseSchema: "HTML track profile with recent meetings, race links and box-win context.",
        permittedFields: ["public track fields", "recent meeting/race fields", "runner/dog/result summary fields"],
        cachePolicy: "force-dynamic page; explicit CDN/browser Cache-Control was not captured in this batch",
        frontendSuccessState: "Track detail renders with recent meetings and race navigation.",
      },
      failureModes: [
        {
          condition: "Track id is missing or the read fails closed to null",
          externalStatus: 404,
          safeUserMessage: "Track not found.",
          serverLogEvent: "No dedicated track-read failure event is implemented",
          retryPermitted: true,
        },
      ],
      dataClassification: ["Public racing reference data"],
      auditEvents: [],
      securityControls: [
        "unique route-id lookup and notFound",
        "public-read racing RLS",
        "8-meeting, 128-race and 1,536-runner SQL caps",
        "16-race-per-meeting and 12-runner-per-race composition caps",
        "no account-data projection",
      ],
      threats: [
        "bounded detail-graph exhaustion at the allowed maximum",
        "database saturation",
        "raw provider data disclosure",
      ],
      tests: [
        FOCUSED_TEST,
        "src/components/screen-contracts/production-screen-public-racing-interactions.test.ts",
      ],
      evidence: [
        "Source path: /tracks/[id] -> getTrackById -> bounded Track/Meeting/Race/Runner/Dog/Result reads -> notFound or public track/race render.",
        "Schema-v16 disposable evidence executes the real populated getTrackById graph under non-superuser, non-BYPASSRLS greyhoundiq_runtime, captures six exact parameterized SQL shapes and sanitized plans, replays them under anonymous RLS, proves missing-ID behavior and cleans the exact probe graph.",
        "Residual: representative-volume plans, deployed-environment parity, page-specific overload controls and sustained page-load p99 remain unverified.",
      ],
      owner: "racing-data-platform",
      verificationStatus: "Partially verified",
    },
  ];
}
