import type { RegistryEvidence, VerificationStatus } from "./shared";

export type ApiRateLimitMethod =
  | "GET"
  | "POST"
  | "PUT"
  | "PATCH"
  | "DELETE"
  | "HEAD"
  | "OPTIONS";

export type RateLimitContract = {
  scope: "api-operation";
  rateLimitId: string;
  traceIds: readonly string[];
  route: string;
  method: ApiRateLimitMethod;
  operationId: string;
  limiterKind: "database-distributed" | "process-local";
  keyShape: string;
  sourceKeyExpression: string;
  maximum: number;
  configuredMaximums?: readonly number[];
  windowMilliseconds: number;
  failMode: "closed" | "not verified";
  sourceFile: string;
  sourceSymbol: string;
  evidence: readonly RegistryEvidence[];
  owner: string;
  verificationStatus: VerificationStatus;
};

type RateLimitInput = {
  route: string;
  method: ApiRateLimitMethod;
  operationId: string;
  keyShape: string;
  sourceKeyExpression: string;
  maximum: number;
  configuredMaximums?: readonly number[];
  windowMilliseconds: number;
  owner: string;
  rateLimitId?: string;
  traceIds?: readonly string[];
  failClosed?: boolean;
  evidenceNote?: string;
};

const SOURCE_ONLY_EVIDENCE_NOTE =
  "Source-level limiter call is registered; deployed behavior is not verified.";

function databaseRateLimit(input: RateLimitInput): RateLimitContract {
  return apiRateLimit(input, "database-distributed");
}

function localRateLimit(input: RateLimitInput): RateLimitContract {
  return apiRateLimit(input, "process-local");
}

function apiRateLimit(
  input: RateLimitInput,
  limiterKind: RateLimitContract["limiterKind"]
): RateLimitContract {
  const sourceFile = `src/app${input.route}/route.ts`;
  return {
    scope: "api-operation",
    rateLimitId: input.rateLimitId ?? `RATE.API.${input.operationId}`,
    traceIds: input.traceIds ?? [],
    route: input.route,
    method: input.method,
    operationId: input.operationId,
    limiterKind,
    keyShape: input.keyShape,
    sourceKeyExpression: input.sourceKeyExpression,
    maximum: input.maximum,
    ...(input.configuredMaximums
      ? { configuredMaximums: input.configuredMaximums }
      : {}),
    windowMilliseconds: input.windowMilliseconds,
    failMode: input.failClosed ? "closed" : "not verified",
    sourceFile,
    sourceSymbol: input.method,
    evidence: [
      {
        sourceFile,
        sourceSymbol: input.method,
        note: input.evidenceNote ?? SOURCE_ONLY_EVIDENCE_NOTE,
      },
    ],
    owner: input.owner,
    verificationStatus: "Partially verified",
  };
}

/**
 * Canonical source-level registry for runtime-limited `src/app/api` operations.
 * Server actions and non-API route handlers are deliberately outside this scope.
 */
export const RATE_LIMITS: readonly RateLimitContract[] = [
  databaseRateLimit({
    route: "/api/analytics/onboarding",
    method: "POST",
    operationId: "postAnalyticsOnboarding",
    keyShape: "analytics:onboarding:global",
    sourceKeyExpression: "ONBOARDING_ANALYTICS_RATE_LIMIT_KEY",
    maximum: 6_000,
    windowMilliseconds: 60_000,
    owner: "onboarding-observability",
    rateLimitId: "RATE.ONBOARDING.ANALYTICS.INGEST",
    traceIds: ["ONBOARDING.ANALYTICS.RECORD"],
    failClosed: true,
    evidenceNote:
      "The non-identifying global counter is checked with failClosed: true before reading the bounded body; the official client does not retry denied or failed delivery. Deployed behavior is not verified.",
  }),
  databaseRateLimit({
    route: "/api/actors/[actorId]/mute",
    method: "POST",
    operationId: "postActorsByActorIdMute",
    keyShape: "actor:mute:<db-user-id>:<actor-id>",
    sourceKeyExpression: "`actor:mute:${current.dbUserId}:${actorId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/agents/[type]/run",
    method: "POST",
    operationId: "postAgentsByTypeRun",
    keyShape: "agent-run:<db-user-id>",
    sourceKeyExpression: "`agent-run:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "agent-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/agents/runs/[id]/cancel",
    method: "POST",
    operationId: "postAgentsRunsByIdCancel",
    keyShape: "agent-run:cancel:<db-user-id>",
    sourceKeyExpression: "`agent-run:cancel:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "agent-security",
  }),
  databaseRateLimit({
    route: "/api/billing/bespoke/checkout",
    method: "POST",
    operationId: "postBillingBespokeCheckout",
    keyShape: "stripe:bespoke:<db-user-id>",
    sourceKeyExpression: "`stripe:bespoke:${current.dbUserId}`",
    maximum: 5,
    windowMilliseconds: 60_000,
    owner: "billing-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/billing/checkout",
    method: "POST",
    operationId: "postBillingCheckout",
    keyShape: "stripe:checkout:<db-user-id>",
    sourceKeyExpression: "`stripe:checkout:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "billing-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/billing/portal",
    method: "POST",
    operationId: "postBillingPortal",
    keyShape: "stripe:portal:<db-user-id>",
    sourceKeyExpression: "`stripe:portal:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "billing-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/calls/[roomId]/end",
    method: "POST",
    operationId: "postCallsByRoomIdEnd",
    keyShape: "call:end:<db-user-id>:<room-id>",
    sourceKeyExpression: "`call:end:${current.dbUserId}:${parsedRoomId}`",
    maximum: 20,
    windowMilliseconds: 600_000,
    owner: "communications-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/calls/[roomId]/invite",
    method: "POST",
    operationId: "postCallsByRoomIdInvite",
    keyShape: "call:invite:<db-user-id>:<room-id>",
    sourceKeyExpression: "`call:invite:${current.dbUserId}:${parsedRoomId}`",
    maximum: 20,
    windowMilliseconds: 600_000,
    owner: "communications-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/calls/[roomId]/token",
    method: "POST",
    operationId: "postCallsByRoomIdToken",
    keyShape: "call:token:<db-user-id>:<room-id>",
    sourceKeyExpression: "`call:token:${current.dbUserId}:${parsedRoomId}`",
    maximum: 20,
    windowMilliseconds: 600_000,
    owner: "communications-security",
  }),
  databaseRateLimit({
    route: "/api/calls/rooms",
    method: "POST",
    operationId: "postCallsRooms",
    keyShape: "call:room:<db-user-id>",
    sourceKeyExpression: "`call:room:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 600_000,
    owner: "communications-security",
  }),
  databaseRateLimit({
    route: "/api/conversations",
    method: "POST",
    operationId: "postConversations",
    keyShape: "conversation:start:<db-user-id>",
    sourceKeyExpression: "`conversation:start:${current.dbUserId}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/block",
    method: "DELETE",
    operationId: "deleteConversationsByIdBlock",
    keyShape: "conversation:unblock:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`conversation:unblock:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/block",
    method: "POST",
    operationId: "postConversationsByIdBlock",
    keyShape: "conversation:block:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`conversation:block:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "community-security",
    rateLimitId: "RATE.PULSE.CONVERSATION.BLOCK",
    traceIds: ["PULSE.CONVERSATION.BLOCK"],
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/messages",
    method: "POST",
    operationId: "postConversationsByIdMessages",
    keyShape: "conversation:message:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`conversation:message:${current.dbUserId}:${id}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/messages/[msgId]",
    method: "DELETE",
    operationId: "deleteConversationsByIdMessagesByMsgId",
    keyShape: "conversation:message:delete:<db-user-id>:<message-id>",
    sourceKeyExpression:
      "`conversation:message:delete:${current.dbUserId}:${msgId}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/read",
    method: "POST",
    operationId: "postConversationsByIdRead",
    keyShape: "conversation:read:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`conversation:read:${current.dbUserId}:${id}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/delivered",
    method: "POST",
    operationId: "postConversationsByIdDelivered",
    keyShape: "conversation:delivered:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`conversation:delivered:${current.dbUserId}:${id}`",
    maximum: 20,
    windowMilliseconds: 60_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/conversations/[id]/search",
    method: "GET",
    operationId: "getConversationsByIdSearch",
    keyShape: "message:search:<db-user-id>:<conversation-id>",
    sourceKeyExpression: "`message:search:${current.dbUserId}:${id}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/discover",
    method: "GET",
    operationId: "getDiscover",
    keyShape:
      "discover:user:<db-user-id> or discover:ip:<client-ip-or-missing-forwarded-for>",
    sourceKeyExpression: "rateLimitKey",
    maximum: 60,
    configuredMaximums: [10, 60],
    windowMilliseconds: 60_000,
    owner: "discovery-security",
  }),
  databaseRateLimit({
    route: "/api/dogs/[id]/claim",
    method: "POST",
    operationId: "postDogsByIdClaim",
    keyShape: "dog:claim:<db-user-id>",
    sourceKeyExpression: "`dog:claim:${current.dbUserId}`",
    maximum: 5,
    windowMilliseconds: 86_400_000,
    owner: "racing-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/dogs/search",
    method: "GET",
    operationId: "getDogsSearch",
    keyShape: "dog:search:<client-ip-or-missing-forwarded-for>",
    sourceKeyExpression:
      "`dog:search:${clientIp || \"missing-forwarded-for\"}`",
    maximum: 60,
    configuredMaximums: [10, 60],
    windowMilliseconds: 60_000,
    owner: "racing-security",
  }),
  databaseRateLimit({
    route: "/api/feed",
    method: "POST",
    operationId: "postFeed",
    keyShape: "feed:post:<db-user-id>",
    sourceKeyExpression: "`feed:post:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]",
    method: "DELETE",
    operationId: "deleteFeedByPostId",
    keyShape: "feed:mutation:<db-user-id>",
    sourceKeyExpression: "`feed:mutation:${userId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]",
    method: "PATCH",
    operationId: "patchFeedByPostId",
    keyShape: "feed:mutation:<db-user-id>",
    sourceKeyExpression: "`feed:mutation:${userId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]/comments",
    method: "POST",
    operationId: "postFeedByPostIdComments",
    keyShape: "feed:comment:<db-user-id>",
    sourceKeyExpression: "`feed:comment:${current.dbUserId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]/reaction",
    method: "POST",
    operationId: "postFeedByPostIdReaction",
    keyShape: "feed:reaction:<db-user-id>",
    sourceKeyExpression: "`feed:reaction:${current.dbUserId}`",
    maximum: 60,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]/save",
    method: "POST",
    operationId: "postFeedByPostIdSave",
    keyShape: "feed:save:<db-user-id>",
    sourceKeyExpression: "`feed:save:${current.dbUserId}`",
    maximum: 60,
    windowMilliseconds: 60_000,
    owner: "feed-security",
  }),
  databaseRateLimit({
    route: "/api/feed/[postId]/share",
    method: "POST",
    operationId: "postFeedByPostIdShare",
    keyShape: "feed:share:<db-user-id>",
    sourceKeyExpression: "`feed:share:${current.dbUserId}`",
    maximum: 20,
    windowMilliseconds: 60_000,
    owner: "feed-security",
  }),
  databaseRateLimit({
    route: "/api/feed/comments/[commentId]",
    method: "DELETE",
    operationId: "deleteFeedCommentsByCommentId",
    keyShape: "feed:comment-mutation:<db-user-id>",
    sourceKeyExpression: "`feed:comment-mutation:${userId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
  }),
  databaseRateLimit({
    route: "/api/feed/comments/[commentId]",
    method: "PATCH",
    operationId: "patchFeedCommentsByCommentId",
    keyShape: "feed:comment-mutation:<db-user-id>",
    sourceKeyExpression: "`feed:comment-mutation:${userId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
  }),
  databaseRateLimit({
    route: "/api/feed/comments/[commentId]/reaction",
    method: "POST",
    operationId: "postFeedCommentsByCommentIdReaction",
    keyShape: "feed:comment-reaction:<db-user-id>",
    sourceKeyExpression: "`feed:comment-reaction:${current.dbUserId}`",
    maximum: 60,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/feed/topics/[topicId]/follow",
    method: "POST",
    operationId: "postFeedTopicsByTopicIdFollow",
    keyShape: "feed:topic-follow:<db-user-id>",
    sourceKeyExpression: "`feed:topic-follow:${current.dbUserId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "feed-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/forum/categories/[slug]/threads",
    method: "POST",
    operationId: "postForumCategoriesBySlugThreads",
    keyShape: "forum:thread:create:<db-user-id>:<category-slug>",
    sourceKeyExpression: "`forum:thread:create:${current.dbUserId}:${slug}`",
    maximum: 3,
    windowMilliseconds: 600_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/forum/threads/[id]/posts",
    method: "POST",
    operationId: "postForumThreadsByIdPosts",
    keyShape: "forum:post:create:<db-user-id>:<thread-id>",
    sourceKeyExpression: "`forum:post:create:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/listings",
    method: "POST",
    operationId: "postListings",
    keyShape: "listing:create:<db-user-id>",
    sourceKeyExpression: "`listing:create:${current.dbUserId}`",
    maximum: 3,
    windowMilliseconds: 600_000,
    owner: "marketplace-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/listings/[id]",
    method: "PATCH",
    operationId: "patchListingsById",
    keyShape: "listing:update:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:update:${current.dbUserId}:${id}`",
    maximum: 10,
    windowMilliseconds: 600_000,
    owner: "marketplace-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/listings/[id]/enquiry",
    method: "POST",
    operationId: "postListingsByIdEnquiry",
    keyShape: "listing:enquiry:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:enquiry:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "marketplace-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/listings/[id]/renew",
    method: "POST",
    operationId: "postListingsByIdRenew",
    keyShape: "listing:renew:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:renew:${current.dbUserId}:${id}`",
    maximum: 3,
    windowMilliseconds: 3_600_000,
    owner: "marketplace-security",
  }),
  databaseRateLimit({
    route: "/api/listings/[id]/save",
    method: "POST",
    operationId: "postListingsByIdSave",
    keyShape: "listing:save:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:save:${current.dbUserId}:${id}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "marketplace-security",
  }),
  databaseRateLimit({
    route: "/api/listings/[id]/sold",
    method: "POST",
    operationId: "postListingsByIdSold",
    keyShape: "listing:sold:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:sold:${current.dbUserId}:${id}`",
    maximum: 3,
    windowMilliseconds: 600_000,
    owner: "marketplace-security",
  }),
  databaseRateLimit({
    route: "/api/listings/[id]/withdraw",
    method: "POST",
    operationId: "postListingsByIdWithdraw",
    keyShape: "listing:withdraw:<db-user-id>:<listing-id>",
    sourceKeyExpression: "`listing:withdraw:${current.dbUserId}:${id}`",
    maximum: 3,
    windowMilliseconds: 600_000,
    owner: "marketplace-security",
  }),
  databaseRateLimit({
    route: "/api/media/[id]",
    method: "DELETE",
    operationId: "deleteMediaById",
    keyShape: "media:delete:<db-user-id>:<media-id>",
    sourceKeyExpression: "`media:delete:${current.dbUserId}:${id}`",
    maximum: 3,
    windowMilliseconds: 600_000,
    owner: "media-security",
    rateLimitId: "RATE.MEDIA.DELETE",
    traceIds: ["MEDIA.ASSET.DELETE"],
  }),
  databaseRateLimit({
    route: "/api/media/[id]",
    method: "PATCH",
    operationId: "patchMediaById",
    keyShape: "media:metadata:<db-user-id>:<media-id>",
    sourceKeyExpression: "`media:metadata:${current.dbUserId}:${id}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "media-security",
  }),
  databaseRateLimit({
    route: "/api/media/[id]/caption",
    method: "DELETE",
    operationId: "deleteMediaByIdCaption",
    keyShape: "media:caption:delete:<db-user-id>:<media-id>",
    sourceKeyExpression:
      "`media:caption:${operation}:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 60_000,
    owner: "media-security",
  }),
  databaseRateLimit({
    route: "/api/media/[id]/caption",
    method: "PUT",
    operationId: "putMediaByIdCaption",
    keyShape: "media:caption:update:<db-user-id>:<media-id>",
    sourceKeyExpression:
      "`media:caption:${operation}:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 60_000,
    owner: "media-security",
  }),
  databaseRateLimit({
    route: "/api/media/[id]/finalize",
    method: "POST",
    operationId: "postMediaByIdFinalize",
    keyShape: "media:finalize:<db-user-id>:<media-id>",
    sourceKeyExpression: "`media:finalize:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 60_000,
    owner: "media-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/media/sign-upload",
    method: "POST",
    operationId: "postMediaSignUpload",
    keyShape: "media:sign-upload:<db-user-id>",
    sourceKeyExpression: "`media:sign-upload:${current.dbUserId}`",
    maximum: 20,
    windowMilliseconds: 60_000,
    owner: "media-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/memory",
    method: "POST",
    operationId: "postMemory",
    keyShape: "memory:create:<db-user-id>",
    sourceKeyExpression: "`memory:create:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "memory-security",
  }),
  databaseRateLimit({
    route: "/api/memory/[id]",
    method: "DELETE",
    operationId: "deleteMemoryById",
    keyShape: "memory:delete:<db-user-id>:<memory-id>",
    sourceKeyExpression: "`memory:delete:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "memory-security",
  }),
  databaseRateLimit({
    route: "/api/memory/[id]/supersede",
    method: "POST",
    operationId: "postMemoryByIdSupersede",
    keyShape: "memory:supersede:<db-user-id>:<memory-id>",
    sourceKeyExpression: "`memory:supersede:${current.dbUserId}:${id}`",
    maximum: 5,
    windowMilliseconds: 600_000,
    owner: "memory-security",
  }),
  databaseRateLimit({
    route: "/api/messages",
    method: "POST",
    operationId: "postMessages",
    keyShape: "message:send:<db-user-id>",
    sourceKeyExpression: "`message:send:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "community-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/profiles/messaging",
    method: "GET",
    operationId: "getProfilesMessaging",
    keyShape: "profiles:messaging:<db-user-id>",
    sourceKeyExpression: "`profiles:messaging:${current.dbUserId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "community-security",
  }),
  databaseRateLimit({
    route: "/api/realtime/token",
    method: "POST",
    operationId: "postRealtimeToken",
    keyShape: "realtime:token:<db-user-id>",
    sourceKeyExpression: "`realtime:token:${current.dbUserId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "realtime-security",
  }),
  localRateLimit({
    route: "/api/replay/stream",
    method: "GET",
    operationId: "getReplayStream",
    keyShape: "replay:stream:<trusted-client-ip-or-missing-forwarded-for>",
    sourceKeyExpression: "`replay:stream:${clientKey}`",
    maximum: 120,
    configuredMaximums: [30, 120],
    windowMilliseconds: 60_000,
    owner: "live-security",
    evidenceNote:
      "Source derives clientKey only from the trusted client-IP extractor or the fixed missing-forwarded-for bucket; capability tokens and provider secrets are excluded. Process-local and deployed behavior is not verified.",
  }),
  databaseRateLimit({
    route: "/api/reports",
    method: "POST",
    operationId: "postReports",
    keyShape: "report:create:<db-user-id>",
    sourceKeyExpression: "`report:create:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "trust-safety-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/reports/[id]/resolve",
    method: "POST",
    operationId: "postReportsByIdResolve",
    keyShape: "report:resolve:<db-user-id>",
    sourceKeyExpression: "`report:resolve:${current.dbUserId}`",
    maximum: 30,
    windowMilliseconds: 60_000,
    owner: "trust-safety-security",
  }),
  databaseRateLimit({
    route: "/api/users/me/delete",
    method: "POST",
    operationId: "postUsersMeDelete",
    keyShape: "account-delete:request:<db-user-id>",
    sourceKeyExpression: "`account-delete:request:${current.dbUserId}`",
    maximum: 3,
    windowMilliseconds: 3_600_000,
    owner: "account-security",
    traceIds: ["ACCOUNT.DELETION.EXECUTE"],
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/users/me/export",
    method: "POST",
    operationId: "postUsersMeExport",
    keyShape: "user-export:<db-user-id>",
    sourceKeyExpression: "`user-export:${current.dbUserId}`",
    maximum: 3,
    windowMilliseconds: 3_600_000,
    owner: "account-security",
    traceIds: ["ACCOUNT.DATA_EXPORT.DOWNLOAD"],
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/users/me/marketing-preferences",
    method: "POST",
    operationId: "postUsersMeMarketingPreferences",
    keyShape: "marketing-preference:email:<db-user-id>",
    sourceKeyExpression: "`marketing-preference:email:${current.dbUserId}`",
    maximum: 20,
    windowMilliseconds: 60_000,
    owner: "account-security",
  }),
  databaseRateLimit({
    route: "/api/users/me/profile",
    method: "PATCH",
    operationId: "patchUsersMeProfile",
    keyShape: "profile:update:<db-user-id>",
    sourceKeyExpression: "`profile:update:${current.dbUserId}`",
    maximum: 10,
    windowMilliseconds: 60_000,
    owner: "account-security",
  }),
  databaseRateLimit({
    route: "/api/webhooks/lago",
    method: "POST",
    operationId: "postWebhooksLago",
    keyShape: "lago-webhook:<client-ip-or-missing-forwarded-for>",
    sourceKeyExpression: "getLagoWebhookRateLimitKey(request.headers)",
    maximum: 1000,
    windowMilliseconds: 60_000,
    owner: "billing-security",
    failClosed: true,
  }),
  databaseRateLimit({
    route: "/api/webhooks/stripe",
    method: "POST",
    operationId: "postWebhooksStripe",
    keyShape: "stripe-webhook:<client-ip-or-missing-forwarded-for>",
    sourceKeyExpression: "getStripeWebhookRateLimitKey(request.headers)",
    maximum: 1000,
    windowMilliseconds: 60_000,
    owner: "billing-security",
    rateLimitId: "RATE.BILLING.STRIPE_WEBHOOK",
    traceIds: ["BILLING.WEBHOOK.PROCESS"],
    failClosed: true,
    evidenceNote:
      "checkRateLimit is called with failClosed: true before reading the body; deployed behavior is not verified.",
  }),
];
