import type { RegistryEvidence, VerificationStatus } from "./shared";

export type ThirdPartyContract = {
  providerId: string;
  provider: string;
  purpose: string;
  dataSent: string[];
  dataReceived: string[];
  personalInformation: string[];
  credentials: string[];
  credentialScope: string;
  credentialStorage: string;
  credentialRotation: string;
  environments: string[];
  allowedHosts: string[];
  tlsVerification: string;
  requestTimeout: string;
  retryPolicy: string;
  circuitBreaker: string;
  rateLimit: string;
  costLimit: string;
  responseValidation: string;
  webhookSecurity: string;
  dataRetention: string;
  providerLogging: string;
  knownSubprocessors: string[];
  failureFallback: string;
  incidentContact: string;
  sourceFiles: string[];
  evidence: RegistryEvidence[];
  responsibleOwner: string;
  verificationStatus: VerificationStatus;
};

export const THIRD_PARTIES = [
  {
    providerId: "THIRD_PARTY.WORKOS",
    provider: "WorkOS AuthKit",
    purpose: "Authentication and identity callback handling.",
    dataSent: ["authentication request parameters"],
    dataReceived: ["callback code/state through the SDK", "identity profile on success"],
    personalInformation: ["identity profile"],
    credentials: ["server credential type and grant are not verified"],
    credentialScope: "WorkOS server credentials; exact scope not verified.",
    credentialStorage: "Environment/secret manager expected; not verified by this registry seed.",
    credentialRotation: "Not verified.",
    environments: ["Not verified."],
    allowedHosts: ["AuthKit SDK provider endpoints; exact hosts not verified"],
    tlsVerification: "Not verified.",
    requestTimeout: "SDK default; not verified.",
    retryPolicy: "User-initiated safe retry from /auth/error.",
    circuitBreaker: "Not verified.",
    rateLimit: "Not verified.",
    costLimit: "Not verified.",
    responseValidation: "AuthKit SDK callback validation; independently not verified.",
    webhookSecurity: "Not applicable; callback flow.",
    dataRetention: "Not verified.",
    providerLogging: "Not verified.",
    knownSubprocessors: ["Not verified."],
    failureFallback: "Allowlisted /auth/error recovery page.",
    incidentContact: "Not recorded.",
    sourceFiles: ["src/app/callback/route.ts", "src/lib/workos-redirect.ts"],
    evidence: [],
    responsibleOwner: "identity-security",
    verificationStatus: "Partially verified",
  },
  {
    providerId: "THIRD_PARTY.STRIPE",
    provider: "Stripe",
    purpose: "Checkout, subscription and webhook billing lifecycle.",
    dataSent: ["server-selected checkout and customer context"],
    dataReceived: ["signed webhook events", "provider billing objects"],
    personalInformation: ["provider customer linkage", "billing status"],
    credentials: ["server secret and webhook signing secret; exact grant not verified"],
    credentialScope: "Stripe secret and webhook secret; exact restricted-key scope not verified.",
    credentialStorage: "Server environment/secret manager; repository values not included.",
    credentialRotation: "Not verified.",
    environments: ["Not verified."],
    allowedHosts: ["Stripe SDK configured endpoint"],
    tlsVerification: "Not verified.",
    requestTimeout: "Not verified.",
    retryPolicy:
      "Stripe transport retries are bounded to two and every mutating create call carries an explicit idempotency key; inbound event ID and payload hash deduplicate webhook delivery.",
    circuitBreaker: "Not verified.",
    rateLimit: "Not verified.",
    costLimit: "Not verified.",
    responseValidation: "Webhook signature plus event-specific settlement validation.",
    webhookSecurity: "Raw-body signature verification and duplicate detection.",
    dataRetention: "Raw webhook payload retention not verified.",
    providerLogging: "Not verified.",
    knownSubprocessors: ["Not verified."],
    failureFallback: "Generic safe error; provider retries are expected.",
    incidentContact: "Not recorded.",
    sourceFiles: [
      "src/app/api/webhooks/stripe/route.ts",
      "src/lib/billing/stripe-webhooks.ts",
    ],
    evidence: [],
    responsibleOwner: "billing-security",
    verificationStatus: "Partially verified",
  },
  {
    providerId: "THIRD_PARTY.SUPABASE_REALTIME",
    provider: "Supabase Realtime",
    purpose: "Private conversation/profile broadcast authorization and presence.",
    dataSent: ["opaque HMAC topic", "profile ID", "grant expiry"],
    dataReceived: ["RPC and channel operation result"],
    personalInformation: ["profile ID", "conversation access relationship"],
    credentials: ["server administrative credential type and grant are not verified"],
    credentialScope: "Supabase server administrative client; exact project role not verified.",
    credentialStorage: "Server environment/secret manager; client exposure prohibited.",
    credentialRotation: "Not verified.",
    environments: ["Not verified."],
    allowedHosts: ["Configured SUPABASE_URL/NEXT_PUBLIC_SUPABASE_URL host"],
    tlsVerification: "Not verified.",
    requestTimeout: "Not verified.",
    retryPolicy: "Block fails when grant revocation reports an error.",
    circuitBreaker: "Not verified.",
    rateLimit: "Not verified.",
    costLimit: "Not verified.",
    responseValidation: "Supabase client error field is checked.",
    webhookSecurity: "Not applicable.",
    dataRetention: "Grant TTL is ten minutes; provider-side retention not verified.",
    providerLogging: "Not verified.",
    knownSubprocessors: ["Not verified."],
    failureFallback: "realtime.grant_revoke_failed; block action fails before audit/broadcast completion.",
    incidentContact: "Not recorded.",
    sourceFiles: ["src/lib/realtime-service.ts"],
    evidence: [
      {
        sourceFile: "src/lib/realtime-service.ts",
        sourceSymbol: "revokeConversationRealtimeGrants",
        note: "The block flow revokes the opaque conversation topic for both participant profiles.",
      },
    ],
    responsibleOwner: "realtime-security",
    verificationStatus: "Partially verified",
  },
  {
    providerId: "THIRD_PARTY.SUPABASE_STORAGE",
    provider: "Supabase Storage",
    purpose: "Private user-media object storage and removal.",
    dataSent: ["server-generated object path", "media bytes during upload", "delete path"],
    dataReceived: ["signed access data", "storage operation result"],
    personalInformation: ["user media"],
    credentials: ["server administrative credential type and grant are not verified"],
    credentialScope: "Supabase server administrative client; exact project role not verified.",
    credentialStorage: "Server environment/secret manager; client exposure prohibited.",
    credentialRotation: "Not verified.",
    environments: ["Not verified."],
    allowedHosts: ["Configured SUPABASE_URL/NEXT_PUBLIC_SUPABASE_URL host"],
    tlsVerification: "Not verified.",
    requestTimeout: "Not verified.",
    retryPolicy: "Delete logs storage failure and preserves the database tombstone.",
    circuitBreaker: "Not verified.",
    rateLimit: "Not verified.",
    costLimit: "Not verified.",
    responseValidation: "Client error handling exists; full provider schema validation not verified.",
    webhookSecurity: "Not applicable.",
    dataRetention: "Not verified.",
    providerLogging: "Not verified.",
    knownSubprocessors: ["Not verified."],
    failureFallback: "Safe log event with media ID; no provider error is returned directly.",
    incidentContact: "Not recorded.",
    sourceFiles: ["src/lib/media-service.ts", "src/lib/supabase-storage.ts"],
    evidence: [],
    responsibleOwner: "media-security",
    verificationStatus: "Partially verified",
  },
  externalService({
    providerId: "THIRD_PARTY.LAGO",
    provider: "Lago",
    purpose: "Usage metering, plans, invoices and signed billing lifecycle events.",
    dataSent: ["external customer ID", "billable metric code", "usage transaction ID", "bounded metric properties"],
    dataReceived: ["signed webhook events", "invoice and subscription state"],
    personalInformation: ["account billing linkage", "usage associated with an account"],
    credentials: ["LAGO_API_KEY", "LAGO_WEBHOOK_SECRET"],
    credentialScope: "Dedicated server API key and webhook signing secret; exact provider grants are not verified.",
    allowedHosts: ["Configured LAGO_API_URL and LAGO_FRONT_URL"],
    responseValidation: "HTTP status is checked and signed webhook payloads pass the local Lago reducer contract.",
    webhookSecurity: "HMAC verification, event identity and dry-run replay tooling; deployed delivery remains unverified.",
    failureFallback: "Usage remains in the durable local outbox for bounded retry; entitlement is not granted by a browser return.",
    sourceFiles: ["src/lib/billing/lago-client.ts", "src/lib/billing/lago-webhooks.ts", "src/lib/billing/usage-service.ts"],
    responsibleOwner: "billing-security",
  }),
  externalService({
    providerId: "THIRD_PARTY.LIVEKIT",
    provider: "LiveKit",
    purpose: "Short-lived voice/video room access and signed call lifecycle webhooks.",
    dataSent: ["room ID", "participant identity", "scoped media grants", "voice/video media"],
    dataReceived: ["signed call lifecycle events", "room and participant state"],
    personalInformation: ["participant identity", "voice/video media"],
    credentials: ["LIVEKIT_API_KEY", "LIVEKIT_API_SECRET", "short-lived participant token"],
    credentialScope: "Server API credential signs room-scoped participant tokens; exact provider project grants are not verified.",
    allowedHosts: ["Configured LIVEKIT_URL and NEXT_PUBLIC_LIVEKIT_URL"],
    responseValidation: "LiveKit SDK verifies webhook signatures; token grants are decoded in local permission tests.",
    webhookSecurity: "Provider JWT signature verification and exact webhook route.",
    dataRetention: "Recordings are not approved; provider call metadata retention is not verified.",
    failureFallback: "Disable call creation and keep text/community journeys available.",
    sourceFiles: ["src/lib/call-token.ts", "src/lib/livekit-admin.ts", "src/app/api/livekit/webhook/route.ts"],
    responsibleOwner: "messaging-security",
  }),
  externalService({
    providerId: "THIRD_PARTY.OPENAI",
    provider: "OpenAI",
    purpose: "Optional dog-card image editing and pinned Codex pull-request review automation.",
    dataSent: ["dog-card image", "bounded edit prompt", "review prompt and repository diff in CI"],
    dataReceived: ["generated image payload", "review output"],
    personalInformation: ["user-supplied dog imagery when the optional card feature is invoked"],
    credentials: ["OPENAI_API_KEY"],
    credentialScope: "Server/CI-only API key; project, model and spend scope are not verified.",
    allowedHosts: ["api.openai.com", "pinned openai/codex-action GitHub action"],
    rateLimit: "Application request admission exists for the dog-card action; provider quota evidence is not verified.",
    costLimit: "Per-image and CI budget alarms are not verified.",
    responseValidation: "HTTP status, JSON shape and base64 image presence are checked by the application adapter.",
    failureFallback: "Optional image generation/review fails without mutating critical race, account or billing state.",
    sourceFiles: ["src/lib/dog-card-service.ts", ".github/workflows/codex-review.yml"],
    responsibleOwner: "ai-security",
  }),
  externalService({
    providerId: "THIRD_PARTY.THEDOGS",
    provider: "TheDogs",
    purpose: "Greyhound meetings, races, results, dog profiles and replay metadata ingestion.",
    dataSent: ["bounded public/provider request parameters", "identified GreyhoundIQ user agent"],
    dataReceived: ["race data", "dog profiles", "result and replay metadata"],
    allowedHosts: ["www.thedogs.com.au"],
    responseValidation: "Provider-specific parsing, source allowlists and raw sanitization are source-tested.",
    failureFallback: "Retain labelled last-known-good data and expose freshness rather than inventing records.",
    sourceFiles: ["src/lib/live/thedogs.ts", "src/lib/live/thedogs-profile.ts", "src/lib/live/thedogs-replay.ts"],
    responsibleOwner: "racing-data-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.FASTTRACK",
    provider: "FastTrack / Greyhound Racing Victoria",
    purpose: "Credentialed Victorian race-data ingestion.",
    dataSent: ["provider request parameters", "FASTTRACK_API_KEY header"],
    dataReceived: ["meetings", "races", "results and greyhound data"],
    credentials: ["FASTTRACK_API_KEY"],
    credentialScope: "Server-only provider API key; exact account grants and rotation are not verified.",
    allowedHosts: ["fasttrack.grv.org.au"],
    responseValidation: "Provider adapter validates expected shapes before normalized ingestion.",
    failureFallback: "Fail the provider sync, retain labelled stale data and use bounded operator-directed replay.",
    sourceFiles: ["src/lib/live/fasttrack.ts"],
    responsibleOwner: "racing-data-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.WATCHDOG",
    provider: "Watchdog / Greyhound Racing Victoria",
    purpose: "Public Victorian form and replay metadata ingestion.",
    dataSent: ["bounded race/form request parameters"],
    dataReceived: ["form, result and replay metadata"],
    allowedHosts: ["watchdog.grv.org.au"],
    responseValidation: "Provider parser maps only approved normalized fields.",
    failureFallback: "Provider failure is isolated to the affected data source and stale state is disclosed.",
    sourceFiles: ["src/lib/live/watchdog.ts"],
    responsibleOwner: "racing-data-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.TOPAZ",
    provider: "Topaz / Greyhound Racing Victoria",
    purpose: "Public OpenAPI-backed greyhound racing data ingestion.",
    dataSent: ["bounded API resource and query parameters"],
    dataReceived: ["meetings, races, results and dog data"],
    allowedHosts: ["topaz.grv.org.au"],
    responseValidation: "Adapter validates the expected response shape and preserves provider provenance.",
    failureFallback: "Provider failure remains isolated and last-known-good data is explicitly labelled stale.",
    sourceFiles: ["src/lib/live/topaz.ts"],
    responsibleOwner: "racing-data-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.RACING_QUEENSLAND",
    provider: "Racing Queensland",
    purpose: "Public race replay discovery and playback metadata.",
    dataSent: ["bounded meeting/race identifiers"],
    dataReceived: ["replay page and media metadata"],
    allowedHosts: ["www.racingqueensland.com.au"],
    responseValidation: "Replay URLs pass the exact provider-host allowlist and public-address pinned fetch path.",
    failureFallback: "Omit unavailable replay media without affecting race/result integrity.",
    sourceFiles: ["src/lib/live/race-replay.ts", "scripts/backfill-race-videos.ts"],
    responsibleOwner: "racing-media-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.TASRACING",
    provider: "Tasracing",
    purpose: "Public Tasmanian race replay discovery and playback metadata.",
    dataSent: ["bounded meeting/race identifiers"],
    dataReceived: ["event, race and S3-hosted replay metadata"],
    allowedHosts: ["test.tasracing.com.au", "form.tasracing.com.au", "tasracing-race-replays.s3.ap-southeast-2.amazonaws.com"],
    responseValidation: "Replay metadata and URLs pass provider-specific normalization and host checks.",
    knownSubprocessors: ["Amazon S3 ap-southeast-2 replay object host"],
    failureFallback: "Omit unavailable replay media and retain the underlying race/result record.",
    sourceFiles: ["src/lib/live/race-replay.ts", "scripts/backfill-race-videos.ts"],
    responsibleOwner: "racing-media-sre",
  }),
  externalService({
    providerId: "THIRD_PARTY.YOUTUBE",
    provider: "YouTube",
    purpose: "Allowlisted public greyhound race replay discovery and privacy-enhanced embedding.",
    dataSent: ["public replay search terms", "browser playback request"],
    dataReceived: ["public replay identifiers and media"],
    allowedHosts: ["www.youtube.com", "www.youtube-nocookie.com"],
    responseValidation: "Only normalized video IDs are accepted and embeds use the allowlisted no-cookie host.",
    dataRetention: "Provider/browser playback telemetry is not verified.",
    providerLogging: "Provider playback/request logging is not verified.",
    failureFallback: "Hide the replay when the provider or validated identifier is unavailable.",
    sourceFiles: ["src/lib/live/race-replay.ts", "scripts/backfill-race-videos.ts"],
    responsibleOwner: "racing-media-privacy",
  }),
  externalService({
    providerId: "THIRD_PARTY.VIMEO",
    provider: "Vimeo",
    purpose: "Greyhounds WA/public race replay showcase discovery and embedding.",
    dataSent: ["public showcase/video identifiers", "browser playback request"],
    dataReceived: ["public replay identifiers and media"],
    allowedHosts: ["vimeo.com", "player.vimeo.com"],
    responseValidation: "Only normalized video IDs and allowlisted Vimeo hosts are accepted.",
    dataRetention: "Provider/browser playback telemetry is not verified.",
    providerLogging: "Provider playback/request logging is not verified.",
    failureFallback: "Hide the replay when the provider or validated identifier is unavailable.",
    sourceFiles: ["src/lib/live/race-replay.ts", "scripts/backfill-race-videos.ts"],
    responsibleOwner: "racing-media-privacy",
  }),
  externalService({
    providerId: "THIRD_PARTY.GOOGLE_CLOUD",
    provider: "Google Cloud Platform",
    purpose: "Cloud Run delivery, Artifact Registry, Secret Manager, Cloud Scheduler, logging/monitoring and target Australian managed PostgreSQL infrastructure.",
    dataSent: ["container artifacts", "deployment configuration", "sanitized telemetry", "application data to approved regional services"],
    dataReceived: ["runtime responses", "deployment and health state", "metrics, logs and alerts"],
    personalInformation: ["application data stored or processed by configured production services"],
    credentials: ["GitHub OIDC workload identity", "short-lived workload identities"],
    credentialScope: "Environment-specific least-privilege service accounts; deployed IAM proof remains incomplete.",
    allowedHosts: ["Google Cloud control and regional service endpoints selected by IaC/workflows"],
    responseValidation: "Deployment workflows validate target project, region, digest and health gates.",
    dataRetention: "Service-specific AU residency and retention require deployed configuration proof.",
    failureFallback: "Freeze deployment, retain the last-known-good digest and invoke zonal/regional recovery runbooks.",
    sourceFiles: [".github/workflows/cloud-run-deploy.yml", "Dockerfile"],
    responsibleOwner: "cloud-platform-security",
  }),
  externalService({
    providerId: "THIRD_PARTY.GITHUB",
    provider: "GitHub",
    purpose: "Source control, pull requests, Actions CI/CD, Dependabot and protected release approvals.",
    dataSent: ["source and review metadata", "build/test output", "OIDC deployment claims"],
    dataReceived: ["workflow events", "dependency updates", "review and status results"],
    credentials: ["GitHub Actions token", "OIDC identity", "environment-scoped secrets"],
    credentialScope: "Workflow/job permissions are source-declared; live organization and branch protection remain unverified.",
    allowedHosts: ["github.com", "api.github.com", "pinned action sources"],
    responseValidation: "Pinned action digests and fail-closed workflow gates are source-tested.",
    dataRetention: "Repository, artifact, workflow-log and audit retention require organization policy verification.",
    failureFallback: "Freeze releases and use the retained last-known-good production artifact; do not bypass required gates.",
    sourceFiles: [".github/workflows/ci.yml", ".github/workflows/cloud-run-deploy.yml", ".github/dependabot.yml"],
    responsibleOwner: "release-engineering-security",
  }),
  externalService({
    providerId: "THIRD_PARTY.NOTIFICATION_WEBHOOK",
    provider: "Operator-configured notification webhook",
    purpose: "Optional asynchronous delivery of user notification payloads to a selected provider.",
    dataSent: ["notification ID/type/title/body/link/target", "recipient email/name"],
    dataReceived: ["HTTP delivery status"],
    personalInformation: ["recipient email/name", "notification content"],
    credentials: ["NOTIFICATION_WEBHOOK_SECRET"],
    credentialScope: "Dedicated header secret; destination provider and exact grants are not selected.",
    allowedHosts: ["Exact configured HTTPS URL; DNS is pinned to validated public addresses for the request"],
    responseValidation: "Redirects are rejected and the final HTTP status is checked.",
    webhookSecurity: "Outbound x-notification-secret header; no inbound webhook.",
    retryPolicy:
      "Bounded at-least-once attempts reuse the notification ID as the downstream idempotency key and stop after the configured cap.",
    failureFallback: "Bounded attempts persist locally and stop after the configured cap.",
    sourceFiles: [
      "src/lib/notification-service.ts",
      "src/lib/notification-webhook.ts",
      "src/lib/notification-webhook-policy.ts",
      "src/lib/public-network.ts",
      "src/lib/live/replay-network.ts",
    ],
    responsibleOwner: "notifications-privacy-security",
    verificationStatus: "Partially verified",
  }),
] as const satisfies readonly ThirdPartyContract[];

type ExternalServiceInput = Pick<
  ThirdPartyContract,
  | "providerId"
  | "provider"
  | "purpose"
  | "dataSent"
  | "dataReceived"
  | "allowedHosts"
  | "sourceFiles"
  | "responsibleOwner"
> &
  Partial<Omit<ThirdPartyContract, "providerId" | "provider" | "purpose" | "dataSent" | "dataReceived" | "allowedHosts" | "sourceFiles" | "responsibleOwner">>;

function externalService(input: ExternalServiceInput): ThirdPartyContract {
  return {
    personalInformation: [],
    credentials: ["No provider credential recorded; verify whether the source is public."],
    credentialScope: "Public-source or server credential boundary; exact provider grants are not verified.",
    credentialStorage: "Secret Manager/environment for any credential; no value is recorded in this registry.",
    credentialRotation: "Not verified or not applicable for a public source.",
    environments: ["Local/staging/production separation is required; deployed provider accounts are not verified."],
    tlsVerification: "HTTPS/TLS is required; deployed certificate and pinning evidence are not asserted.",
    requestTimeout: "Source adapter timeout must be bounded; exact provider/runtime evidence is not verified.",
    retryPolicy: "Bounded retry only for safe/idempotent reads; exact runtime budget remains provider-specific.",
    circuitBreaker: "Not verified.",
    rateLimit: "Provider quota and application admission limits are not verified.",
    costLimit: "Budget/quota protection is not verified or not applicable to the public source.",
    responseValidation: "Provider-specific response validation remains partially verified.",
    webhookSecurity: "Not applicable unless explicitly stated.",
    dataRetention: "Provider and local normalized/raw retention require approved evidence.",
    providerLogging: "Provider logging and retention are not verified.",
    knownSubprocessors: ["Not verified."],
    failureFallback: "Fail the optional provider operation without granting local authority or corrupting critical state.",
    incidentContact: "Not recorded.",
    evidence: [],
    verificationStatus: "Partially verified",
    ...input,
  };
}
