export const ARCHITECTURE_EVIDENCE_SCOPE =
  "Source-static selected design only; deployment, runtime, failover, load, IAM, alert delivery and production validation remain unverified.";

export const ARCHITECTURE_INVENTORY_EVIDENCE = [
  "src/components/design-lab-architecture-inventory.ts",
  "src/components/design-lab-architecture-lab.tsx",
  "src/components/design-lab-architecture-inventory.test.ts",
  "docs/architecture/greyhoundiq-australia-production-architecture.md",
  "docs/architecture/greyhoundiq-production-architecture-report.html",
] as const;

export const ARCHITECTURE_PRIMARY_PATH = [
  "Australian web clients (native post-MVP)",
  "Global ALB + Armor + cache allowlist + ESPv2",
  "Sydney + Melbourne app, worker and realtime cells",
  "AlloyDB + Cloud Storage + Pub/Sub/Redis; LiveKit on separate AU compute",
] as const;

export const ARCHITECTURE_COMPONENT_FIELD_REQUIREMENTS = [
  ["security.architecture-component-record.component.public-or-private-exposure", "publicOrPrivateExposure"],
  ["security.architecture-component-record.component.authentication-method", "authenticationMethod"],
  ["security.architecture-component-record.component.network-restrictions", "networkRestrictions"],
  ["security.architecture-component-record.component.credential-used", "credentialUsed"],
  ["security.architecture-component-record.component.data-processed", "dataProcessed"],
  ["security.architecture-component-record.component.data-stored", "dataStored"],
  ["security.architecture-component-record.component.encryption", "encryption"],
  ["security.architecture-component-record.component.logging", "logging"],
  ["security.architecture-component-record.component.retention", "retention"],
  ["security.architecture-component-record.component.responsible-owner", "responsibleOwner"],
  ["security.architecture-component-record.component.failure-impact", "failureImpact"],
  ["security.architecture-component-record.component.recovery-method", "recoveryMethod"],
] as const;

export type ArchitectureEvidenceState =
  | "current-source"
  | "selected-target"
  | "conditional"
  | "provider-undecided";

export type ArchitectureComponent = {
  id: string;
  name: string;
  layer: string;
  evidenceState: ArchitectureEvidenceState;
  regions: readonly string[];
  publicOrPrivateExposure: string;
  authenticationMethod: string;
  networkRestrictions: string;
  credentialUsed: string;
  dataProcessed: readonly string[];
  dataStored: string;
  encryption: string;
  logging: string;
  retention: string;
  responsibleOwner: string;
  failureImpact: string;
  recoveryMethod: string;
  evidence: readonly string[];
};

const PLAN = "docs/architecture/greyhoundiq-australia-production-architecture.md";
const REPORT =
  "docs/architecture/greyhoundiq-production-architecture-report.html";

export const ARCHITECTURE_COMPONENTS: readonly ArchitectureComponent[] = [
  {
    id: "domain-control-plane",
    name: "Registrar, Cloud DNS and certificates",
    layer: "Edge control plane",
    evidenceState: "selected-target",
    regions: ["Global control plane"],
    publicOrPrivateExposure: "Public authoritative DNS; management is private.",
    authenticationMethod: "Workforce identity, phishing-resistant MFA and reviewed changes are selected; deployment is unverified.",
    networkRestrictions: "Only authoritative DNS and managed TLS are public; registrar and zone administration have no application path.",
    credentialUsed: "Short-lived workforce identity; no credential value is stored in this registry.",
    dataProcessed: ["Domain names", "DNS records", "certificate metadata"],
    dataStored: "Versioned zone and certificate configuration; retention is not yet approved.",
    encryption: "DNSSEC and managed TLS are selected; enforcement evidence is unverified.",
    logging: "Zone, registrar and certificate changes must enter the security audit sink.",
    retention: "Unverified pending the approved audit-log retention schedule.",
    responsibleOwner: "Platform and Security",
    failureImpact: "A bad zone, registrar change or certificate can remove the whole public service.",
    recoveryMethod: "Restore a reviewed zone version, follow the DNSSEC order and rehearse certificate rollback.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "edge-security-stack",
    name: "Global ALB, Cloud Armor and allowlisted CDN",
    layer: "Public edge",
    evidenceState: "selected-target",
    regions: ["Nearest active Google edge", "Sydney origin", "Melbourne origin"],
    publicOrPrivateExposure: "Only selected public web, API, asset and exact webhook routes are exposed.",
    authenticationMethod: "TLS at the edge; Armor admission and gateway/application identity checks follow by route.",
    networkRestrictions: "AU consumer policy, narrow provider exceptions and load-balancer-only origin ingress are selected.",
    credentialUsed: "Google-managed service identity and certificates; live bindings are unverified.",
    dataProcessed: ["HTTP metadata", "public cacheable responses", "security-policy signals"],
    dataStored: "Public allowlisted cache objects only; private and authenticated responses must bypass.",
    encryption: "TLS in transit; public CDN residency can be global and is explicitly bounded.",
    logging: "Edge action, cache status, origin fill, rate limit and regional routing signals are required.",
    retention: "Unverified pending the telemetry classification and retention schedule.",
    responsibleOwner: "Platform SRE and Security",
    failureImpact: "Misrouting blocks traffic; false positives block cohorts; unsafe caching can leak data.",
    recoveryMethod: "Known-good URL map, policy rollback, cache purge/version and tested Cloud Run service-health failover; outlier detection alone is not treated as complete regional ejection.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "espv2-gateway",
    name: "Cloud Endpoints ESPv2 gateway cells",
    layer: "API policy",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Reachable only through the protected load-balancer API routes.",
    authenticationMethod: "Coarse token or API-key validation; application authorization remains authoritative.",
    networkRestrictions: "Declared OpenAPI routes only; gateway service identity invokes the API backend.",
    credentialUsed: "Workload service identity with audience-bound tokens; live IAM is unverified.",
    dataProcessed: ["API headers", "bounded API bodies", "quota and route metadata"],
    dataStored: "Versioned service configuration and telemetry, not business records.",
    encryption: "TLS from client edge and encrypted provider-managed backend transport are selected.",
    logging: "Operation, auth outcome, quota outcome, latency and safe correlation fields.",
    retention: "Unverified pending gateway log classification.",
    responsibleOwner: "API and Platform",
    failureImpact: "A stale or saturated gateway blocks API traffic or admits excess work.",
    recoveryMethod: "Canary immutable config, stop traffic to the bad revision and restore the prior config.",
    evidence: [PLAN, REPORT, "openapi.json"],
  },
  {
    id: "cloud-run-app-cells",
    name: "Stateless Cloud Run application cells",
    layer: "Application compute",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Protected web/API origin; the direct run.app path must be blocked before production.",
    authenticationMethod: "WorkOS session or supported API identity, followed by server authorization and RLS.",
    networkRestrictions: "Internal-and-load-balancing ingress and private data access are selected; live proof is absent.",
    credentialUsed: "Cloud Run workload identity and secret references; no permanent cloud key is selected.",
    dataProcessed: ["User requests", "race data", "account and marketplace data", "provider results"],
    dataStored: "No durable instance state; durable state is external.",
    encryption: "TLS at ingress and encrypted private/provider connections are selected.",
    logging: "Request, trace, region, revision, operation, outcome and duration with redaction.",
    retention: "Ephemeral instance state only; log retention remains unverified.",
    responsibleOwner: "Application and SRE",
    failureImpact: "Slow, leaking or exhausted cells increase errors and can pressure the database.",
    recoveryMethod: "Bounded autoscale, priority shedding, immutable rollback and tested service-health failover using readiness probes plus a warm instance in each region; unknown health and rapid-crash edge cases remain explicit tests.",
    evidence: [PLAN, REPORT, "src/app"],
  },
  {
    id: "cloud-run-worker-cells",
    name: "Independently capped Cloud Run workers",
    layer: "Asynchronous compute",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne where supported"],
    publicOrPrivateExposure: "Private service-identity invocation only.",
    authenticationMethod: "Queue or service identity plus operation allowlist.",
    networkRestrictions: "Separate instance and concurrency caps prevent background work starving requests.",
    credentialUsed: "Dedicated least-privilege workload identities and secret references.",
    dataProcessed: ["Outbox events", "notifications", "media jobs", "reports", "provider calls"],
    dataStored: "No durable local state; job state and outcomes persist externally.",
    encryption: "Encrypted queue, database and provider transport are selected.",
    logging: "Event ID, queue age, attempt, idempotency outcome, duration and dead-letter state.",
    retention: "Job and dead-letter retention is unverified per job class.",
    responsibleOwner: "Worker owners and SRE",
    failureImpact: "Backlogs grow; unchecked concurrency can overwhelm the database or providers.",
    recoveryMethod: "Pause dispatch, scale inside downstream budgets, rollback, replay only after approval.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "private-service-network",
    name: "Private service network and controlled egress",
    layer: "Network trust boundary",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Private data-plane boundary; no database, cache, queue or dashboard public path.",
    authenticationMethod: "Workload identity at service boundaries; network location alone grants nothing.",
    networkRestrictions: "Private service access, explicit egress allowlists and metadata/SSRF controls are selected.",
    credentialUsed: "Short-lived workload identity; permanent service-account keys are prohibited by design.",
    dataProcessed: ["East-west application traffic", "database traffic", "controlled provider egress"],
    dataStored: "Network policy and flow/audit metadata only.",
    encryption: "Encrypted service transport; mTLS only where a measured boundary requires it.",
    logging: "Denied access, egress decisions and identity-aware service calls are required.",
    retention: "Unverified pending the network-log schedule.",
    responsibleOwner: "Platform and Security",
    failureImpact: "Over-broad access enables bypass or exfiltration; over-tight access causes dependency outage.",
    recoveryMethod: "Reviewed policy rollback and isolated break-glass access with an audit trail.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "alloydb-sydney",
    name: "AlloyDB Sydney HA writer",
    layer: "Core data",
    evidenceState: "selected-target",
    regions: ["Sydney"],
    publicOrPrivateExposure: "Private database endpoint only.",
    authenticationMethod: "Dedicated runtime, migration and operator roles plus PostgreSQL RLS.",
    networkRestrictions: "Application/private service access only; no public database route.",
    credentialUsed: "Secret-managed database identity or approved workload integration; compatibility is unverified.",
    dataProcessed: ["Core relational user, race, billing, community and audit transactions"],
    dataStored: "Authoritative OLTP data, outbox rows and backup/PITR history.",
    encryption: "Provider-managed encryption at rest and TLS in transit are selected.",
    logging: "Connections, locks, waits, query class, failover, backup and safe operation identifiers.",
    retention: "Unverified pending data-class retention and restore policy approval.",
    responsibleOwner: "DBRE and Application",
    failureImpact: "Writes pause or fail; saturation can remove every critical journey.",
    recoveryMethod: "Regional HA failover, read-only containment, isolated PITR restore or Melbourne promotion runbook.",
    evidence: [PLAN, REPORT, "prisma/schema.prisma"],
  },
  {
    id: "alloydb-melbourne",
    name: "AlloyDB Melbourne secondary and read capacity",
    layer: "Core data recovery",
    evidenceState: "selected-target",
    regions: ["Melbourne"],
    publicOrPrivateExposure: "Private replica/secondary endpoint only.",
    authenticationMethod: "Replica-safe read role; promotion requires controlled operator authority.",
    networkRestrictions: "Approved app cells and controlled DBRE operations only.",
    credentialUsed: "Secret-managed database identity; live bindings are unverified.",
    dataProcessed: ["Asynchronous replication", "replica-safe reads", "recovery validation"],
    dataStored: "Asynchronous copy of selected Sydney database state.",
    encryption: "Encrypted replication and storage are selected.",
    logging: "Replica lag, recovery point, read consistency, promotion and reconnect events.",
    retention: "Matches the approved database recovery policy; currently unverified.",
    responsibleOwner: "DBRE and Incident Commander",
    failureImpact: "Lag serves stale reads; premature promotion risks data loss or split-brain recovery errors.",
    recoveryMethod: "Verify lag, approve one-writer promotion, update revisions in waves, validate and plan failback.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "database-pooler",
    name: "Managed database pooler or proxy",
    layer: "Connection admission",
    evidenceState: "conditional",
    regions: ["Sydney", "Melbourne recovery path"],
    publicOrPrivateExposure: "Private application-to-database path only.",
    authenticationMethod: "Application database identity; no end-user direct access.",
    networkRestrictions: "Only approved app/worker services and operator reserve may consume connections.",
    credentialUsed: "Database identity from Secret Manager; session compatibility must be rehearsed.",
    dataProcessed: ["PostgreSQL sessions", "transactions", "transaction-local RLS context"],
    dataStored: "Connection/session state only; no authoritative business storage.",
    encryption: "TLS on application and database legs is selected.",
    logging: "Pool use, wait time, reset, reconnect and exhaustion without query values.",
    retention: "Operational telemetry only; unverified.",
    responsibleOwner: "DBRE",
    failureImpact: "A slow or incompatible pool can hide saturation or break transaction-local security context.",
    recoveryMethod: "Reject excess admission and use only a rehearsed bypass/rollback configuration.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "regional-cache",
    name: "Per-region Standard-tier Memorystore",
    layer: "Ephemeral realtime distribution",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Private application path only.",
    authenticationMethod: "Dedicated gateway workload identity plus managed cache authentication on a private regional network.",
    networkRestrictions: "Each regional realtime gateway reaches only its own application Redis; LiveKit uses a separate Redis boundary.",
    credentialUsed: "Secret-managed cache authentication where required; no browser credential.",
    dataProcessed: ["Ephemeral realtime fan-out", "short-lived presence", "non-authoritative delivery hints"],
    dataStored: "TTL-bounded disposable values; AlloyDB and durable event replay remain authoritative.",
    encryption: "Encrypted private transport and provider-managed at-rest encryption are selected.",
    logging: "Hit ratio, latency, eviction, hot keys, memory and connection saturation.",
    retention: "Seconds to minutes with jitter; exact TTLs require route review.",
    responsibleOwner: "Realtime Platform and SRE",
    failureImpact: "Regional fan-out pauses and connections drop; asynchronous cache failover may lose acknowledged ephemeral values.",
    recoveryMethod: "Reconnect with bounded jitter, rebuild ephemeral state and recover durable missed events by cursor; Standard tier is cross-zone only and is never presented as cross-region DR.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "pubsub-outbox",
    name: "Transactional outbox and AU-restricted Pub/Sub",
    layer: "Durable asynchronous intent",
    evidenceState: "selected-target",
    regions: ["Sydney or Melbourne per message entry under an AU persistence allowlist"],
    publicOrPrivateExposure: "Private publisher/subscriber paths only.",
    authenticationMethod: "Publisher and subscriber workload identities with topic/subscription least privilege.",
    networkRestrictions: "Message persistence is restricted to Sydney/Melbourne with regional endpoints when in-transit enforcement is enabled; this policy does not replicate every message into both regions.",
    credentialUsed: "Short-lived workload identity; no embedded queue key.",
    dataProcessed: ["Versioned events", "idempotency keys", "causal IDs", "bounded job payloads"],
    dataStored: "Outbox rows, message backlog and dead-letter messages within approved retention.",
    encryption: "Provider encryption and authenticated transport are selected.",
    logging: "Publish/dispatch rate, oldest age, retry, duplicate and dead-letter state.",
    retention: "Unverified per event class and privacy schedule.",
    responsibleOwner: "Application and Worker owners",
    failureImpact: "Duplicates, out-of-order delivery or backlog delay side effects; unbounded workers pressure dependencies.",
    recoveryMethod: "Idempotent consumers, bounded retry, DLQ quarantine, outbox replay and an explicit publisher/topology failover runbook; regional availability is not inferred from the residency allowlist.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "cloud-tasks-sydney",
    name: "Bounded Cloud Tasks queues",
    layer: "Regional scheduling",
    evidenceState: "selected-target",
    regions: ["Sydney"],
    publicOrPrivateExposure: "Private service-identity dispatch only.",
    authenticationMethod: "Queue service identity with exact worker audience.",
    networkRestrictions: "Only reconstructable, noncritical regional jobs; not the sole critical DR path.",
    credentialUsed: "Short-lived Google service identity.",
    dataProcessed: ["Scheduled or throttled job metadata", "idempotency keys"],
    dataStored: "Bounded regional queue state for reconstructable work.",
    encryption: "Provider-managed encryption in transit and at rest.",
    logging: "Queue age, dispatch, attempts, latency and terminal outcome.",
    retention: "Unverified per job class.",
    responsibleOwner: "Worker owners",
    failureImpact: "Sydney outage pauses dispatch; excessive concurrency can pressure downstream services.",
    recoveryMethod: "Disable or reconstruct work from its durable source; critical intent stays in the outbox/Pub/Sub path.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "au-object-storage",
    name: "Sydney + Melbourne AU dual-region object storage",
    layer: "Object data",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Private by default; signed private access and explicitly public versioned objects only.",
    authenticationMethod: "Workload identity, uniform bucket access and short-lived signed access.",
    networkRestrictions: "No public bucket origin; protected CDN for approved public objects and direct quarantine upload only.",
    credentialUsed: "Workload identity and short-lived signed capability; no static storage key.",
    dataProcessed: ["Uploads", "quarantine objects", "public media", "private exports"],
    dataStored: "Versioned objects, quarantine state and asynchronously replicated recovery copies in Australia.",
    encryption: "Provider-managed at-rest encryption and HTTPS signed transfers are selected.",
    logging: "Sign, upload, scan, promote, download, delete and access-denial audit events.",
    retention: "Unverified by object class; lifecycle, soft-delete and incomplete-upload policies are required.",
    responsibleOwner: "Media, Platform and Security",
    failureImpact: "Access failures break media/exports; bad IAM can leak objects; a destructive regional event can expose the selected replication RPO.",
    recoveryMethod: "Version restore, signed-access revocation, quarantine isolation and controlled event dedupe/replay; an ADR selects default replication or Turbo based on measured RPO and cost.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "application-search",
    name: "Bounded application search and read models",
    layer: "Application capability",
    evidenceState: "current-source",
    regions: ["Application/database boundary"],
    publicOrPrivateExposure: "Only through reviewed public or authenticated application routes.",
    authenticationMethod: "Route-specific session and object/tenant authorization.",
    networkRestrictions: "No separate public search service is selected; calls remain inside the application data boundary.",
    credentialUsed: "Application database identity.",
    dataProcessed: ["Bounded search terms", "public race data", "authorized account/community data"],
    dataStored: "PostgreSQL indexes/materialized read models; no separate search cluster is selected.",
    encryption: "Application/database encrypted transport and encrypted storage are selected.",
    logging: "Operation, complexity, duration, rows/bytes and quota outcome without raw sensitive queries.",
    retention: "Follows source data retention; query-log retention is unverified.",
    responsibleOwner: "Application and DBRE",
    failureImpact: "Expensive or cache-busting search can exhaust database and application concurrency.",
    recoveryMethod: "Complexity/row/time caps, cached public models, route shedding and deferred separate search only after measurement.",
    evidence: [PLAN, REPORT, "src/app/api/discover/route.ts"],
  },
  {
    id: "observability-desk",
    name: "Observability and incident-control desk",
    layer: "Operations",
    evidenceState: "selected-target",
    regions: ["Australian log buckets", "Global metrics/control plane"],
    publicOrPrivateExposure: "Private operator dashboards and audit sinks only.",
    authenticationMethod: "Workforce identity, least privilege and audited emergency access.",
    networkRestrictions: "No public dashboard; sensitive logs remain in reviewed Australian sinks where supported.",
    credentialUsed: "Short-lived workforce/workload identity and paging integration references.",
    dataProcessed: ["Metrics", "structured logs", "traces", "audit events", "synthetic results"],
    dataStored: "Regional logs/audit records plus provider-managed global metrics metadata.",
    encryption: "Encrypted ingestion and at-rest provider storage are selected.",
    logging: "The desk records changes, alert delivery, incident actions and emergency-control outcomes.",
    retention: "Unverified by telemetry class; security evidence requires tamper-resistant retention.",
    responsibleOwner: "SRE and Security",
    failureImpact: "Operators become blind, paging can fail, or excessive/sensitive logging creates cost/privacy harm.",
    recoveryMethod: "External synthetics, dead-man checks, secondary contact channel and manual incident checklist.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "secret-manager-kms",
    name: "Secret Manager and key management",
    layer: "Identity and secrets",
    evidenceState: "selected-target",
    regions: ["Sydney and Melbourne user-managed payload replicas; global service semantics reviewed separately"],
    publicOrPrivateExposure: "Private control-plane access only.",
    authenticationMethod: "Least-privilege workload and workforce identity.",
    networkRestrictions: "Approved services and just-in-time operators only; no browser-delivered secret.",
    credentialUsed: "Short-lived identity retrieves versioned secrets; the registry never contains values.",
    dataProcessed: ["Provider credentials", "database secret metadata", "signing/key references"],
    dataStored: "Synchronously written user-managed Australian payload replicas for selected secrets; global accessibility and metadata implications require review.",
    encryption: "KMS/provider encryption with selected rotation and emergency revocation.",
    logging: "Secret access, denial, version creation, rotation and privileged changes.",
    retention: "Overlapping versions only for the approved rollback window; schedule unverified.",
    responsibleOwner: "Security and Platform",
    failureImpact: "New instances or provider calls fail; version creation can fail when a configured replica region is unavailable; compromise can cross multiple trust boundaries.",
    recoveryMethod: "Use runtime-cached or overlapping known-good versions, revoke/rotate, audit consumers and follow the approved global-versus-regional secret topology runbook.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "delivery-control-plane",
    name: "GitHub, CI, Artifact Registry and deployment controls",
    layer: "Software supply chain",
    evidenceState: "selected-target",
    regions: ["External source control", "Australian artifact/runtime targets"],
    publicOrPrivateExposure: "Private repositories, workflows, artifact and protected deployment environment.",
    authenticationMethod: "Human MFA plus GitHub OIDC workload identity federation and protected approval.",
    networkRestrictions: "Only approved workflows can publish; only the protected environment can promote the exact digest.",
    credentialUsed: "Short-lived OIDC federation; permanent cloud deployment keys are prohibited.",
    dataProcessed: ["Source", "SBOM", "test evidence", "image digest", "deployment metadata"],
    dataStored: "Versioned source, CI records, attestations and immutable container artifacts.",
    encryption: "Provider encryption and signed/provenance-bound artifact transport are selected.",
    logging: "Review, workflow, artifact, approval, IAM and deployment audit events.",
    retention: "Unverified pending software-supply-chain evidence policy.",
    responsibleOwner: "Release Engineering and Security",
    failureImpact: "Outage stops deployment; compromise can ship an unauthorized candidate.",
    recoveryMethod: "Freeze changes, revoke federation, retain known-good signed image and require fresh protected approval.",
    evidence: [PLAN, REPORT, ".github/workflows/ci.yml", ".github/workflows/cloud-run-deploy.yml"],
  },
  {
    id: "workos-identity",
    name: "WorkOS identity boundary",
    layer: "External identity provider",
    evidenceState: "current-source",
    regions: ["External provider; residency exception requires approval"],
    publicOrPrivateExposure: "Public authentication redirects/callbacks; private provider management.",
    authenticationMethod: "OIDC/session exchange with server-side callback and local authorization.",
    networkRestrictions: "Exact callbacks and provider domains only; application fails closed for risky new auth actions.",
    credentialUsed: "Secret-managed client credentials and provider signing material.",
    dataProcessed: ["Identity assertions", "session metadata", "account recovery signals"],
    dataStored: "Provider identity records plus local session/account linkage; exact residency and retention are unverified.",
    encryption: "HTTPS/OIDC transport and provider at-rest controls.",
    logging: "Authentication outcome, provider latency, safe subject reference and recovery events.",
    retention: "Unverified pending identity/privacy review.",
    responsibleOwner: "Identity and Security",
    failureImpact: "New login/recovery fails; existing-session behavior depends on tested token semantics.",
    recoveryMethod: "Keep proven existing sessions only, fail closed for high-risk operations and engage provider recovery.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "payment-providers",
    name: "Stripe and Lago payment boundary",
    layer: "External payment providers",
    evidenceState: "current-source",
    regions: ["External providers; cross-border exception requires approval"],
    publicOrPrivateExposure: "Public checkout/return and exact signed webhook routes.",
    authenticationMethod: "Server-created checkout, verified webhook signatures and server-side entitlement reconciliation.",
    networkRestrictions: "Exact methods/routes, CDN bypass, replay guard and provider egress allowlist.",
    credentialUsed: "Secret-managed provider credentials and webhook signing secrets.",
    dataProcessed: ["Customer/provider IDs", "plan and invoice state", "webhook events"],
    dataStored: "Provider-held card data; local references, invoices and entitlement state only.",
    encryption: "HTTPS and provider at-rest controls; payment-card data remains with the provider.",
    logging: "Provider event ID, signature/replay outcome, reconciliation and safe billing references.",
    retention: "Unverified pending financial and privacy retention approval.",
    responsibleOwner: "Billing and Security",
    failureImpact: "Checkout or reconciliation delays; incorrect callbacks must never grant entitlement.",
    recoveryMethod: "Queue reconciliation, dedupe events, retain authoritative provider state and disable new checkout if integrity is uncertain.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "email-provider",
    name: "Email provider boundary",
    layer: "External notification provider",
    evidenceState: "provider-undecided",
    regions: ["Provider and residency unverified"],
    publicOrPrivateExposure: "Worker egress only; inbound user links return through reviewed application routes.",
    authenticationMethod: "Provider API identity and signed callbacks if enabled.",
    networkRestrictions: "Notification worker bulkhead, destination/domain allowlist and bounded dispatch.",
    credentialUsed: "Secret-managed provider credential after selection.",
    dataProcessed: ["Email address", "template identifier", "short-lived action link"],
    dataStored: "Provider delivery metadata; exact storage and retention are unverified.",
    encryption: "HTTPS API transport; provider at-rest and message-transport posture require review.",
    logging: "Template ID, provider message ID, outcome and latency; no body or token.",
    retention: "Unverified pending provider selection and privacy review.",
    responsibleOwner: "Notifications and Privacy",
    failureImpact: "Recovery/notification delays; synchronous coupling could harm signup if not queued.",
    recoveryMethod: "Queue with bounded retry, open the circuit, delay noncritical mail and use approved manual recovery for critical cases.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "livekit-calls",
    name: "Dedicated Australian LiveKit SFU cluster",
    layer: "Self-hosted voice/video media plane",
    evidenceState: "selected-target",
    regions: ["Australian dedicated compute; exact node and failure-domain placement unverified"],
    publicOrPrivateExposure: "Public media plane after application-authorized token issuance; webhook is exact and signed.",
    authenticationMethod: "Short-lived room token issued only after membership/block checks.",
    networkRestrictions: "Dedicated VM or compatible Kubernetes compute with required signalling, ICE/TCP, TURN/TLS and public UDP media paths; never Cloud Run. LiveKit Redis is private and isolated from application Redis.",
    credentialUsed: "Secret-managed API credential and short-lived participant token.",
    dataProcessed: ["Room/participant metadata", "voice/video media", "call lifecycle events"],
    dataStored: "Authoritative call metadata stays in AlloyDB; cluster routing is ephemeral in private HA Redis and recordings remain disabled unless separately approved.",
    encryption: "Trusted TLS for signalling/TURN plus encrypted media; exact cipher, certificate and recording controls require verification.",
    logging: "Room/token issuance, SFU node, join latency, bandwidth, packet loss, TURN use, drain/failure and webhook outcome without media content.",
    retention: "Unverified; recordings are disabled unless an approved retention flow exists.",
    responsibleOwner: "Messaging and Security",
    failureImpact: "A node loss disconnects its rooms because one room fits on one SFU; failure must not affect core app/database correctness.",
    recoveryMethod: "Drain nodes before maintenance, retain one tested spare of measured capacity, reconnect clients to a healthy node, disable call creation if capacity is unsafe and keep text/community paths available.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "analytics-sink",
    name: "Queued analytics sink",
    layer: "Optional external processing",
    evidenceState: "provider-undecided",
    regions: ["Provider and residency unverified"],
    publicOrPrivateExposure: "Worker egress only; no browser credential or critical-path dependency.",
    authenticationMethod: "Dedicated low-privilege provider identity after selection.",
    networkRestrictions: "Allowlisted event schema, queue bulkhead and emergency disable switch.",
    credentialUsed: "Secret-managed provider credential after selection.",
    dataProcessed: ["Minimized product events", "safe actor class", "operation outcome"],
    dataStored: "Provider analytics events only after data-minimization approval.",
    encryption: "HTTPS and provider at-rest controls require verification.",
    logging: "Publish/drop outcome, queue age, schema version and provider latency.",
    retention: "Unverified pending provider and privacy selection.",
    responsibleOwner: "Product Analytics and Privacy",
    failureImpact: "Insights are delayed; analytics must never block a user transaction.",
    recoveryMethod: "Drop or backlog inside a hard cap, disable the sink and preserve critical queues.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "ai-provider",
    name: "AI provider adapter boundary",
    layer: "Optional external processing",
    evidenceState: "provider-undecided",
    regions: ["Provider and residency unverified"],
    publicOrPrivateExposure: "Authenticated application/worker path only; no direct browser provider key.",
    authenticationMethod: "Server-side entitlement, quota, tool allowlist and dedicated provider identity.",
    networkRestrictions: "Allowlisted models/tools, bounded concurrency/tokens/cost and emergency kill switch.",
    credentialUsed: "Secret-managed provider credential after selection.",
    dataProcessed: ["Minimized prompt context", "model output", "tool invocation metadata"],
    dataStored: "No provider retention assumption is approved; exact policy is unverified.",
    encryption: "HTTPS and provider at-rest controls require verification.",
    logging: "Safe operation, model, token/cost budget, latency and policy outcome without prompt content.",
    retention: "Unverified; sensitive context is prohibited until approved.",
    responsibleOwner: "AI, Security and Privacy",
    failureImpact: "Optional generation fails, leaks context or creates unbounded cost if admission is weak.",
    recoveryMethod: "Disable AI, open circuit, cancel queued work and retain all critical journeys.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "racing-providers",
    name: "FastTrack and TheDogs racing providers",
    layer: "External data ingestion",
    evidenceState: "current-source",
    regions: ["External provider origins; exact quotas/regions unverified"],
    publicOrPrivateExposure: "Scheduled worker egress and exact reviewed callback paths only.",
    authenticationMethod: "Provider-specific server credential or public-source policy plus provenance validation.",
    networkRestrictions: "Allowlisted origins, bounded fetch, response-size limits and isolated ingestion workers.",
    credentialUsed: "Secret-managed provider credential where required.",
    dataProcessed: ["Race meetings", "dogs", "results", "replay/source metadata"],
    dataStored: "Validated provider records with source/provenance and bounded raw archive policy.",
    encryption: "HTTPS where supported and encrypted local/Australian storage.",
    logging: "Provider, operation, status, bytes, duration, validation and freshness without credentials.",
    retention: "Unverified by raw/archive/normalized class.",
    responsibleOwner: "Racing Data and SRE",
    failureImpact: "Race data becomes stale or wrong; retries can multiply provider and database pressure.",
    recoveryMethod: "Circuit, last-known-good labelled stale data, bounded retry and audited backfill.",
    evidence: [PLAN, REPORT],
  },
  {
    id: "application-realtime",
    name: "Australian application realtime gateways",
    layer: "Durable-event delivery and WebSocket fan-out",
    evidenceState: "selected-target",
    regions: ["Sydney", "Melbourne"],
    publicOrPrivateExposure: "Authenticated WSS through the protected load balancer; publisher, Pub/Sub, Redis and replay paths remain private.",
    authenticationMethod: "WorkOS session plus server-side conversation/object authorization, short-lived connection grants and cursor ownership checks.",
    networkRestrictions: "Dedicated Cloud Run WebSocket gateways use regional Pub/Sub bridges and separate regional application Redis; direct origins and LiveKit data channels are prohibited for durable business events.",
    credentialUsed: "Gateway workload identities and short-lived client connection grants; no Pub/Sub or Redis credential enters the browser.",
    dataProcessed: ["Versioned outbox events", "membership grants", "ephemeral fan-out", "replay cursors"],
    dataStored: "AlloyDB stores authoritative events/cursors; Pub/Sub stores bounded delivery backlog and Redis stores disposable regional fan-out state.",
    encryption: "HTTPS/WSS at the edge and authenticated private service transport are selected.",
    logging: "Authorization, region, gateway revision, cursor, queue age, duplicate outcome, Redis loss and reconnect signals without message content.",
    retention: "Durable event and DLQ retention require approval; Redis state is TTL-bounded and disposable.",
    responsibleOwner: "Realtime Platform, Application and SRE",
    failureImpact: "Events are delayed or connections drop; durable messages must remain recoverable without corrupting core writes.",
    recoveryMethod: "Clients reconnect with bounded jitter and a cursor, gateways replay from the application API/outbox, and overload controls shed presence before durable delivery.",
    evidence: [PLAN, REPORT],
  },
] as const;

export type ArchitectureInfrastructureSurface = {
  id: string;
  requirementId: string;
  label: string;
  componentIds: readonly string[];
  disposition: ArchitectureEvidenceState;
  note: string;
  evidence: readonly string[];
};

function surface(
  id: string,
  label: string,
  componentIds: readonly string[],
  disposition: ArchitectureEvidenceState,
  note: string,
): ArchitectureInfrastructureSurface {
  return {
    id,
    requirementId: `security.architecture-infrastructure-surface.${id}`,
    label,
    componentIds,
    disposition,
    note,
    evidence: [PLAN, REPORT],
  };
}

export const ARCHITECTURE_INFRASTRUCTURE_SURFACES = [
  surface("dns", "DNS", ["domain-control-plane"], "selected-target", "Cloud DNS and DNSSEC target."),
  surface("domains", "Domains", ["domain-control-plane"], "selected-target", "Registrar, subdomain and certificate ownership."),
  surface("cdn", "CDN", ["edge-security-stack"], "selected-target", "Allowlisted public caching only."),
  surface("waf", "WAF", ["edge-security-stack"], "selected-target", "Cloud Armor edge and backend policies."),
  surface("load-balancer", "Load balancer", ["edge-security-stack"], "selected-target", "Global external ALB to two AU cells."),
  surface("reverse-proxy", "Reverse proxies", ["edge-security-stack", "espv2-gateway"], "selected-target", "ALB and ESPv2 own distinct routing/policy boundaries."),
  surface("application-servers", "Application servers", ["cloud-run-app-cells"], "selected-target", "Stateless modular-monolith cells."),
  surface("serverless", "Serverless", ["cloud-run-app-cells", "cloud-run-worker-cells"], "selected-target", "Managed Cloud Run services; function-per-route is not selected."),
  surface("containers", "Containers", ["cloud-run-app-cells", "cloud-run-worker-cells", "delivery-control-plane"], "selected-target", "One immutable signed digest across AU cells."),
  surface("internal-services", "Internal services", ["espv2-gateway", "cloud-run-worker-cells"], "selected-target", "Gateway and worker boundaries use service identity."),
  surface("network-boundaries", "Network boundaries", ["private-service-network"], "selected-target", "Public edge separated from the private data plane."),
  surface("subnets", "Subnets", ["private-service-network"], "selected-target", "No public data subnet; managed/private service connectivity is the target."),
  surface("database-hosts", "Database hosts", ["alloydb-sydney"], "selected-target", "Private Sydney HA writer."),
  surface("replicas", "Read replicas", ["alloydb-melbourne"], "selected-target", "Replica-safe reads and controlled DR promotion."),
  surface("poolers", "Connection poolers", ["database-pooler"], "conditional", "Selected only after Prisma/RLS/session compatibility proof."),
  surface("caches", "Caches", ["edge-security-stack", "regional-cache"], "selected-target", "CDN handles approved public objects; per-region application Redis handles disposable realtime fan-out only."),
  surface("queues", "Queues", ["pubsub-outbox", "cloud-tasks-sydney"], "selected-target", "Critical AU intent and bounded regional scheduling."),
  surface("object-storage", "Object storage", ["au-object-storage"], "selected-target", "Australian Cloud Storage is the sole final object-store target; Supabase remains replacement inventory, not an accepted production component."),
  surface("search", "Search", ["application-search"], "current-source", "No separate search service until measurement justifies it."),
  surface("monitoring", "Monitoring", ["observability-desk"], "selected-target", "RED/USE/SLO/security views and independent synthetics."),
  surface("logs", "Log stores", ["observability-desk"], "selected-target", "Australian sensitive-log sinks; global metadata is reviewed separately."),
  surface("secrets", "Secrets manager", ["secret-manager-kms"], "selected-target", "User-managed AU replicas for selected secrets."),
  surface("cicd", "CI/CD", ["delivery-control-plane"], "selected-target", "OIDC, provenance, immutable digest and protected approval."),
  surface("source-control", "Source control", ["delivery-control-plane"], "selected-target", "Private reviewed repository and protected branches."),
  surface("backups", "Backups", ["alloydb-sydney", "alloydb-melbourne", "au-object-storage"], "selected-target", "PITR and isolated restore remain unproven."),
  surface("authentication-provider", "Authentication provider", ["workos-identity"], "current-source", "WorkOS remains an explicit external boundary."),
  surface("payment-provider", "Payment provider", ["payment-providers"], "current-source", "Stripe/Lago boundary; card data stays provider-held."),
  surface("email-provider", "Email provider", ["email-provider"], "provider-undecided", "Provider, quotas, residency and recovery are launch inputs."),
  surface("messaging-provider", "Messaging and calls", ["livekit-calls", "application-realtime"], "selected-target", "Durable application realtime and LiveKit media remain separate Australian boundaries with separate Redis services."),
  surface("analytics-provider", "Analytics provider", ["analytics-sink"], "provider-undecided", "Optional queued sink; never a critical-path dependency."),
  surface("ai-provider", "AI provider", ["ai-provider"], "provider-undecided", "Optional bounded adapter; no provider is approved."),
  surface("racing-provider", "Racing providers", ["racing-providers"], "current-source", "FastTrack/TheDogs ingestion boundary with provenance."),
] as const;

export const ARCHITECTURE_TRUST_FLOW_FIELD_REQUIREMENTS = [
  ["security.trust-boundary-diagram.format", "format"],
  ["security.trust-boundary-diagram.external-actors", "externalActors"],
  ["security.trust-boundary-diagram.internal-actors", "internalActors"],
  ["security.trust-boundary-diagram.processes", "processes"],
  ["security.trust-boundary-diagram.datastores", "datastores"],
  ["security.trust-boundary-diagram.external-services", "externalServices"],
  ["security.trust-boundary-diagram.trust-boundaries", "trustBoundaries"],
  ["security.trust-boundary-diagram.authentication-boundaries", "authenticationBoundaries"],
  ["security.trust-boundary-diagram.authorization-boundaries", "authorizationBoundaries"],
  ["security.trust-boundary-diagram.encryption-boundaries", "encryptionBoundaries"],
  ["security.trust-boundary-diagram.sensitive-data-flows", "sensitiveDataFlows"],
  ["security.trust-boundary-diagram.entry-points", "entryPoints"],
  ["security.trust-boundary-diagram.exit-points", "exitPoints"],
] as const;

export type ArchitectureTrustFlow = {
  id: string;
  requirementId: string;
  title: string;
  format: "Design Lab typed flow v1";
  path: readonly string[];
  externalActors: readonly string[];
  internalActors: readonly string[];
  processes: readonly string[];
  datastores: readonly string[];
  externalServices: readonly string[];
  trustBoundaries: readonly string[];
  authenticationBoundaries: readonly string[];
  authorizationBoundaries: readonly string[];
  encryptionBoundaries: readonly string[];
  sensitiveDataFlows: readonly string[];
  entryPoints: readonly string[];
  exitPoints: readonly string[];
  evidence: readonly string[];
};

type ArchitectureTrustFlowSeed = Omit<
  ArchitectureTrustFlow,
  "requirementId" | "format" | "evidence"
>;

function flow(seed: ArchitectureTrustFlowSeed): ArchitectureTrustFlow {
  return {
    ...seed,
    requirementId: `security.trust-boundary-diagram.${seed.id}`,
    format: "Design Lab typed flow v1",
    evidence: [PLAN, REPORT],
  };
}

export const ARCHITECTURE_TRUST_FLOWS = [
  flow({
    id: "public-browsing",
    title: "Public browsing",
    path: ["Australian visitor", "Google edge + Armor", "Allowlisted CDN", "Public app/read model"],
    externalActors: ["Anonymous Australian visitor"],
    internalActors: ["Edge policy", "public web/API application"],
    processes: ["TLS termination", "bot/rate decision", "cache-key evaluation", "bounded public read"],
    datastores: ["Global public CDN cache", "AU object storage", "PostgreSQL public read model"],
    externalServices: ["Google edge network"],
    trustBoundaries: ["Internet to Google edge", "edge cache miss to Australian application", "application to private data plane"],
    authenticationBoundaries: ["Anonymous allowlist only; session-bearing requests leave the shared-cache path"],
    authorizationBoundaries: ["Only explicitly public routes and fields can be returned"],
    encryptionBoundaries: ["HTTPS terminates at the edge; protected transport continues to the origin"],
    sensitiveDataFlows: ["No private or tenant data may enter the shared CDN"],
    entryPoints: ["Public page and reviewed anonymous read routes"],
    exitPoints: ["Public response with explicit cache policy and correlation metadata"],
  }),
  flow({
    id: "authentication",
    title: "Authentication and account recovery",
    path: ["User browser", "Protected auth route", "WorkOS", "Server callback", "Local session/account"],
    externalActors: ["End user", "identity-provider operator"],
    internalActors: ["Authentication route", "callback handler", "account service"],
    processes: ["Redirect allowlist", "OIDC exchange", "session issuance", "recovery validation"],
    datastores: ["WorkOS identity store", "local account/session records"],
    externalServices: ["WorkOS"],
    trustBoundaries: ["Browser to edge", "application to identity provider", "provider assertion to local account"],
    authenticationBoundaries: ["Provider authentication and server-side session issuance"],
    authorizationBoundaries: ["A valid identity does not grant role, tenant or object access"],
    encryptionBoundaries: ["HTTPS redirects/callbacks and protected server-to-provider exchange"],
    sensitiveDataFlows: ["Identity assertion, session metadata and recovery signals"],
    entryPoints: ["Sign-in, callback and recovery routes"],
    exitPoints: ["Bounded session, generic recovery response or fail-closed error"],
  }),
  flow({
    id: "authenticated-use",
    title: "Authenticated application use",
    path: ["Member", "Edge + ESPv2", "Next.js application", "Object/tenant authorization", "PostgreSQL RLS"],
    externalActors: ["Authenticated member"],
    internalActors: ["Gateway", "application service", "database runtime role"],
    processes: ["Quota", "session validation", "schema validation", "object authorization", "bounded transaction"],
    datastores: ["PostgreSQL", "approved private object storage", "optional disposable cache"],
    externalServices: ["WorkOS when session/provider validation is required"],
    trustBoundaries: ["Client to protected edge", "gateway to application", "application to private data plane"],
    authenticationBoundaries: ["Gateway coarse identity and application session validation"],
    authorizationBoundaries: ["Server object/function/tenant check followed by RLS defence in depth"],
    encryptionBoundaries: ["HTTPS and encrypted private service/database transport"],
    sensitiveDataFlows: ["Account, tenant, community, marketplace and private-media metadata"],
    entryPoints: ["Declared authenticated web and API routes"],
    exitPoints: ["Explicit response fields, queued acceptance or safe error with correlation ID"],
  }),
  flow({
    id: "administration",
    title: "Administration",
    path: ["Administrator", "Workforce/session identity", "Private admin route", "Privilege check + reauth", "Audit + datastore"],
    externalActors: ["Authorized administrator", "support operator with scoped role"],
    internalActors: ["Admin guard", "privileged service", "audit writer"],
    processes: ["MFA/session validation", "role/permission check", "dangerous-action approval", "immutable audit"],
    datastores: ["PostgreSQL", "security audit sink"],
    externalServices: ["WorkOS/workforce identity", "paging for emergency actions"],
    trustBoundaries: ["Managed administrator device to edge", "admin route to privileged service", "privileged service to data/control plane"],
    authenticationBoundaries: ["Phishing-resistant MFA and privileged reauthentication are selected"],
    authorizationBoundaries: ["Deny-by-default admin permission and two-person approval for destructive actions"],
    encryptionBoundaries: ["HTTPS and encrypted private control/data-plane calls"],
    sensitiveDataFlows: ["User support data, billing/admin records and privileged-action evidence"],
    entryPoints: ["Private or tightly protected administration routes"],
    exitPoints: ["Scoped result plus tamper-resistant audit event"],
  }),
  flow({
    id: "billing",
    title: "Billing and entitlement",
    path: ["Member or provider", "Exact billing route", "Billing service", "Stripe/Lago", "Entitlement state"],
    externalActors: ["Member", "payment provider"],
    internalActors: ["Checkout service", "webhook verifier", "entitlement service"],
    processes: ["Server price selection", "signature/replay verification", "event dedupe", "reconciliation"],
    datastores: ["Provider billing store", "local customer/invoice/entitlement records"],
    externalServices: ["Stripe", "Lago"],
    trustBoundaries: ["Browser to checkout route", "provider webhook to exact ingress", "billing service to entitlement datastore"],
    authenticationBoundaries: ["Member session for checkout; provider signature for webhook"],
    authorizationBoundaries: ["Server owns plan, customer and entitlement decisions"],
    encryptionBoundaries: ["HTTPS to app/provider; card data remains at the provider"],
    sensitiveDataFlows: ["Customer/provider IDs, plan, invoice and entitlement status"],
    entryPoints: ["Checkout, portal, return and exact signed webhook routes"],
    exitPoints: ["Provider redirect, informational return and reconciled server entitlement"],
  }),
  flow({
    id: "racing-ingestion",
    title: "Racing-data ingestion",
    path: ["Scheduler", "Isolated ingestion worker", "Racing provider", "Validation + provenance", "PostgreSQL read model"],
    externalActors: ["Racing-data provider operator"],
    internalActors: ["Scheduler", "ingestion worker", "validation and persistence services"],
    processes: ["Bounded fetch", "schema/size validation", "source provenance", "idempotent upsert", "freshness tracking"],
    datastores: ["Bounded raw archive", "PostgreSQL normalized racing data"],
    externalServices: ["FastTrack", "TheDogs"],
    trustBoundaries: ["Scheduler to worker", "worker egress to provider", "untrusted provider response to trusted datastore"],
    authenticationBoundaries: ["Scheduler/worker service identity and provider credential where required"],
    authorizationBoundaries: ["Only approved providers, operations and destination tables"],
    encryptionBoundaries: ["HTTPS where supported and encrypted Australian storage"],
    sensitiveDataFlows: ["Provider credential and provenance metadata; racing facts are generally public"],
    entryPoints: ["Scheduled jobs and exact reviewed provider callbacks"],
    exitPoints: ["Validated records, labelled stale fallback or quarantined failure"],
  }),
  flow({
    id: "community",
    title: "Community content",
    path: ["Member", "Protected community route", "Authorization + validation", "Moderation/outbox", "PostgreSQL + workers"],
    externalActors: ["Member", "moderator"],
    internalActors: ["Community service", "moderation service", "notification worker"],
    processes: ["Membership/block check", "content validation", "moderation", "transactional write", "notification enqueue"],
    datastores: ["PostgreSQL community records", "audit/moderation records", "queue"],
    externalServices: ["Notification provider after queued dispatch"],
    trustBoundaries: ["User content to application", "moderation decision boundary", "database event to worker/provider"],
    authenticationBoundaries: ["Member session; moderator role for moderation actions"],
    authorizationBoundaries: ["Object ownership, membership, block relationship and moderator permission"],
    encryptionBoundaries: ["HTTPS and encrypted database/queue/provider transport"],
    sensitiveDataFlows: ["User content, actor identity, block/membership and moderation evidence"],
    entryPoints: ["Feed, forum, group and report routes"],
    exitPoints: ["Authorized content response, moderation state and queued notification"],
  }),
  flow({
    id: "messaging",
    title: "Private messaging",
    path: ["Member", "Messaging API", "Conversation membership + block check", "AlloyDB + outbox", "AU Pub/Sub", "Regional gateway + Redis", "Cursor-capable client"],
    externalActors: ["Conversation participants"],
    internalActors: ["Messaging service", "authorization service", "outbox publisher", "regional realtime gateway"],
    processes: ["Participant validation", "block check", "transactional message/outbox write", "idempotent publish", "ephemeral fan-out", "cursor replay"],
    datastores: ["AlloyDB conversations/messages/outbox", "Pub/Sub backlog", "regional disposable Redis"],
    externalServices: ["Google Cloud regional realtime data plane"],
    trustBoundaries: ["Client to messaging API", "conversation object to authorization", "outbox to Pub/Sub", "gateway to client"],
    authenticationBoundaries: ["Member session, short-lived connection grant and workload identities"],
    authorizationBoundaries: ["Conversation membership and block relationship on every object/channel/cursor"],
    encryptionBoundaries: ["HTTPS/WSS and authenticated encrypted private service transport"],
    sensitiveDataFlows: ["Private message content, participant and read-state metadata"],
    entryPoints: ["Conversation, message, search, connection-grant and replay routes"],
    exitPoints: ["Authorized message response, scoped realtime event or durable cursor replay"],
  }),
  flow({
    id: "calls",
    title: "Voice and video calls",
    path: ["Member", "Call authorization route", "Short-lived room token", "LiveKit media plane", "Signed lifecycle webhook"],
    externalActors: ["Call participants", "LiveKit webhook sender"],
    internalActors: ["Call service", "membership/block authorization", "webhook handler"],
    processes: ["Room access check", "token issue", "call lifecycle reconciliation", "end/invite controls"],
    datastores: ["PostgreSQL room/participant metadata", "audit events"],
    externalServices: ["LiveKit"],
    trustBoundaries: ["Client to token route", "application to LiveKit", "provider webhook to application"],
    authenticationBoundaries: ["Member session, short-lived room token and signed provider webhook"],
    authorizationBoundaries: ["Room membership, block relationship, participant role and exact token scope"],
    encryptionBoundaries: ["HTTPS to app/provider and provider media encryption"],
    sensitiveDataFlows: ["Participant identity, room metadata and voice/video media"],
    entryPoints: ["Room, invite, token, end and exact webhook routes"],
    exitPoints: ["Scoped media session, audited lifecycle update or denied token"],
  }),
  flow({
    id: "marketplace",
    title: "Marketplace",
    path: ["Buyer or seller", "Marketplace API", "Listing/object authorization", "PostgreSQL", "Media/payment boundary"],
    externalActors: ["Buyer", "seller", "advertiser/boost purchaser"],
    internalActors: ["Listing service", "enquiry service", "entitlement/boost service"],
    processes: ["Listing validation", "ownership check", "enquiry", "state transition", "boost entitlement"],
    datastores: ["PostgreSQL listings/enquiries", "authorized media objects", "billing references"],
    externalServices: ["Stripe/Lago", "object storage provider"],
    trustBoundaries: ["Client to listing API", "listing ownership boundary", "app to media/payment provider"],
    authenticationBoundaries: ["Member session and provider webhook signature for paid state"],
    authorizationBoundaries: ["Listing ownership, visibility, buyer/seller separation and server entitlement"],
    encryptionBoundaries: ["HTTPS plus encrypted database/object/provider transport"],
    sensitiveDataFlows: ["Seller identity, enquiry content, private media and payment references"],
    entryPoints: ["Listing browse/detail/create/update/enquiry/boost routes"],
    exitPoints: ["Explicit listing fields, authorized enquiry and reconciled boost state"],
  }),
  flow({
    id: "uploads",
    title: "Controlled file uploads",
    path: ["Authenticated user", "Upload intent", "AU quarantine", "Scanner worker", "Published/private AU storage"],
    externalActors: ["Authenticated uploader"],
    internalActors: ["Media service", "scanner worker", "metadata finalizer"],
    processes: ["Tenant/size/type/quota check", "signed upload", "signature/MIME/malware scan", "promotion"],
    datastores: ["AU quarantine storage", "published/private AU storage", "media metadata"],
    externalServices: ["Australian Cloud Storage"],
    trustBoundaries: ["Untrusted client file to quarantine", "quarantine to scanner", "clean object to trusted serving origin"],
    authenticationBoundaries: ["Member session before signed capability; workload identity for scanner"],
    authorizationBoundaries: ["Tenant path, object ownership, quota and short-lived signed scope"],
    encryptionBoundaries: ["HTTPS signed upload/download and encrypted object storage"],
    sensitiveDataFlows: ["User file content, object metadata and scan outcome"],
    entryPoints: ["Sign-upload and finalize routes plus direct signed quarantine URL"],
    exitPoints: ["Authorized signed download/public approved media or audited rejection"],
  }),
  flow({
    id: "exports",
    title: "Data exports",
    path: ["Member", "Export request", "Bounded queue", "RLS-aware worker", "Private AU object", "Signed download"],
    externalActors: ["Account owner", "authorized support operator"],
    internalActors: ["Export service", "queue", "export worker", "download authorizer"],
    processes: ["Reauthentication", "scope validation", "asynchronous generation", "ownership check", "expiry/deletion"],
    datastores: ["PostgreSQL", "queue", "private AU object storage", "audit log"],
    externalServices: ["Object storage provider"],
    trustBoundaries: ["User to export admission", "worker to tenant data", "private object to signed download"],
    authenticationBoundaries: ["Account session and privileged reauthentication for sensitive export"],
    authorizationBoundaries: ["Subject/tenant scope at query and download; support access is separately scoped"],
    encryptionBoundaries: ["HTTPS and encrypted database/queue/object storage"],
    sensitiveDataFlows: ["Personal, account and activity data in a temporary private artifact"],
    entryPoints: ["User/admin export request routes"],
    exitPoints: ["Short-lived owner-bound download or expired/deleted artifact"],
  }),
  flow({
    id: "deletion",
    title: "Account deletion",
    path: ["Account owner or authorized admin", "Reauthentication", "Deletion coordinator", "Data/provider jobs", "Audit tombstone"],
    externalActors: ["Account owner", "authorized administrator", "affected providers"],
    internalActors: ["Deletion service", "data owners", "worker coordinator", "audit writer"],
    processes: ["Identity confirmation", "last-admin guard", "legal hold check", "idempotent purge/anonymize", "reconciliation"],
    datastores: ["PostgreSQL", "object storage", "provider references", "minimal audit tombstone"],
    externalServices: ["Identity, billing, media, messaging and notification providers as applicable"],
    trustBoundaries: ["Requester to destructive operation", "coordinator to each data owner", "application to external provider deletion"],
    authenticationBoundaries: ["Recent reauthentication and provider/service identity"],
    authorizationBoundaries: ["Self/tenant/admin scope, last-admin protection and dual approval where required"],
    encryptionBoundaries: ["HTTPS and encrypted internal/provider deletion calls"],
    sensitiveDataFlows: ["Personal identifiers, deletion scope, legal-hold state and completion evidence"],
    entryPoints: ["Self-service and authorized administration deletion routes"],
    exitPoints: ["Idempotent completion, retained legal exception or safe retry state"],
  }),
  flow({
    id: "ai-tools",
    title: "AI tools",
    path: ["Entitled member", "AI admission + policy", "Bounded queue/adapter", "AI provider", "Output validator"],
    externalActors: ["Entitled user", "AI provider"],
    internalActors: ["AI policy service", "tool allowlist", "worker/adapter", "output validator"],
    processes: ["Entitlement/quota", "context minimization", "prompt/tool policy", "token/cost limit", "output validation"],
    datastores: ["Approved minimal context", "queue metadata", "safe outcome/audit record"],
    externalServices: ["Provider undecided; no provider is approved by this inventory"],
    trustBoundaries: ["User input to AI policy", "minimized context to provider", "untrusted model output to application"],
    authenticationBoundaries: ["Authenticated entitled session and dedicated provider identity"],
    authorizationBoundaries: ["Per-user/tenant quota and strict tool/resource allowlist"],
    encryptionBoundaries: ["HTTPS provider transport; provider storage/residency remains unverified"],
    sensitiveDataFlows: ["Minimized prompt context, tool arguments and untrusted model output"],
    entryPoints: ["Declared authenticated AI/agent routes"],
    exitPoints: ["Validated bounded response, queued result or disabled/denied outcome"],
  }),
  flow({
    id: "design-lab",
    title: "Design Lab",
    path: ["Authorized local/staging reviewer", "Design Lab access policy", "Synthetic/public fixtures", "Read-only UI"],
    externalActors: ["Authorized product/security reviewer"],
    internalActors: ["Design Lab route guard", "screen registry", "release-gate evaluator"],
    processes: ["Environment/identity check", "synthetic fixture load", "source-static evidence evaluation", "noindex response"],
    datastores: ["Local disposable demo database", "source registries", "local audit artifacts"],
    externalServices: ["Approved public racing sources only; no production service mutation"],
    trustBoundaries: ["Reviewer to nonproduction route", "Design Lab to local/synthetic data", "evidence UI to protected release approval"],
    authenticationBoundaries: ["Local/staging access policy; production enablement fails closed"],
    authorizationBoundaries: ["Browser state never grants release or production data access"],
    encryptionBoundaries: ["Loopback/local development or authorized staging HTTPS boundary"],
    sensitiveDataFlows: ["No production customer rows; synthetic/private fixtures stay nonproduction"],
    entryPoints: ["Registered Design Lab routes"],
    exitPoints: ["Noindexed evidence UI and blocked/ready-for-approval status only"],
  }),
  flow({
    id: "cicd",
    title: "CI/CD and deployment",
    path: ["Developer pull request", "GitHub review + CI", "Signed immutable artifact", "Protected approval", "AU Cloud Run revision"],
    externalActors: ["Developer", "independent reviewer", "authorized production approver"],
    internalActors: ["CI workflow", "security/test gates", "artifact registry", "deployment workflow"],
    processes: ["Review", "test/scan", "SBOM/provenance", "digest binding", "protected promotion", "canary/rollback"],
    datastores: ["Source repository", "CI evidence", "artifact registry", "infrastructure state", "deployment audit"],
    externalServices: ["GitHub", "Google Cloud control plane"],
    trustBoundaries: ["Developer input to reviewed source", "CI to cloud via OIDC", "approved digest to production runtime"],
    authenticationBoundaries: ["Human MFA and short-lived OIDC workload federation"],
    authorizationBoundaries: ["Protected branches, required review, environment approval and least-privilege deploy role"],
    encryptionBoundaries: ["HTTPS/provider encryption and signed/provenance-bound artifact transport"],
    sensitiveDataFlows: ["Source, build evidence, deployment metadata and secret references; no secret value in artifacts/logs"],
    entryPoints: ["Pull request, reviewed workflow dispatch and protected approval"],
    exitPoints: ["Immutable AU revision, failed gate or audited rollback"],
  }),
] as const;

export const ARCHITECTURE_MASTER_EVIDENCE_REQUIREMENT_IDS = [
  ...ARCHITECTURE_INFRASTRUCTURE_SURFACES.map((item) => item.requirementId),
  ...ARCHITECTURE_COMPONENT_FIELD_REQUIREMENTS.map(([id]) => id),
  ...ARCHITECTURE_TRUST_FLOWS.map((item) => item.requirementId),
  ...ARCHITECTURE_TRUST_FLOW_FIELD_REQUIREMENTS.map(([id]) => id),
] as const;
