import {
  DEMO_ROUTE_AUDIT_EVALUATION,
  DEMO_ROUTE_AUDIT_EXPECTED_ROWS,
  DEMO_SCREEN_COUNT,
} from "./demo-experience-registry";
import { DESIGN_LAB_RELEASE_GATE } from "./design-lab-release-gate";

export type DesignLabDeliveryProgressStatus =
  "verified" | "in-progress" | "waiting" | "blocked";

export type DesignLabDeliveryProgressItem = {
  id: string;
  title: string;
  summary: string;
  status: DesignLabDeliveryProgressStatus;
  verificationOutcome: "pass" | "fail" | "pending";
  owner: string;
  updatedAt: string;
  evidence: readonly string[];
  verification: readonly string[];
  nextStep?: string;
};

const exactRouteAuditComplete =
  DEMO_ROUTE_AUDIT_EVALUATION.valid &&
  DEMO_ROUTE_AUDIT_EVALUATION.failedRoutes.length === 0 &&
  DEMO_ROUTE_AUDIT_EVALUATION.passedRoutes.length > 0;
const exactRouteAuditScore = `${DEMO_ROUTE_AUDIT_EVALUATION.passedRoutes.length}/${
  DEMO_ROUTE_AUDIT_EVALUATION.summary?.expected ?? "?"
}`;

export const DESIGN_LAB_DELIVERY_PROGRESS: readonly DesignLabDeliveryProgressItem[] =
  [
    {
      id: "WORK.RUNTIME.LOCALHOST",
      title: "Read-only Design Lab runtime",
      summary:
        "Localhost is running in isolated full-access demo mode and returns the read-only response header.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Runtime lane",
      updatedAt: "2026-07-13T19:50:00+10:00",
      evidence: ["src/lib/demo-access.ts", "scripts/audit-demo-routes.ts"],
      verification: [
        "GET http://localhost:3000/design-lab -> 200 + X-GreyhoundIQ-Demo",
      ],
    },
    {
      id: "WORK.API.OPENAPI",
      title: "Source-derived OpenAPI candidate",
      summary:
        "The current OpenAPI 3.0.3 candidate is source-derived and passes path, operation-ID, reference and Checkout request-encoding inventory checks.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "API contract lane",
      updatedAt: "2026-07-13T19:50:00+10:00",
      evidence: ["openapi.json", "src/app/api/billing/checkout/route.ts"],
      verification: [
        "OpenAPI parse, operation-ID uniqueness, and reference validation",
      ],
    },
    {
      id: "WORK.API.STATIC-AUDIT",
      title: "Free OpenAPI static security audit",
      summary:
        "The source-derived Spectral 6.16.1 candidate has zero errors and 163 warnings. A fail-closed AST registry proves 62 real limited API operations, the runtime emits one tested shared 429 contract, OpenAPI annotations synchronize only from that registry, and replay now uses one encrypted capability parameter; immutable deployed negative tests remain open.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "API security lane",
      updatedAt: "2026-07-14T06:13:41+10:00",
      evidence: [
        "openapi.json",
        ".spectral.yaml",
        "scripts/harden-openapi-contract.mjs",
        "scripts/harden-openapi-contract.test.mjs",
        "scripts/openapi-ruleset.test.mjs",
        "scripts/sync-openapi-rate-limits.ts",
        "scripts/sync-openapi-rate-limits.test.ts",
        "package.json",
        ".github/workflows/ci.yml",
        "security/rate-limits.ts",
        "security/rate-limits.test.ts",
        "src/lib/rate-limit-response.ts",
        "src/lib/rate-limit-response.test.ts",
        "src/lib/rate-limit-response-route-contract.test.ts",
        "scripts/check-race-replay-parsers.ts",
        "src/lib/live/replay-proxy.ts",
        "src/app/api/replay/stream/route.ts",
        "docs/security/openapi-static-audit.md",
      ],
      verification: [
        "Spectral 6.16.1; OpenAPI SHA-256 26a56856a97ebfb7387cdf3f56ca5fd502eb639760a8f948ca59878359f936d2",
        "163 findings: zero errors; 98 restricted-string, 63 validation-response and 2 additionalProperties warnings; exit 0 at error severity",
        "Replay MEDIA-SIGNED-URL-001 is limited to the encrypted base64url t capability, 600 seconds, 30-second skew, API Security ownership and review by 2026-10-14; other URL credentials still fail",
        "REPLAY-STREAM-503-SAME-ORIGIN-001 applies only to GET /api/replay/stream 503, has complete review metadata, and fails if copied while global CORS checks remain enabled",
        "AST parity derives 62/102 API operations with a limiter: 61 database-distributed and one process-local replay backstop; 104 total methods include callback and sign-in",
        "All 62 limiter denials use the tested shared 429 body and headers; exact operation IDs and policies synchronize into OpenAPI and fail closed on drift",
        "The overbroad upstream all-2XX/all-4XX quota-header rule is replaced only by source parity, exact synchronization and custom operation/response rules; all other OWASP API4 rules remain enabled",
        "Independent source-static review PASS: exact import provenance and stale-managed-429 mutations fail closed; removing all registered 429 responses produces 62 custom-rule errors",
      ],
      nextStep:
        "Bind authorised negative authorisation, input, response-header, replay, edge-limit and access-log-redaction tests to the immutable candidate, and complete deployed replay egress validation. Triage the 163 warnings without inventing runtime behavior.",
    },
    {
      id: "WORK.CAPACITY.EGRESS",
      title: "Staging-load network boundary",
      summary:
        "App, Realtime, media-upload, redirect and custom-path targets now fail closed to exact approved origins.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Capacity and security lane",
      updatedAt: "2026-07-13T19:50:00+10:00",
      evidence: [
        "scripts/staging-load-policy.ts",
        "scripts/staging-load-policy.test.ts",
        "scripts/staging-load-probe.ts",
      ],
      verification: [
        "npx tsx scripts/staging-load-policy.test.ts",
        "Independent egress review PASS",
      ],
    },
    {
      id: "WORK.OBSERVABILITY.AGGREGATE-MAINTENANCE",
      title: "Aggregate-maintenance monitoring",
      summary:
        "The bounded rate-limit cleanup and aggregate-refresh source implementation now has independently reviewed timing, structured completion/attention events, mutation-free Google Cloud discovery, strict monitoring identifiers, and source-defined failure/absence alerts. This is a source-static PASS only: no Google Cloud resource, notification delivery, Scheduler failure, metric ingestion, backlog ceiling, or production runtime behavior has been verified.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Observability and database reliability lane",
      updatedAt: "2026-07-14T06:46:14+10:00",
      evidence: [
        "src/lib/rate-limit-maintenance.ts",
        "src/lib/rate-limit-maintenance.test.ts",
        "src/lib/live/sync.ts",
        "src/lib/live/sync-aggregate-maintenance.test.ts",
        "scripts/check-rate-limit-maintenance-postgres.ts",
        "scripts/gcp-monitoring-setup.sh",
        "scripts/gcp-monitoring-setup.test.ts",
        "scripts/check-production-safety.ts",
        "docs/security/logging-and-alerting.md",
        "docs/architecture/incident-response-controls.md",
      ],
      verification: [
        "Independent source-static re-review PASS; no cloud calls or production promotion",
        "Cleanup runs in bounded 5,000-row batches with a 10-batch ceiling, SKIP LOCKED progress and explicit completion/attention events",
        "Application budget 780 seconds, per-view ceiling 120 seconds, Scheduler deadline 840 seconds and Cloud Run timeout 900 seconds preserve explicit timing headroom",
        "Monitoring validation rejects malformed project, service and notification-channel values; Cloud Run service-name boundaries prove 49 characters pass and 50 fail with zero gcloud calls",
        "Fake-gcloud exit-9 discovery failures for uptime checks, log metrics and alert policies terminate with zero create/update mutations",
        "Metric-absence documentation blocks deployment until a successful post-creation run_completed sample and a later 90-minute absence/page/acknowledgement exercise are proved",
      ],
      nextStep:
        "In an authorised production project, validate the approved host, service and enabled on-call channel; reconcile and inspect the exact metrics and policies; seed the first successful completion sample; exercise the post-seed absence and Scheduler-failure pages; prove acknowledgement, closure, ingestion delay, backlog and database ceilings; then bind the results to the immutable release candidate.",
    },
    {
      id: "WORK.UI.AUDIT-CHECKLIST",
      title: "Master-checklist render performance",
      summary:
        "Collapsed groups lazy-mount requirement rows, reducing initial server-rendered markup from 5.52 MB to 1.20 MB.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Design Lab UI lane",
      updatedAt: "2026-07-13T19:50:00+10:00",
      evidence: [
        "src/components/master-audit-checklist.tsx",
        "src/components/master-audit-checklist.test.ts",
      ],
      verification: [
        "npx tsx src/components/master-audit-checklist.test.ts",
        "Browser expand/collapse QA",
      ],
    },
    {
      id: "WORK.DOCS.LIVE-COUNTERS",
      title: "Live product and security report counters",
      summary:
        "Nine product audit reports and the release security report now carry machine-managed counter blocks derived from the same screen, master, pre-production and database registries as the Design Lab UI. Documentation CI fails on missing blocks or any count drift.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Evidence and documentation lane",
      updatedAt: "2026-07-14T11:41:22+10:00",
      evidence: [
        "scripts/check-design-lab-doc-counters.ts",
        "scripts/check-design-lab-doc-counters.test.ts",
        "scripts/check-docs.mjs",
        "docs/product/design-lab-coverage.md",
        "docs/product/final-audit-report.md",
        "docs/product/route-inventory.md",
        "docs/product/user-story-matrix.md",
        "docs/product/action-inventory.md",
        "docs/product/form-field-registry.md",
        "docs/product/permissions-matrix.md",
        "docs/product/state-matrix.md",
        "docs/product/onboarding-map.md",
        "docs/security/release-security-report.md",
      ],
      verification: [
        "npx tsx scripts/check-design-lab-doc-counters.test.ts",
        "npm run docs:check",
        "Negative fixture proves a one-count aggregate drift fails closed",
        "GET /design-lab?area=overview renders the same registry-derived total",
      ],
    },
    {
      id: "WORK.UI.RESPONSIVE-WORKSPACE",
      title: "Responsive tables and architecture diagrams",
      summary:
        "A source-bound loopback Chrome audit covers all seven Design Lab workspace areas and the linked architecture report at 360px and 390px. It fails on document overflow, overwide visible tables, inaccessible clipped diagrams, browser exceptions or mutating requests.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Design Lab responsive evidence lane",
      updatedAt: "2026-07-14T11:44:06+10:00",
      evidence: [
        "scripts/audit-design-lab-responsive-workspace.ts",
        "scripts/audit-design-lab-responsive-workspace.test.ts",
        "output/design-lab-responsive-workspace/latest.json",
        "docs/product/responsive-audit.md",
      ],
      verification: [
        "16/16 loopback cases pass across 360px and 390px",
        "70 table measurements with zero visible overwide tables",
        "30 diagram measurements with zero inaccessible clipped diagrams",
        "Zero document-overflow cases, browser exceptions or mutating requests",
      ],
    },
    {
      id: "WORK.ROUTES.EXACT-AUDIT",
      title: `Exact ${DEMO_ROUTE_AUDIT_EXPECTED_ROWS.length}-route localhost audit`,
      summary: `The hardened single-worker sweep is ${exactRouteAuditScore}; Feed demo reads are serialized for the one-connection local pool while non-demo reads remain parallel.`,
      status: exactRouteAuditComplete ? "verified" : "in-progress",
      verificationOutcome: exactRouteAuditComplete ? "pass" : "fail",
      owner: "Route evidence lane",
      updatedAt:
        DEMO_ROUTE_AUDIT_EVALUATION.generatedAt ?? "2026-07-13T00:00:00+10:00",
      evidence: [
        "output/demo-route-audit/latest.json",
        "scripts/audit-demo-routes.ts",
        "scripts/audit-demo-routes.test.ts",
      ],
      verification: [
        "npx tsx scripts/audit-demo-routes.test.ts",
        `${exactRouteAuditScore} exact localhost routes pass with raw response predicates validated`,
        "Feed scheduler test preserves parallel non-demo reads and serial full-access demo reads",
      ],
      ...(exactRouteAuditComplete
        ? {}
        : {
            nextStep:
              "Rerun the exact localhost route audit against unchanged source and close every failed route.",
          }),
    },
    {
      id: "WORK.SECURITY.REPORT-BAN",
      title: "Last-admin and self-lockout bypass",
      summary:
        "Ban authorization now locks, re-reads actor and target state, checks moderator/admin/self/last-admin rules, then mutates; independent bypass review passed.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Authorization lane",
      updatedAt: "2026-07-13T20:17:00+10:00",
      evidence: [
        "src/lib/report-service.ts",
        "src/lib/admin-access-contract.ts",
        "src/lib/report-ban-policy.test.ts",
      ],
      verification: [
        "Report-ban and admin-access policy tests pass",
        "Independent demotion, inactive-actor and last-admin bypass review PASS",
        "Typecheck and focused lint pass",
      ],
    },
    {
      id: "WORK.EVIDENCE.MASTER",
      title: "Master evidence reconciliation",
      summary:
        "Five narrow master claims plus 82 exact production-enabled route-registration requirements have independently reviewed evidence without overriding any action, authorization, state, payment or production-runtime gate. The prior /account/appearance credit was removed because that preview is production-disabled; /auth/error was not manufactured because no matching atomic master requirement exists.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Evidence lane",
      updatedAt: "2026-07-13T19:50:00+10:00",
      evidence: [
        "src/components/master-audit-evidence.ts",
        "src/components/master-audit-requirements.test.ts",
        "src/components/product-route-master-evidence.ts",
        "src/components/product-route-master-evidence.test.ts",
        "output/demo-route-audit/latest.json",
      ],
      verification: [
        "Master registry, route registry, security registry, and Stripe behavior tests",
        "Independent exact-route master review PASS: 82 unique production-enabled route registrations with family split 7 public / 9 racing / 15 community / 6 Marketplace / 12 Account / 32 Administration / 1 AI",
        "Honest correction: candidate master evidence decreased by one after excluding production-disabled /account/appearance",
      ],
    },
    {
      id: "WORK.EVIDENCE.ROUTE-REGISTRY",
      title: "Atomic route-registry evidence",
      summary: `Nine narrow product gates now have independently reviewed evidence for Design Lab consumption, route inspection, dynamic patterns and parameters, titles, product-area mapping, exact noindex policy, default production enablement and Design Lab indexing prevention across the live ${DEMO_SCREEN_COUNT}-route registry.`,
      status: "verified",
      verificationOutcome: "pass",
      owner: "Route evidence lane",
      updatedAt: "2026-07-14T02:15:24+10:00",
      evidence: [
        "src/components/demo-experience-registry.ts",
        "src/components/demo-experience-registry.test.ts",
        "src/components/demo-experience-screen-map.tsx",
        "src/components/design-lab-route-safety.test.ts",
        "src/lib/design-lab-access-policy.test.ts",
        "docs/product/route-inventory.md",
        "src/components/master-audit-evidence.ts",
      ],
      verification: [
        `Exact ${DEMO_SCREEN_COUNT}-route filesystem parity and unique route contracts pass`,
        "All 13 dynamic route patterns and parameters match independent extraction",
        "Independent review approved nine narrow gates and rejected broader incomplete inventory claims",
      ],
    },
    {
      id: "WORK.SCREENS.PROVENANCE",
      title: "Screen evidence provenance",
      summary:
        "Four independent adversarial passes now reject every reproduced provenance bypass and accept a valid 2 MiB tracked capture frame.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Screen-contract lane",
      updatedAt: "2026-07-13T20:52:24+10:00",
      evidence: [
        "src/components/screen-contracts/types.ts",
        "scripts/screen-evidence.ts",
        "scripts/screen-evidence.test.ts",
      ],
      verification: [
        "Independent fourth-pass provenance review: PASS",
        "Duplicate IDs, typed status conflicts, junction escapes, assume-unchanged tampering, mixed roles and unsafe roots reject",
        "Exact route/frame evidence, generated descendants and a 2,097,169-byte tracked frame pass",
      ],
    },
    {
      id: "WORK.SCREENS.USER-STORIES",
      title: "Registered screen user-story rollout",
      summary: `All ${DEMO_SCREEN_COUNT} live route contracts carry complete user-story coverage, including six separately governed Design Lab manifests. Retained 90-route HTTP and hydrated captures are historical source-bound evidence; the current ${DEMO_ROUTE_AUDIT_EXPECTED_ROWS.length}-route source requires its own exact recapture in the separate route lane. This verifies only render-baseline stories. Admin request-level role denial, mutations, alternative states and AI role, tier and execution enforcement remain separate unverified work.`,
      status: "verified",
      verificationOutcome: "pass",
      owner: "User-story lane",
      updatedAt: "2026-07-14T06:50:38+10:00",
      evidence: [
        "src/components/demo-experience-registry.ts",
        "src/components/screen-contracts/public-racing-user-stories.test.ts",
        "src/components/screen-contracts/community-user-stories.test.ts",
        "src/components/screen-contracts/marketplace-account-user-stories.test.ts",
        "src/components/screen-contracts/admin-user-stories.test.ts",
        "src/components/screen-contracts/ai-user-stories.test.ts",
        "src/app/admin/admin-authorization-inventory.ts",
        "docs/product/user-story-matrix.md",
        "src/components/screen-contracts/design-lab-user-stories.ts",
        "src/components/screen-contracts/design-lab-user-stories.test.ts",
        "scripts/audit-design-lab-user-stories.ts",
        "scripts/audit-design-lab-user-stories.test.ts",
        "scripts/audit-design-lab-hydrated-stories.ts",
        "scripts/audit-design-lab-hydrated-stories.test.ts",
        "output/demo-route-audit/design-lab-user-stories.json",
        "output/demo-route-audit/design-lab-hydrated-stories.json",
        "output/demo-route-audit/design-lab-user-stories-independent-review-final.json",
      ],
      verification: [
        "84/84 authoritative non-Design-Lab routes (83 production-enabled plus the production-disabled Appearance preview) across public, racing, community, Marketplace, Account, Administration and AI map 1:1 to stable story IDs, concrete open paths and existing page sources",
        "15/15 community routes bind exact current-source audit rows, including Forum-to-Groups and Messages-to-Pulse canonical redirects",
        "19/19 Marketplace and Account routes bind an immutable exact tuple inventory to source files and current-source audit rows, including Listings-to-Marketplace canonical redirects",
        "32/32 Administration routes bind immutable exact tuples to page sources, current-source audit rows and the fail-closed role inventory (23 administrator-only, 9 moderator-capable)",
        "1/1 AI route binds an immutable exact tuple to the Agents source, current-source audit row and ai-tools-user registry role while request-level role, tier, execution, cancellation and history isolation remain unverified",
        "Each production baseline has actor, trigger, outcome, Given/When/Then render acceptance and source-specific assertions",
        "Historical source-bound HTTP evidence has one passing row for each route in its 90-route candidate; it is not current 97-route evidence",
        "Admin authorization inventory status: source-declared roles captured; request-level signed-out/member/moderator/administrator denial remains unverified",
        `Live registered screen story status: ${DEMO_SCREEN_COUNT}/${DEMO_SCREEN_COUNT} complete`,
        "Independent +84 render-evidence review: PASS at reviewed source snapshot c41739e86fb7deb910ba5eb776183ae2e8d37db9e940394ae1d164fa714a2c12 across 738 files and audit SHA-256 66f97a5b4c90026a55f5053acf07aa4be1aa3f4f8f2a245f100273d3e2c788d0; later architecture and Design Lab manifest changes did not alter those 84 mappings",
        "Historical integrated recapture: 90/90 routes against source digest e8ba3156701a714c876274de22ed5a826250e7491254fcc28b3b2a599185fd59 across 742 files; audit JSON SHA-256 051ca493a08cf306a1f62aa0e2b94c522bf4f0415de1cc64f578a1ac15d8a612",
        "Independent +3 Design Lab story review: PASS for /design-lab, /design-lab/demo-experience and /design-lab/dock-skins; HTTP evidence SHA-256 0136f5949d487706252306691408ac45a8b1a0a304d5735e337c492975a0f484 and hydrated evidence SHA-256 33b8fe1d37742c73bf13d51322a39daf1b305ecd7459eb7ba8995353cc2eddba",
        "Independent fail-closed parser review: PASS",
        "ROLE-BLUEPRINTS, FEED-DEVICE-PREVIEW and MARKETPLACE-TEMPLATES independently approved as tested",
        "Six complete local import closures contain zero form/submission signals; /design-lab traverses 64 local code files",
        "All 16 unique referenced test programs pass and are registered in the CI unit runner",
        "Action/state/fixture inventories are exact; only the independently reviewed workspace, demo-experience and dock-skins runtime sets are tested, while the remaining Design Lab routes stay captured",
        "Canonical local audit: 12/12 scenarios across 6/6 routes",
        "Hydrated local audit: 23/23 interaction scenarios prove exact workspace, demo-experience and dock action/state/fixture sets with zero mutating requests",
        "Historical HTTP-only bind: 90/90 routes passed against its frozen source fingerprint at concurrency one; current-source recapture remains in WORK.ROUTES.EXACT-AUDIT",
      ],
    },
    {
      id: "WORK.SCREENS.RUNTIME-COVERAGE",
      title: "Design Lab runtime action, state and fixture proof",
      summary:
        "The frozen 23-scenario loopback browser audit maps every action, state and synthetic fixture ID for /design-lab, /design-lab/demo-experience and /design-lab/dock-skins by exact set equality. After an initial independent rejection, family filtering was isolated, admin frames now open through a real native GET and Desktop, D1 and Home are proven through genuine state transitions. The independent re-review passed all nine tested cells with zero mutating requests.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Design Lab runtime-coverage lane",
      updatedAt: "2026-07-14T07:51:00+10:00",
      evidence: [
        "src/components/screen-contracts/design-lab-user-stories.ts",
        "src/components/screen-contracts/design-lab-user-stories.test.ts",
        "scripts/audit-design-lab-hydrated-stories.ts",
        "scripts/audit-design-lab-hydrated-stories.test.ts",
        "scripts/audit-design-lab-hydrated-stories-atomic.test.ts",
        "output/demo-route-audit/design-lab-hydrated-stories.json",
      ],
      verification: [
        "Structural contract PASS: 23 unique scenarios each own one exact action/state/fixture coverage row",
        "Exact tested inventories: workspace 4 actions / 11 states / 9 fixtures; demo experience 10 / 7 / 3; dock skins 11 / 13 / 8",
        "Zero captured mutating HTTP methods; this browser audit does not claim permissions or onboarding, which are independently source-tested; forms remain excluded",
        "Independent remediation re-review PASS: isolated racing filters each prove 9 exact routes, registry-to-admin is a native GET, viewports prove Desktop-to-Mobile-to-Desktop-to-Tablet, dock skins prove D1-to-D2-to-D1 and actions prove Menu-to-Home",
        "Stable structural JSON comparison ignores object-key insertion order while preserving strict array order; reordered-key, value-drift and array-order regression tests pass",
        "Final source-bound evidence: HTTP 12/12 SHA-256 32621f910ae5619ed7afe8898ed095bd5210e3b86c1c9de6f1aff231da144d5b; hydrated 23/23 SHA-256 022eb35ee089bd6004a1a6c837a0c742ef73631dd53cecd549cda00b18c5c3c1",
      ],
    },
    {
      id: "WORK.SCREENS.RUNTIME-COVERAGE-WAVE-2",
      title: "Design Lab runtime proof wave 2",
      summary:
        "The isolated 55-scenario loopback browser audit proves exact action, state and fixture inventories for /design-lab/role-blueprints, /feed/device-preview and /marketplace/design-lab. Only the nine browser-eligible action, state and Design Lab cells are promoted by this audit; permissions and onboarding are independently source-tested.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Design Lab runtime-coverage lane",
      updatedAt: "2026-07-14T11:56:38+10:00",
      evidence: [
        "src/components/screen-contracts/design-lab-user-stories.ts",
        "src/components/screen-contracts/design-lab-user-stories.test.ts",
        "scripts/audit-design-lab-hydrated-wave2.ts",
        "scripts/audit-design-lab-hydrated-wave2.test.ts",
        "scripts/audit-design-lab-hydrated-wave2-atomic.test.ts",
        "output/demo-route-audit/design-lab-hydrated-wave2.json",
      ],
      verification: [
        "55/55 source-bound interaction scenarios pass across the three remaining Design Lab routes",
        "Scope is exactly three routes and three eligible cells per route: actions, states and designLab",
        "This browser audit does not claim permissions or onboarding; focused source tests own those tested cells, while forms remain excluded because these routes expose no complete local form/submission contract",
        "Every transition is deterministic and the audit records zero mutating requests or browser exceptions",
      ],
    },
    {
      id: "WORK.SECURITY.SIGNUP-CALLBACK-TRACE",
      title: "Signup and callback security trace",
      summary:
        "A source-accurate partial trace now follows the AuthKit callback through local acceptance, Profile and SocialActor creation, durable SignupOutbox handoff, worker cleanup/claim/settlement and safe recovery. Independent review rejected seven initial overclaims; the repaired registry now records 18 honest database operations overall, exact 307 redirects, canonical story references, complete AuditLog columns and a fixed callback error envelope that discards raw database exceptions. No master requirement or production-runtime credit was promoted.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Identity security trace lane",
      updatedAt: "2026-07-14T07:51:00+10:00",
      evidence: [
        "security/traces.ts",
        "security/database-operations.ts",
        "security/audit-events.ts",
        "security/registry.test.ts",
        "src/app/callback/route.ts",
        "src/lib/signup-acceptance.test.ts",
        "src/lib/signup-acceptance-worker.test.ts",
        "src/lib/auth-callback-route-contract.test.ts",
        "docs/security/security-trace-registry.md",
      ],
      verification: [
        "Independent remediation re-review PASS on all seven blocking findings",
        "Registry PASS: 104 HTTP route methods, 73 server actions, 9 partial traces and 18 database operations",
        "Expired outbox cleanup is explicitly unbounded; claim and settlement are each bounded to one row",
        "Synthetic email and secret probes prove caught callback exceptions cannot enter structured logs",
        "Trace remains Partially verified: provider internals, deployed runtime, generated SQL/RLS, worker identity, concrete sink, backlog operations and end-to-end UI success remain unverified",
      ],
    },
    {
      id: "WORK.SECURITY.FINAL-TRACEABILITY",
      title: "Final security traceability and summary structure",
      summary:
        "The final security report structure is being implemented as a fail-closed known, partial and unknown envelope over the existing nine partial traces and current endpoint, database-operation and third-party registries. The candidate is limited to 44 report-structure requirements and must not imply complete traces, production-runtime verification, zero findings or complete ownership.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Security traceability lane",
      updatedAt: "2026-07-14T08:01:43+10:00",
      evidence: [
        "security/traces.ts",
        "security/database-operations.ts",
        "docs/security/security-trace-registry.md",
        "src/components/master-audit-evidence.ts",
      ],
      verification: [
        "Candidate scope is exactly 23 traceability fields plus 21 summary metrics",
        "Unsupported metrics remain unknown and partial registry counts remain explicitly partial",
        "No completion credit is counted until exact-ID, drift, scope and overclaim mutation tests pass and an independent review approves the evidence",
      ],
      nextStep:
        "Finish the typed output, regenerate the existing registry document, prove every fail-closed mutation, independently review the 44 scoped requirements, then recalculate the master counter.",
    },
    {
      id: "WORK.PREPROD.SYNTHETIC-PRIVATE-FIXTURES",
      title: "Synthetic-only private fixture gate",
      summary:
        "Independent adversarial re-review accepted the frozen schema-v2 proof: all nine approved assets have explicit fictional or non-person provenance and byte binding, two deterministic 37-row runs preserved provider data, exact cleanup returned every verifier-owned row to zero, and fail-closed mutations cover the prior rejection paths.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Pre-production data-safety lane",
      updatedAt: "2026-07-14T09:05:00+10:00",
      evidence: [
        "scripts/seed-demo-route-fixtures.ts",
        "scripts/demo-route-fixture-contract.ts",
        "scripts/demo-route-fixture-evidence.ts",
        "scripts/check-demo-route-fixture-idempotency.ts",
        "scripts/check-demo-route-fixture-idempotency.test.ts",
        "scripts/check-demo-route-fixture-evidence.test.ts",
        "security/data-classification.ts",
        "security/local-data-policy.ts",
        "docs/security/data-classification.md",
        "output/database-audit/demo-fixture-idempotency.json",
        "package.json",
      ],
      verification: [
        "Independent review accepted artifact SHA-256 616f5a6cbb08315d3834b11b18012c13673ac32f539748d878555afe5c74d308 and its exact source/asset binding",
        "The fixed binding covers 20 exact source files and nine explicitly approved assets, including every fixture portrait byte",
        "Two 37-row runs were identical; both collision probes passed; provider hashes were unchanged; exact cleanup returned fixture and provider counts to zero",
        "Mutation tests reject an omitted bound file, missing or changed asset, empty probes, forged cleanup count, erased model counts, stale or extra fields and a secret-bearing URL",
        "Maintenance contract: recapture this isolated proof whenever a bound fixture source or approved asset changes",
      ],
    },
    {
      id: "WORK.SECURITY.ADMIN-AUTHORIZATION",
      title: "Administration authorization inventory",
      summary:
        "A fail-closed inventory binds 32 administration pages, 31 privileged server actions and the report-resolution API to moderator or administrator roles; source-tested report-ban policy now denies moderator peer, administrator, self, missing-role and unknown-role targets while runtime denial remains unverified.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Authorization lane",
      updatedAt: "2026-07-14T03:18:00+10:00",
      evidence: [
        "src/app/admin/admin-authorization-inventory.ts",
        "src/app/admin/admin-authorization-inventory.test.ts",
        "src/lib/admin-access-contract.ts",
        "src/lib/report-ban-policy.test.ts",
        "src/lib/report-service.ts",
      ],
      verification: [
        "The inventory validator rejects missing, extra and role-mismatched pages, actions and handlers",
        "Focused policy and inventory tests deny moderator self, moderator, administrator, missing-role and unknown-role bans while retaining administrator authority subject to self and last-admin controls",
        "All focused administration authorization tests, typecheck, lint, build and docs checks pass",
        "Independent TypeScript-AST review: 64/64 surfaces match the inventory and none are unguarded",
        "No request-level signed-out/member/moderator/administrator denial matrix is claimed",
      ],
      nextStep:
        "Prove the complete signed-out/member/moderator/administrator request-denial matrix, then run local PostgreSQL concurrency tests for simultaneous last-admin ban, demotion and account-deletion attempts.",
    },
    {
      id: "WORK.ADS.DESIGN-CONTRACT",
      title: "Advertising and boost design contract",
      summary:
        "Three Feed placements, three seller-boost packages, eight user stories and sixteen scenarios now define provisional pricing, creative, delivery, privacy, payment and admin controls without implying a live product.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Advertising design-contract lane",
      updatedAt: "2026-07-13T21:35:25+10:00",
      evidence: [
        "src/components/advertising-product-contract.ts",
        "src/components/advertising-product-contract.test.ts",
        "src/components/design-lab-advertising-console.tsx",
        "src/components/design-lab-advertising-console.test.ts",
        "docs/product/advertising-platform.md",
      ],
      verification: [
        "Independent remediation review PASS for the Design Lab contract only",
        "Quote bounds, Checkout activation, GST, expiry, eligibility, global caps, privacy and accessibility adversarial checks pass",
        "Focused tests, ESLint, typecheck, docs check and diff check pass",
      ],
    },
    {
      id: "WORK.ADS.PLATFORM",
      title: "Advertiser platform and premium inventory",
      summary:
        "The verified Design Lab contract publishes three premium Feed placements, eight cross-lifecycle stories, sixteen scenarios, creative rules, global frequency caps, provisional AUD pricing and a fail-closed prepaid payment boundary; runtime implementation remains open.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Advertising product lane",
      updatedAt: "2026-07-13T21:35:25+10:00",
      evidence: [
        "src/components/feed-house-promotion.tsx",
        "src/components/feed-system-prototype.tsx",
        "src/components/advertising-product-contract.ts",
        "src/components/advertising-product-contract.test.ts",
        "src/components/design-lab-advertising-console.tsx",
        "src/components/design-lab-advertising-console.test.ts",
      ],
      verification: [
        "Primary-source platform, Australian advertising and payment research captured in a typed Design Lab contract",
        "Independent contract review PASS without promoting the unimplemented product",
      ],
      nextStep:
        "Implement the forward-only schema, advertiser authorization, creative review, rate-card order, Stripe sandbox and delivery services.",
    },
    {
      id: "WORK.ADS.MARKETPLACE-BOOST",
      title: "Marketplace seller boosts",
      summary:
        "The five-card Feed carousel now has three provisional GST-inclusive boost packages, owned-listing eligibility, equal seller rotation, hard caps and under-delivery credits in Design Lab.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Marketplace monetisation lane",
      updatedAt: "2026-07-13T21:35:25+10:00",
      evidence: [
        "src/components/feed-system-prototype.tsx",
        "src/components/marketplace-dog-player-card.tsx",
        "src/components/advertising-product-contract.ts",
        "src/components/design-lab-advertising-console.tsx",
      ],
      verification: [
        "Official promoted-listing patterns reviewed; fixed viewable-delivery model encoded for the enquiry-style Marketplace",
        "Independent contract review PASS without promoting seller ownership, payment or delivery implementation",
      ],
      nextStep:
        "Implement seller ownership isolation, paid boost orders, atomic delivery caps, reconciliation and responsive runtime evidence.",
    },
    {
      id: "WORK.UI.NAVIGATION",
      title: "Design Lab Mission Control navigation",
      summary:
        "The 34,102px flat desktop document is reorganized into seven shareable modules, including the production Architecture control room, with one canonical status ribbon and responsive navigation.",
      status: "verified",
      verificationOutcome: "pass",
      owner: "Design Lab UI lane",
      updatedAt: "2026-07-13T23:30:00+10:00",
      evidence: [
        "src/components/design-lab-workspace.ts",
        "src/components/design-lab-workspace.test.ts",
        "src/components/design-lab-workspace-shell.tsx",
        "src/components/design-lab-workspace-shell.test.ts",
        "src/components/demo-experience-screen-map.tsx",
      ],
      verification: [
        "Three runnable structures compared; Mission Control selected and prototype removed",
        "Focused workspace, registry and user-story tests, scoped ESLint and typecheck pass",
        "Local browser checks cover overview, advertising, screen library and a 390px mobile viewport",
        "Source-contract checks cover all seven module IDs, exact area routing and architecture report embedding",
        "Advertising table proves a 315px focusable scroll region around its 760px table at the 390px viewport",
      ],
    },
    {
      id: "WORK.DATABASE.LOCAL-CATALOG",
      title: "Local PostgreSQL compatibility evidence",
      summary:
        "The transaction-read-only, literal-loopback collector and adversarial validator are implemented. The recovered local catalog remains blocked: it ran as postgres instead of greyhoundiq_runtime and two applied migration checksums do not match the checkout.",
      status: "blocked",
      verificationOutcome: "fail",
      owner: "Database reliability lane",
      updatedAt: "2026-07-14T02:30:46+10:00",
      evidence: [
        "scripts/audit-local-postgres-catalog.ts",
        "scripts/audit-local-postgres-catalog.test.ts",
        "scripts/design-lab-source-fingerprint.ts",
        "docs/security/database-inventory.md",
      ],
      verification: [
        "Collector refuses implicit DATABASE_URL fallback, DNS targets and non-loopback hosts; it forces a one-connection read-only session",
        "PostgreSQL 15.18, UTF8/en_US.utf8/UTC, pg_trgm/plpgsql, roles, grants and 90 applied rows were captured without credentials",
        "All 107 application tables enable and FORCE RLS; the sole unprotected 108th public table is Prisma metadata _prisma_migrations",
        "Current postgres superuser/BYPASSRLS role versus intended greyhoundiq_runtime remains a blocking mismatch",
        "Applied checksums mismatch 20260710133000_free_personal_feed_writes and 20260710134000_add_social_actor_media_foundation; the latter proves an applied migration was later edited",
        "Focused contract, inventory, source-fingerprint, pre-production registry, docs, lint, typecheck and Prisma validation checks passed",
      ],
      nextStep:
        "After source settles, root captures and validates the canonical port-55733 artifact. Keep parity blocked until immutable forward-only migration history, least-privilege runtime identity and isolated unsupported-catalog replay are proven; never rewrite migration history or alter roles to make the audit pass.",
    },
    {
      id: "WORK.DATABASE.DESIGN-LAB-PARITY",
      title: "Persistent Design Lab database parity",
      summary:
        "The dedicated loopback database on port 55735 now uses a clean v2 volume built from all 93 current forward migrations; the prior v1 volume remains retained offline. Daniel's local account graph was restored with matching per-table hashes. A read-only diagnostic matched all 16 catalog families against the separate clean replay and proved the exact greyhoundiq_runtime identity with no missing or unexpected privileges. Canonical credit remains blocked until the stage-0 source and replay/parity artifacts are committed exactly at one Git HEAD.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Database reliability lane",
      updatedAt: "2026-07-14T13:57:59+10:00",
      evidence: [
        "docker-compose.design-lab-db.yml",
        "scripts/design-lab-database.ts",
        "scripts/design-lab-database.test.ts",
        "scripts/check-design-lab-database-parity.ts",
        "scripts/check-design-lab-database-parity.test.ts",
        "output/database-audit/design-lab-database-parity.json",
      ],
      verification: [
        "Current source-bound replay PASS: 97 migrations from empty storage and Prisma No difference detected; exact commit binding remains open",
        "Current read-only diagnostic PASS: 16/16 server, extension, role, membership, relation, column, constraint, index, view, function, trigger, policy, sequence, enum, grant and migration catalog families match the isolated replay",
        "Current read-only diagnostic PASS: greyhoundiq_runtime is LOGIN, non-superuser, NOBYPASSRLS, NOCREATEROLE, NOCREATEDB, limited to 40 sessions, retains CONNECT, has CREATE/TEMPORARY false and has no missing or unexpected privileges",
        "Current read-only diagnostic PASS: 107/107 application tables enable and FORCE RLS",
        "Localhost recovery PASS: /api/health/ready returns database ok after the controlled Next/Prisma restart against v2",
        "Account preservation PASS: User, Profile, SocialActor, SignupOutbox and RateLimit rows match the retained v1 volume by count and content hash",
        "The recovered provider/demo database on port 55733 remains running, unchanged and explicitly excluded from parity credit",
        "No production version, topology, TLS, backup, failover, pool capacity or production-data parity is claimed",
      ],
      nextStep:
        "Freeze and review the current source, commit the stage-0 parity controls plus verified replay artifact at one exact HEAD, recapture the canonical parity artifact from that commit, and validate it without worktree drift. Keep PREPROD.DB.PRISMA_SCHEMA_PARITY in progress until the exact-binding validator passes; local diagnostics do not substitute for that contract.",
    },
    {
      id: "WORK.OBSERVABILITY.STRUCTURED-LOGGING",
      title: "Structured runtime logging boundary",
      summary:
        "The source registry accounts for 45 production logger callsites: 28 request, 15 mixed request/job and 2 boot. Proxy-generated IDs and request-only fallbacks keep request logs correlated, while requestless execution is explicit null. Mixed-path production behavior, deployed ingestion, Cloud Trace association and remaining common fields stay open.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Observability and security lane",
      updatedAt: "2026-07-14T03:53:44+10:00",
      evidence: [
        "src/lib/logger.ts",
        "src/lib/logger.test.ts",
        "src/lib/request-id.ts",
        "src/lib/request-id.test.ts",
        "src/lib/live/sync.ts",
        "src/proxy.ts",
        "scripts/structured-logging-policy.ts",
        "scripts/structured-logging-policy.test.ts",
        "scripts/request-correlation-policy.ts",
        "scripts/request-correlation-policy.test.ts",
        "package.json",
        ".github/workflows/ci.yml",
      ],
      verification: [
        "The source registry accounts for 45 production callsites: 28 request, 15 mixed request/job and 2 boot; no detected server console or direct process-stream bypass remains",
        "Proxy overwrites caller-supplied x-request-id with a GreyhoundIQ UUID; request-only wrappers generate a normalized fallback UUID, while mixed and boot execution remains explicitly requestless outside the Next.js Node request runtime",
        "A valid x-cloud-trace-context value is preserved only as traceId; the global load balancer can pass a caller-supplied value unchanged, so trace propagation is not trusted as GreyhoundIQ's request identity",
        "The CI policy rejects supported named, namespace, chained and dynamic-import aliases, unclassified or dynamic events, unsafe literal context fields, unawaited asynchronous logging, execution-scope mismatch, duplicate/count drift and stale registry entries",
        "Focused logger, request-ID, API-error, readiness, structured-logging, request-correlation, TypeScript and ESLint checks pass",
        "Independent review recommends at most partially-verified source evidence for security.application-log-field.request-or-correlation-id; no canonical promotion is made because mixed-path runtime behavior, trace association and deployed Cloud Logging ingestion remain open",
      ],
      nextStep:
        "Prove request IDs on mixed-path logs in a deployed request, add Cloud Logging query evidence, use the required logging.googleapis.com/trace field or a supported client, and test caller trace propagation at the protected edge. Then close client-console and sensitive-category gaps and standardise operation, outcome and duration before completing ARCH-602.",
    },
    {
      id: "WORK.ARCHITECTURE.PLAN",
      title: "Australia production architecture and resilience mandate",
      summary:
        "The corrected 2026-07-16 web-MVP architecture is synchronized into Design Lab: a new free-trial GCP account, Google edge and ESPv2, Sydney/Melbourne Cloud Run cells, AlloyDB, Australian Cloud Storage, application realtime through outbox/Pub/Sub/regional Redis, and independent Sydney/Melbourne LiveKit cells with room-home routing and per-cell HA Redis. Native store delivery is post-MVP. The source-static architecture and Terraform contracts are evidence only; managed staging, provider journeys, origin enforcement, data recovery, realtime, media and load behavior remain release blockers.",
      status: "in-progress",
      verificationOutcome: "fail",
      owner: "Architecture, SRE and security lane",
      updatedAt: "2026-07-15T13:49:41+10:00",
      evidence: [
        "src/components/design-lab-architecture-inventory.ts",
        "src/components/design-lab-architecture-inventory.test.ts",
        "src/components/design-lab-architecture-lab.tsx",
        "src/components/design-lab-architecture-lab.test.ts",
        "src/components/master-audit-evidence.ts",
        "docs/architecture/greyhoundiq-australia-production-architecture.md",
        "docs/architecture/greyhoundiq-production-architecture-report.html",
        "public/greyhoundiq-production-architecture.html",
        "src/components/design-lab-architecture-plan.ts",
        "infra/terraform/README.md",
        "infra/terraform/main.tf",
        "infra/terraform/edge.tf",
        "infra/terraform/.terraform.lock.hcl",
        "infra/terraform/contract.test.mjs",
        ".github/workflows/ci.yml",
        ".agents/skills/greyhoundiq-production-architecture/SKILL.md",
        "config/gcp-architecture.json",
        "scripts/gcp-architecture-policy.ts",
        "scripts/gcp-architecture-policy.test.ts",
        "scripts/check-database-compatibility-inventory.ts",
        "scripts/check-database-compatibility-inventory.test.ts",
        "docs/security/database-inventory.md",
        "prisma/migrations/20260714004000_add_signup_acceptance_outbox/migration.sql",
        "prisma/migrations/20260714010000_add_signup_outbox_lease_token/migration.sql",
        "src/lib/signup-acceptance.ts",
        "src/lib/signup-acceptance.test.ts",
        "src/lib/signup-acceptance-worker.ts",
        "src/lib/signup-acceptance-worker-store.ts",
        "src/lib/signup-acceptance-worker.test.ts",
        "src/lib/auth-sync.ts",
        "src/app/callback/route.ts",
        "src/lib/request-id.ts",
        "src/lib/request-id.test.ts",
        "src/lib/logger.ts",
        "src/lib/logger.test.ts",
        "src/lib/db-context.ts",
        "src/app/api/health/ready/route.ts",
        "src/app/api/health/ready/route.test.ts",
        "scripts/staging-load-evidence.ts",
        "scripts/staging-load-evidence.test.ts",
        "scripts/staging-load-probe.ts",
        "output/staging-load/latest.json",
        "config/slo-alert-policy.json",
        "scripts/check-slo-alert-policy.ts",
        "scripts/check-slo-alert-policy.test.ts",
        "docs/architecture/slo-alert-policy.md",
        "config/incident-response-controls.json",
        "scripts/check-incident-response-policy.ts",
        "scripts/check-incident-response-policy.test.ts",
        "docs/architecture/incident-response-controls.md",
        "src/lib/emergency-controls.ts",
        "src/lib/emergency-controls.test.ts",
        "src/app/api/dogs/search/route.ts",
        "src/app/api/media/sign-upload/route.ts",
        "src/app/api/users/me/export/route.ts",
        "src/app/api/agents/[type]/run/route.ts",
        "src/lib/agent-service.ts",
        "src/lib/dog-card-service.ts",
        ".github/workflows/cloud-run-deploy.yml",
        "scripts/gcp-cloud-run-deploy.ps1",
      ],
      verification: [
        "Independent +73 source-static architecture review: PASS; master 418→491/3315 and overall 696→769/4156 while the release remains blocked",
        "Exact structural mapping: 32/32 infrastructure IDs, 12/12 component-record fields across 25 unique components, and 29/29 trust requirements represented by 16 flow diagrams plus 13 required fields",
        "Fail-closed mutations reject missing mappings, component fields and flows plus unknown/orphan components and orphan evidence IDs",
        "Live Architecture UI returns 200 and renders 32 surfaces, 25 components, 16 flows, the source-static boundary and evidence-unverified warning",
        "Static contract: 30 ordered sections, eight Mermaid diagrams and 70 task entries",
        "Architecture skill validator PASS",
        "ARCH-401 source inventory PASS: 113 models, 100 reviewed migrations and frozen schema/migration SHA-256 digests; deployed catalog parity remains unverified",
        "AU target-policy, database-inventory, request-correlation and log-redaction focused tests PASS",
        "Readiness database work is bounded to a 1s pool wait and 2s transaction timeout, uses a cheap indexed lookup and returns generic no-store failures",
        "Power-outage recovery restored the existing loopback Postgres volume, applied the pending forward-only migration and rebound localhost to the local database; readiness is 200",
        "Comparable local-only smoke improved from overall p95 44,033ms and /feed p95 44,172ms to overall p95 3,733ms and /feed p95 1,998ms with 25/25 HTTP 200; marketplace p95 3,734ms remains performance work and no staging load task is credited",
        "Provisional SLO policy source PASS: 10 critical/noncritical objectives and eight multi-window burn policies; deployment, telemetry bindings, named roster and page delivery remain explicitly unverified",
        "Incident source PASS: exact first-30-minute procedure, 13 controls and seven runbooks; search, export, upload, AI and realtime suppression are repository-implemented, one rollback is manual-documented and seven controls remain unimplemented. Search/export/upload/AI source tests pass; deployment and exercise remain unverified",
        "Emergency deployment source policy PASS: the GitHub workflow and local staging deploy map SEARCH_DISABLED, EXPORT_DISABLED, UPLOAD_DISABLED, AI_DISABLED and REALTIME_BROADCAST_DISABLED through strict false-default inputs; invalid values fail closed, a tagged no-traffic candidate is smoked before exact revision promotion, the temporary tag is removed, and runtime environment values are not logged. No cloud command was run; deployed behavior, incident exercises and external GitHub environment reviewer rules remain unverified",
        "Signup acceptance source PASS: the new user, profile, personal actor and one deduplicated outbox row share the existing system-context transaction; callback failure is fail-closed through the recovery path",
        "Signup worker source PASS: SKIP LOCKED claims, expiring lease ownership, attempt-on-claim accounting, deterministic bounded jitter, generic failure codes and dead-letter transitions pass focused tests without provider calls",
        "Local-only SignupOutbox evidence confirms all three forward-only migrations are applied, RLS and FORCE RLS remain enabled, the system policy and expected indexes remain present, leaseToken is nullable text, and the safe correlationId is nullable varchar(128); no worker runtime, sink idempotency, queue, replay or backlog evidence is claimed",
        "ARCH-206 is in progress: the proxy supplies a bounded request ID and new signup intent preserves it through application, database outbox claim and worker-handler input; no deployed gateway trace, running worker or end-to-end trace query is claimed",
        "Terraform source contract PASS after independent review: provider 7.24.0 is pinned, service-level Sydney/Melbourne scaling is bounded at 10 instances per region across overlapping revisions, Cloud Armor rule descriptions satisfy the 64-character provider limit, provider exceptions are POST-only, CDN remains off and all candidate Armor controls remain preview-only",
        "Terraform 1.14.5 provider-schema validation PASS in the official immutable container image hashicorp/terraform@sha256:96d2bc440714bf2b2f2998ac730fd4612f30746df43fca6f0892b2e2035b11bc: fmt -check -recursive, init -backend=false -lockfile=readonly and validate all passed for hashicorp/google and hashicorp/google-beta 7.24.0",
        "The reviewed .terraform.lock.hcl records Linux and Windows provider checksums; repository CI mounts Terraform source read-only and repeats the dependency-free source contract plus locked provider-schema validation. No plan, apply, state, live-cloud behavior or external branch-protection setting is claimed",
        "RELEASE BLOCKER: the new target account has no deployed architecture resources. The legacy workflow declares a public Sydney-only Supabase path and the green-staging Terraform is not a production foundation. The selected target needs separate public load-balancer ingress with disabled default URLs, IAM-only internal worker endpoints, consistent port/timeouts, numeric secret versions and independently reviewed production IaC before any apply",
        "FINAL DATA-PLANE BLOCKER: AlloyDB is selected but not provisioned or proven. Sydney HA, asynchronous Melbourne secondary/read capacity, emergency promotion with non-zero-RPO exposure, planned switchover, fencing, connection budgets, reconciliation and failback tests remain open",
        "FINAL STORAGE/REALTIME/MEDIA BLOCKER: active Supabase Storage and Realtime runtime paths remain replacement inventory. Cloud Storage, the general AlloyDB outbox, AU Pub/Sub topology, regional WebSocket gateways, per-region application Redis, cursor recovery, and independent Sydney/Melbourne LiveKit cells with room-home routing and per-cell HA Redis must be implemented before the final candidate",
        "FIRST-PARTY REVIEW CORRECTION: the global load balancer selects the closest available region; health-based failover requires Cloud Run readiness/service health plus a warm instance in each region. Outlier detection alone is imperfect and cannot close ARCH-308",
        "MVP SCOPE DECISION: five native iOS/iPadOS/Android requirements remain visible as post-MVP work and no longer enter the web-MVP deployment denominator",
        "Selected target remains explicitly unverified and not deployed; current repository-declared ingress risk is recorded separately",
        "Current go/no-go checklist remains fail-closed with no production claims",
      ],
      nextStep:
        "Complete the provider-neutral storage boundary and Cloud Storage adapter, then build the outbox/Pub/Sub/WebSocket/Redis realtime boundary and the fail-closed regional LiveKit room-home contract while preparing separate source-only production IaC for the selected free-trial project. After explicit spend authority, prove service health, direct-origin denial, AlloyDB compatibility/restore/promotion, WorkOS, Stripe, racing providers and LiveKit before binding the exact candidate and evidence digest. Billing-account upgrade, DNS cutover, live payments and production promotion remain separate human approvals.",
    },
    {
      id: "WORK.DESIGN-LAB.PENDING-WORK-INDEX",
      title: "Complete pending-work index",
      summary:
        "The Requirements workspace now derives one searchable backlog from every screen, master, pre-production and database release check, defaulting to open work and exposing owner, role, screen, dependency, registry and evidence filters without duplicating completion authority.",
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Design Lab orchestration lane",
      updatedAt: "2026-07-14T10:10:00+10:00",
      evidence: [
        "src/components/design-lab-pending-work.ts",
        "src/components/design-lab-pending-work-panel.tsx",
        "src/components/design-lab-pending-work.test.ts",
        "src/components/design-lab-pending-work-panel.test.ts",
        "src/components/design-lab-sync.ts",
        "src/components/demo-experience-screen-map.tsx",
      ],
      verification: [
        "Exact-set test binds the derived index total and completion count to the production release gate and rejects duplicate IDs",
        "Focused logic, UI-contract and lint checks pass",
        "Local Requirements route returns 200 and server-renders the Complete Pending Work panel",
        "Current source-derived gate is intentionally stricter than the stale frozen headline because invalid route evidence contributes zero route credit",
      ],
      nextStep:
        "Independently review the filters and registry drift controls, complete a clean-browser mobile/tablet/desktop interaction check, then recapture the canonical Design Lab route and hydrated evidence under the final source fingerprint.",
    },
    {
      id: "WORK.DESIGN-LAB.SYNC",
      title: "Canonical Design Lab sync audit",
      summary: `A new source-changing wave is active. The fail-closed registry currently derives ${DESIGN_LAB_RELEASE_GATE.completedChecks}/${DESIGN_LAB_RELEASE_GATE.totalChecks}; the prior 777/4160 narrative is stale because its route artifact no longer matches two dynamic thread fixtures. Every canonical browser artifact must be recaptured against one new frozen source fingerprint before any promotion.`,
      status: "in-progress",
      verificationOutcome: "pending",
      owner: "Design Lab orchestration lane",
      updatedAt: "2026-07-14T08:01:43+10:00",
      evidence: [
        "src/components/design-lab-sync.ts",
        "src/components/design-lab-sync.test.ts",
        "src/components/demo-route-audit-evidence.ts",
        "src/components/demo-route-audit-evidence.test.ts",
        "scripts/check-design-lab-sync.ts",
        "scripts/design-lab-source-fingerprint.ts",
        "scripts/design-lab-source-fingerprint.test.ts",
        "output/demo-route-audit/latest.json",
        "output/demo-route-audit/design-lab-user-stories.json",
        "output/demo-route-audit/design-lab-hydrated-stories.json",
      ],
      verification: [
        `Current fail-closed gate: ${DESIGN_LAB_RELEASE_GATE.completedChecks}/${DESIGN_LAB_RELEASE_GATE.totalChecks}; the previous 777/4160 snapshot is retained only as historical context and is not current evidence`,
        "Historical route audit: 90/90 against source digest e8ba3156701a714c876274de22ed5a826250e7491254fcc28b3b2a599185fd59 across 742 files; JSON SHA-256 051ca493a08cf306a1f62aa0e2b94c522bf4f0415de1cc64f578a1ac15d8a612",
        "Design Lab story audit: 12/12 scenarios across 6/6 routes; evidence SHA-256 32621f910ae5619ed7afe8898ed095bd5210e3b86c1c9de6f1aff231da144d5b",
        "Hydrated story audit: 23/23 scenarios with zero mutating requests; evidence SHA-256 022eb35ee089bd6004a1a6c837a0c742ef73631dd53cecd549cda00b18c5c3c1",
        "Product route master evidence independently passed at 82 exact production-enabled registrations after removing one invalid /account/appearance credit",
        "Signup/callback registry re-review passed but intentionally contributes no master or database-operation completion credit",
        "A historical 90/90 run performed during a source change was discarded automatically and never became canonical evidence",
        "Operational contract: after any fingerprinted source change, recapture all three runtime artifacts against one frozen tree before retaining their coverage credit",
      ],
      nextStep:
        "Finish and independently review the three active lanes, freeze the tree, recapture route, HTTP story and both runtime interaction artifacts in order, then rerun the exact sync and release checks before changing the canonical count.",
    },
  ] as const;

export const DESIGN_LAB_DELIVERY_PROGRESS_SUMMARY = Object.freeze({
  total: DESIGN_LAB_DELIVERY_PROGRESS.length,
  verified: DESIGN_LAB_DELIVERY_PROGRESS.filter(
    (item) => item.status === "verified",
  ).length,
  active: DESIGN_LAB_DELIVERY_PROGRESS.filter(
    (item) => item.status === "in-progress",
  ).length,
  waiting: DESIGN_LAB_DELIVERY_PROGRESS.filter(
    (item) => item.status === "waiting",
  ).length,
  blocked: DESIGN_LAB_DELIVERY_PROGRESS.filter(
    (item) => item.status === "blocked",
  ).length,
});
