import type { MarketplaceDogCardData } from "./marketplace-dog-player-card";

export type MarketplaceTemplateListing = MarketplaceDogCardData & {
  artworkSrc: string;
  publicHighlight: string;
};

export const MARKETPLACE_TEMPLATE_LISTINGS: ReadonlyArray<MarketplaceTemplateListing> = [
  {
    listingId: "demo-rocket-card",
    dogId: "cmr0fg5ki00a4ephcaj4sdctc",
    name: "GreyhoundIQ Demo Rocket",
    colourSex: "Black dog",
    starts: 10,
    wins: 3,
    seconds: 2,
    thirds: 2,
    strikeRate: 30,
    prizeMoney: "Demo only",
    pedigree: "Synthetic Design Lab fixture",
    price: "POA",
    description:
      "Synthetic profile reserved for safe Design Lab navigation and interaction testing.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?q=GreyhoundIQ+Demo+Rocket",
    profileHref: "/dogs/cmr0fg5ki00a4ephcaj4sdctc",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc: "/images/marketplace-cards/row-beau-obsidian-aurora.webp",
    publicHighlight: "Synthetic Design Lab fixture",
  },
  {
    listingId: "saanvi-card",
    dogId: "cmr0ktfrx01x1ep20p0y2j8nu",
    name: "Saanvi",
    colourSex: "Black bitch",
    starts: 74,
    wins: 22,
    seconds: 19,
    thirds: 3,
    strikeRate: 29.7,
    prizeMoney: "See profile",
    pedigree: "Superior Panama × Sherbini",
    price: "POA",
    description:
      "Golden Chase winner with public racing and pedigree context.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?category=dogs",
    profileHref: "/dogs/cmr0ktfrx01x1ep20p0y2j8nu",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc: "/images/marketplace-cards/saanvi-golden-chase-crown.webp",
    publicHighlight: "Golden Chase winner",
  },
  {
    listingId: "saahd-card",
    dogId: "cmr0m2myr05frepx490k4jzny",
    name: "Saahd",
    colourSex: "Black dog",
    starts: 70,
    wins: 16,
    seconds: null,
    thirds: null,
    strikeRate: 22.9,
    prizeMoney: "$45,000+",
    pedigree: "Public racing profile",
    price: "POA",
    description:
      "Experienced racer with 70 starts, 16 wins and public form context.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?category=dogs",
    profileHref: "/dogs/cmr0m2myr05frepx490k4jzny",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc: "/images/marketplace-cards/saahd-heritage-chrome.webp",
    publicHighlight: "70-start public record",
  },
  {
    listingId: "aariellas-girl-card",
    dogId: "cmr0fqxt403c0epzs7bhmhr6m",
    name: "Aariella's Girl",
    colourSex: "Red fawn bitch",
    starts: 37,
    wins: 13,
    seconds: 3,
    thirds: 8,
    strikeRate: 35.1,
    prizeMoney: "$48,822",
    pedigree: "Feral Franky × Drink Moet",
    price: "POA",
    description:
      "Public racing record through 29 June 2026 with pedigree and connections.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?category=dogs",
    profileHref: "/dogs/cmr0fqxt403c0epzs7bhmhr6m",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc:
      "/images/marketplace-cards/aariellas-girl-ruby-velocity.webp",
    publicHighlight: "Career snapshot to 29 June 2026",
  },
  {
    listingId: "ohara-card",
    dogId: "cmr0lmivq02xaepmk8y7450p9",
    name: "O'hara",
    colourSex: "Racing bitch",
    starts: 75,
    wins: 12,
    seconds: 11,
    thirds: 14,
    strikeRate: 16,
    prizeMoney: "$25,990",
    pedigree: "Fabregas × Stunning Chloe",
    price: "POA",
    description:
      "Richmond Riches semi-finalist with public pedigree context.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?category=dogs",
    profileHref: "/dogs/cmr0lmivq02xaepmk8y7450p9",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc: "/images/marketplace-cards/ohara-noir-art-deco.webp",
    publicHighlight: "Richmond Riches semi-finalist",
  },
  {
    listingId: "aaron-alpaca-card",
    dogId: "cmr0ltvp104coepykf9irul0r",
    name: "Aaron Alpaca",
    colourSex: "Black bitch",
    starts: 67,
    wins: 11,
    seconds: null,
    thirds: null,
    strikeRate: 16.4,
    prizeMoney: "$17,945",
    pedigree: "Dyna Villa × Cheekers",
    price: "POA",
    description:
      "Public career and pedigree profile with 67 starts and 11 wins.",
    listingLabel: "Marketplace",
    listingHref: "/marketplace?category=dogs",
    profileHref: "/dogs/cmr0ltvp104coepykf9irul0r",
    seller: {
      displayName: "Seller details on listing",
      verified: false,
      region: "Australia",
      responseTime: "Enquiries in Pulse",
    },
    artworkSrc:
      "/images/marketplace-cards/aaron-alpaca-copper-circuit.webp",
    publicHighlight: "67-start public career",
  },
];
