/**
 * Atomic extraction of the product-wide GreyhoundIQ and Design Lab master prompt.
 *
 * IDs are durable contracts. Never renumber or reuse an ID; append a new key when
 * the prompt changes. A requirement being present here is not evidence that the
 * product requirement has been completed.
 */

export const PRODUCT_MASTER_PROMPT_ID =
  "greyhoundiq.product-design-lab-master.2026-07-13" as const;

export type ProductMasterRequirementStatus =
  | "not-started"
  | "captured"
  | "verified"
  | "tested"
  | "blocked"
  | "excluded";

export type ProductMasterRequirement = {
  id: string;
  prompt: typeof PRODUCT_MASTER_PROMPT_ID;
  section: string;
  requirement: string;
  status: ProductMasterRequirementStatus;
  evidence: readonly string[];
  owner: string;
  releaseBlocking: boolean;
};

type RequirementSeed = readonly [
  key: string,
  requirement: string,
  releaseBlocking?: boolean,
];

const OWNER = "AI Kick Start delivery team";

function requirements(
  section: string,
  prefix: string,
  seeds: readonly RequirementSeed[],
): ProductMasterRequirement[] {
  return seeds.map(([key, requirement, releaseBlocking = true]) => ({
    id: `${prefix}.${key}`,
    prompt: PRODUCT_MASTER_PROMPT_ID,
    section,
    requirement,
    status: "not-started",
    evidence: [],
    owner: OWNER,
    releaseBlocking,
  }));
}

export const PRODUCT_MASTER_REQUIRED_SECTIONS = [
  "outcomes",
  "discovery.audit-sources",
  "discovery.production-crawl",
  "discovery.route-registry",
  "stories.contract",
  "stories.atomic-capabilities",
  "actions.controls",
  "actions.behaviour",
  "forms.contract",
  "fields.contract",
  "onboarding.product-surfaces",
  "onboarding.behaviour",
  "onboarding.persistence",
  "onboarding.roles",
  "onboarding.access-explanations",
  "onboarding.targeting",
  "onboarding.devices",
  "onboarding.mobile-safety",
  "onboarding.accessibility",
  "onboarding.analytics",
  "onboarding.management",
  "racing.production-structures",
  "racing.fixtures",
  "routes.public",
  "routes.racing",
  "routes.community",
  "routes.marketplace",
  "routes.account",
  "routes.administration",
  "routes.ai-tools",
  "design-lab.routes",
  "design-lab.selectors",
  "design-lab.states",
  "design-lab.url-state",
  "design-lab.safety",
  "design-lab.inspector",
  "system-states",
  "global.functionality",
  "global.accessibility",
  "global.responsive-widths",
  "global.responsive-behaviour",
  "global.privacy-security",
  "global.data-integrity",
  "outputs",
  "documentation.recommended-paths",
  "verification.automated-gates",
  "verification.test-levels",
  "verification.e2e-journeys",
  "completion.evidence",
  "completion.prohibited-placeholders",
  "completion.user-understanding",
] as const;

const outcomeRequirements = requirements("outcomes", "OUT", [
  ["route-screen-inventory", "Produce a complete route and screen inventory."],
  ["user-story-inventory", "Produce a complete user-story inventory."],
  ["action-inventory", "Produce a complete action and interaction inventory."],
  ["form-field-registry", "Produce a complete form and field registry."],
  ["permissions-matrix", "Produce a complete role, tier, and permissions matrix."],
  ["state-matrix", "Produce a complete state matrix for every screen and component."],
  ["design-lab-parity", "Represent every production-facing experience in the Design Lab."],
  ["onboarding", "Provide first-run and contextual onboarding across the entire product."],
  ["no-dead-or-fake-ui", "Leave no dead links, fake controls, placeholder actions, or undocumented journeys."],
  ["automated-evidence", "Provide automated evidence that every registered route, action, and state was tested."],
]);

const auditSourceRequirements = requirements(
  "discovery.audit-sources",
  "DISC.SRC",
  [
    ["route-definitions", "Inspect all application route definitions."],
    ["next-route-directories", "Inspect Next.js route directories."],
    ["route-groups", "Inspect Next.js route groups."],
    ["layouts", "Inspect layouts."],
    ["nested-layouts", "Inspect nested layouts."],
    ["parallel-routes", "Inspect parallel routes."],
    ["navigation-menus", "Inspect navigation menus."],
    ["desktop-navigation", "Inspect desktop navigation."],
    ["mobile-navigation", "Inspect mobile navigation."],
    ["tablet-navigation", "Inspect tablet navigation."],
    ["footer-navigation", "Inspect footer navigation."],
    ["account-navigation", "Inspect account navigation."],
    ["admin-navigation", "Inspect administration navigation."],
    ["context-menus", "Inspect context menus."],
    ["dropdown-menus", "Inspect dropdown menus."],
    ["tabs", "Inspect tabs."],
    ["sub-tabs", "Inspect sub-tabs."],
    ["navigation-cards", "Inspect cards that navigate."],
    ["search-result-links", "Inspect search-result links."],
    ["breadcrumbs", "Inspect breadcrumbs."],
    ["pagination-links", "Inspect pagination links."],
    ["modals", "Inspect modals."],
    ["dialogs", "Inspect dialogs."],
    ["drawers", "Inspect drawers."],
    ["popovers", "Inspect popovers."],
    ["tooltips", "Inspect tooltips."],
    ["command-palettes", "Inspect command palettes."],
    ["empty-state-actions", "Inspect empty-state calls to action."],
    ["error-state-actions", "Inspect error-state calls to action."],
    ["auth-redirects", "Inspect authentication redirects."],
    ["billing-return-routes", "Inspect billing return routes."],
    ["invitation-links", "Inspect invitation links."],
    ["email-links", "Inspect email links."],
    ["notification-links", "Inspect notification links."],
    ["deep-links", "Inspect deep links."],
    ["dynamic-routes", "Inspect dynamic routes."],
    ["api-redirects", "Inspect API-triggered redirects."],
    ["feature-flagged-routes", "Inspect feature-flagged routes."],
    ["role-gated-routes", "Inspect role-gated routes."],
    ["tier-gated-routes", "Inspect subscription-tier-gated routes."],
    ["automated-tests", "Inspect existing automated tests."],
    ["design-lab-routes", "Inspect existing Design Lab routes."],
    ["design-lab-fixtures", "Inspect existing Design Lab fixture data."],
    ["production-pages", "Inspect all pages available on greyhoundsiq.com.au."],
    ["database-models", "Discover product surface implied by database models."],
    ["api-handlers", "Discover product surface implied by API handlers."],
    ["authentication-flows", "Discover product surface implied by authentication flows."],
    ["billing-flows", "Discover product surface implied by billing flows."],
    ["feature-flags", "Discover product surface implied by feature flags."],
  ],
);

const productionCrawlRequirements = requirements(
  "discovery.production-crawl",
  "DISC.CRAWL",
  [
    ["source-route", "Record the source route for every discovered production link or action."],
    ["source-component", "Record the source component for every discovered production link or action."],
    ["visible-label", "Record the visible label for every discovered production link or action."],
    ["accessible-label", "Record the accessible label for every discovered production link or action."],
    ["destination", "Record the destination for every discovered production link or action."],
    ["http-status", "Record the HTTP status for every discovered production link."],
    ["redirect-chain", "Record the complete redirect chain for every discovered production link."],
    ["authentication", "Record the authentication requirement for every discovered production link or action."],
    ["role", "Record the role requirement for every discovered production link or action."],
    ["subscription", "Record the subscription requirement for every discovered production link or action."],
    ["dynamic-parameters", "Record dynamic parameters for every discovered production link."],
    ["query-parameters", "Record query parameters for every discovered production link."],
    ["target-context", "Record whether each destination opens in the current tab or a new tab."],
    ["local-parity", "Record whether each production destination exists in the local application."],
    ["design-lab-parity", "Record whether each production destination exists in the Design Lab."],
    ["state-coverage", "Record whether each destination has complete loading, empty, and error states."],
    ["canonical-host", "Check canonical and non-canonical host variants and record inconsistent behaviour."],
    ["breakpoint-links", "Include links visible only at particular responsive breakpoints."],
    ["non-nav-links", "Include footer, legal, login-return, dynamic-record, email, and notification links rather than relying on sitemap or top navigation."],
  ],
);

const routeRegistryRequirements = requirements(
  "discovery.route-registry",
  "REG.ROUTE",
  [
    ["single-source", "Maintain one machine-readable route and screen registry without conflicting duplicates."],
    ["drives-navigation", "Use the registry as a source for application navigation."],
    ["drives-design-lab", "Use the registry as a source for Design Lab navigation."],
    ["drives-onboarding", "Use the registry as a source for onboarding tours."],
    ["drives-tests", "Use the registry as a source for automated route testing."],
    ["drives-access", "Use the registry as a source for role and tier access."],
    ["drives-fixtures", "Use the registry as a source for screen-state fixtures."],
    ["drives-docs", "Use the registry as a source for documentation coverage."],
    ["field-id", "Give every screen contract a stable id."],
    ["field-route", "Record the concrete route in every screen contract."],
    ["field-route-pattern", "Record the route pattern when a screen is dynamic."],
    ["field-title", "Record the screen title."],
    ["field-product-area", "Record the screen product area."],
    ["field-description", "Record a meaningful screen description."],
    ["field-actors", "Record all actors for the screen."],
    ["field-authentication", "Record whether authentication is public, optional, or required."],
    ["field-roles", "Record allowed roles."],
    ["field-tiers", "Record allowed subscription tiers."],
    ["field-feature-flags", "Record relevant feature flags."],
    ["field-dynamic-parameters", "Record all dynamic parameters."],
    ["field-query-parameters", "Record all query parameters."],
    ["field-entry-points", "Record every meaningful entry point."],
    ["field-primary-actions", "Record primary actions."],
    ["field-secondary-actions", "Record secondary actions."],
    ["field-forms", "Record forms used by the screen."],
    ["field-data-dependencies", "Record data dependencies."],
    ["field-supported-states", "Record supported screen states."],
    ["field-tour", "Record the onboarding tour id where applicable."],
    ["field-fixtures", "Record Design Lab fixture ids."],
    ["field-noindex", "Record whether the screen is noindex."],
    ["field-production-enabled", "Record whether the screen is production-enabled."],
  ],
);

const storyContractRequirements = requirements("stories.contract", "STORY.FIELD", [
  ["actor", "Every user story records the actor."],
  ["goal", "Every user story records the goal."],
  ["value", "Every user story records the reason or value."],
  ["entry-points", "Every user story records entry points."],
  ["preconditions", "Every user story records preconditions."],
  ["permissions", "Every user story records permissions."],
  ["subscription", "Every user story records subscription requirements."],
  ["feature-flags", "Every user story records feature flags."],
  ["required-data", "Every user story records required data."],
  ["happy-path", "Every user story records the primary happy path."],
  ["alternative-paths", "Every user story records alternative paths."],
  ["failure-paths", "Every user story records failure paths."],
  ["blocked-private-paths", "Every user story records blocked and private paths."],
  ["actions", "Every user story records available actions."],
  ["forms", "Every user story records forms involved."],
  ["fields", "Every user story records fields involved."],
  ["validation", "Every user story records validation rules."],
  ["loading", "Every user story records loading behaviour."],
  ["empty", "Every user story records empty behaviour."],
  ["success", "Every user story records success feedback."],
  ["recoverable-error", "Every user story records recoverable-error feedback."],
  ["navigation-result", "Every user story records the navigation result."],
  ["analytics-audit", "Every user story records analytics and audit events."],
  ["onboarding", "Every user story records onboarding guidance."],
  ["accessibility", "Every user story records accessibility requirements."],
  ["mobile", "Every user story records mobile behaviour."],
  ["fixtures", "Every user story records Design Lab fixtures."],
  ["tests", "Every user story records automated test coverage."],
]);

const storyCapabilityRequirements = requirements(
  "stories.atomic-capabilities",
  "STORY.CAP",
  [
    ["view", "Create independently testable viewing stories."],
    ["search", "Create independently testable searching stories."],
    ["filter", "Create independently testable filtering stories."],
    ["sort", "Create independently testable sorting stories."],
    ["create", "Create independently testable creation stories."],
    ["edit", "Create independently testable editing stories."],
    ["delete", "Create independently testable deletion stories."],
    ["save", "Create independently testable saving stories."],
    ["unsave", "Create independently testable unsaving stories."],
    ["publish", "Create independently testable publishing stories."],
    ["unpublish", "Create independently testable unpublishing stories."],
    ["comment", "Create independently testable commenting stories."],
    ["react", "Create independently testable reaction stories."],
    ["share", "Create independently testable sharing stories."],
    ["report", "Create independently testable reporting stories."],
    ["block", "Create independently testable blocking stories."],
    ["join", "Create independently testable joining stories."],
    ["leave", "Create independently testable leaving stories."],
    ["invite", "Create independently testable invitation stories."],
    ["accept", "Create independently testable acceptance stories."],
    ["decline", "Create independently testable decline stories."],
    ["message", "Create independently testable messaging stories."],
    ["call", "Create independently testable calling stories."],
    ["upload", "Create independently testable upload stories."],
    ["download", "Create independently testable download stories."],
    ["export", "Create independently testable export stories."],
    ["subscribe", "Create independently testable subscription stories."],
    ["cancel", "Create independently testable cancellation stories."],
    ["retry", "Create independently testable retry stories."],
    ["recover", "Create independently testable recovery stories."],
    ["auth-return", "Create independently testable authentication-return stories."],
    ["billing-return", "Create independently testable billing-return stories."],
  ],
);

const actionControlRequirements = requirements("actions.controls", "ACTION.TYPE", [
  ["buttons", "Catalogue every button."],
  ["links", "Catalogue every link."],
  ["icon-buttons", "Catalogue every icon button."],
  ["cards", "Catalogue every interactive card."],
  ["tabs", "Catalogue every tab."],
  ["accordions", "Catalogue every accordion control."],
  ["filters", "Catalogue every filter."],
  ["sort", "Catalogue every sort control."],
  ["dates", "Catalogue every date selector."],
  ["search", "Catalogue every search field."],
  ["pagination", "Catalogue every pagination control."],
  ["menus", "Catalogue every menu."],
  ["toggles", "Catalogue every toggle."],
  ["checkboxes", "Catalogue every checkbox."],
  ["radios", "Catalogue every radio control."],
  ["selects", "Catalogue every select control."],
  ["sliders", "Catalogue every slider."],
  ["uploads", "Catalogue every file upload."],
  ["media", "Catalogue every media control."],
  ["likes", "Catalogue every like control."],
  ["saves", "Catalogue every save control."],
  ["shares", "Catalogue every share control."],
  ["comments", "Catalogue every comment control."],
  ["messages", "Catalogue every message control."],
  ["calls", "Catalogue every call control."],
  ["video", "Catalogue every video control."],
  ["notifications", "Catalogue every notification control."],
  ["billing", "Catalogue every billing control."],
  ["admin", "Catalogue every administrative mutation."],
]);

const actionBehaviourRequirements = requirements(
  "actions.behaviour",
  "ACTION.BEHAVIOUR",
  [
    ["purpose", "Every interactive control has a clear purpose."],
    ["real-result", "Every interactive control has a real result."],
    ["feedback", "Every interactive control provides immediate feedback."],
    ["keyboard", "Every interactive control supports keyboard use."],
    ["focus", "Every interactive control has visible focus treatment."],
    ["disabled", "Every interactive control defines disabled behaviour."],
    ["pending", "Every interactive control defines pending behaviour."],
    ["success", "Every interactive control defines success behaviour."],
    ["failure", "Every interactive control defines recoverable failure behaviour."],
    ["permission-denied", "Every relevant control defines permission-denied behaviour."],
    ["design-lab", "Every interactive control has Design Lab coverage."],
    ["tests", "Every interactive control has automated interaction coverage."],
    ["no-fake-controls", "No control may look interactive while doing nothing."],
  ],
);

const formContractRequirements = requirements("forms.contract", "FORM.FIELD", [
  ["id", "Record a stable form id."],
  ["route", "Record the route containing the form."],
  ["story", "Record the form's user story."],
  ["actor", "Record the form actor."],
  ["purpose", "Record the form purpose."],
  ["destination", "Record the submission destination."],
  ["mutation", "Record the mutation performed."],
  ["authentication", "Record the authentication requirement."],
  ["ownership", "Record the ownership requirement."],
  ["role", "Record the role requirement."],
  ["tier", "Record the tier requirement."],
  ["update-strategy", "Record whether updates are optimistic or pessimistic."],
  ["pending", "Record pending behaviour."],
  ["duplicate-prevention", "Record duplicate-submission prevention."],
  ["success", "Record the success result."],
  ["failure", "Record the failure result."],
  ["audit", "Record the audit event."],
  ["analytics", "Record the analytics event."],
]);

const fieldContractRequirements = requirements("fields.contract", "FIELD.FIELD", [
  ["name", "Record each field name."],
  ["visible-label", "Record each field's visible label."],
  ["accessible-label", "Record each field's accessible label."],
  ["input-type", "Record each field's input type."],
  ["data-type", "Record each field's data type."],
  ["required", "Record whether each field is required or optional."],
  ["default", "Record each field's default value."],
  ["placeholder", "Record each field's placeholder."],
  ["help", "Record each field's help text."],
  ["character-limits", "Record character limits."],
  ["numeric-limits", "Record minimum and maximum values."],
  ["file-types", "Record accepted file types."],
  ["file-sizes", "Record accepted file sizes."],
  ["validation", "Record validation rules."],
  ["sanitisation", "Record sanitisation rules."],
  ["error", "Record the user-facing error message."],
  ["source", "Record the field data source."],
  ["persistence", "Record the persistence destination."],
  ["privacy", "Record the privacy classification."],
  ["onboarding", "Record whether the field appears in onboarding."],
  ["mobile-input", "Record mobile keyboard and input mode."],
  ["autofill", "Record autofill behaviour."],
  ["read-only-disabled", "Record read-only and disabled states."],
  ["conditional-visibility", "Record conditional visibility rules."],
  ["hidden", "Include hidden fields."],
  ["generated-ids", "Include generated identifiers."],
  ["consent", "Include consent fields."],
  ["media-metadata", "Include media metadata fields."],
  ["disclosures", "Include disclosure fields."],
  ["billing-intent", "Include billing-intent fields."],
  ["dependent-fields", "Include fields shown only after another selection."],
]);

const onboardingSurfaceRequirements = requirements(
  "onboarding.product-surfaces",
  "ONBOARD.SURFACE",
  [
    ["global-welcome", "Provide a global welcome flow."],
    ["intent-selection", "Provide role or intent selection."],
    ["product-area-tours", "Provide product-area tours."],
    ["page-walkthroughs", "Provide page-level walkthroughs."],
    ["section-explanations", "Provide section-level explanations."],
    ["field-help", "Provide field-level assistance."],
    ["help-icons", "Provide contextual help icons."],
    ["inline-examples", "Provide inline examples."],
    ["empty-guidance", "Provide empty-state guidance."],
    ["permission-tier-explanations", "Explain permissions and tier gates contextually."],
    ["what-can-i-do", "Provide 'What can I do here?' assistance."],
    ["why-unavailable", "Provide 'Why is this unavailable?' assistance."],
    ["progressive-not-generic", "Use progressive contextual onboarding rather than one oversized generic modal."],
  ],
);

const onboardingBehaviourRequirements = requirements(
  "onboarding.behaviour",
  "ONBOARD.BEHAVIOUR",
  [
    ["start", "Support starting a tour."],
    ["next", "Support moving to the next step."],
    ["back", "Support moving to the previous step."],
    ["skip-step", "Support skipping the current step."],
    ["skip-tour", "Support skipping the current tour."],
    ["dismiss", "Support dismissing onboarding."],
    ["resume", "Support resuming later."],
    ["restart", "Support restarting a tour."],
    ["reset-all", "Support resetting all tours."],
    ["complete", "Support marking a tour complete."],
    ["do-not-show", "Support 'Do not show this again'."],
    ["manual-help", "Support opening contextual help manually."],
    ["search-help", "Support searching help topics."],
    ["support-docs", "Link to relevant support documentation."],
  ],
);

const onboardingPersistenceRequirements = requirements(
  "onboarding.persistence",
  "ONBOARD.PERSIST",
  [
    ["user", "Persist onboarding progress by user."],
    ["anonymous-session", "Persist onboarding for an anonymous browser session where appropriate."],
    ["tour-id", "Persist onboarding progress by tour id."],
    ["tour-version", "Persist onboarding progress by tour version."],
    ["route", "Persist onboarding progress by route."],
    ["product-area", "Persist onboarding progress by product area."],
    ["role", "Persist onboarding progress by role."],
    ["tier", "Persist onboarding progress by subscription tier."],
    ["completion", "Persist onboarding completion state."],
    ["version-bump", "Increment a tour version after material changes without resetting unrelated tours."],
  ],
);

const onboardingRoleRequirements = requirements("onboarding.roles", "ONBOARD.ROLE", [
  ["visitor", "Provide a public visitor onboarding path."],
  ["new-member", "Provide a newly authenticated member onboarding path."],
  ["racing-user", "Provide a racing-data user onboarding path."],
  ["owner", "Provide a greyhound owner onboarding path."],
  ["breeder", "Provide a breeder onboarding path."],
  ["trainer", "Provide a trainer onboarding path."],
  ["buyer", "Provide a marketplace buyer onboarding path."],
  ["seller", "Provide a marketplace seller onboarding path."],
  ["community", "Provide a community participant onboarding path."],
  ["page-manager", "Provide a page or business manager onboarding path."],
  ["team-member", "Provide a team member onboarding path."],
  ["support", "Provide a support operator onboarding path."],
  ["moderator", "Provide a moderator onboarding path."],
  ["administrator", "Provide an administrator onboarding path."],
  ["ai-user", "Provide an AI tools user onboarding path."],
  ["accessible-only", "Show guidance only for features the current user can access."],
]);

const onboardingAccessRequirements = requirements(
  "onboarding.access-explanations",
  "ONBOARD.ACCESS",
  [
    ["why", "Explain why a feature is unavailable."],
    ["authentication", "Explain when authentication is required."],
    ["subscription", "Explain when another subscription is required."],
    ["role", "Explain when an invitation or role is required."],
    ["next-action", "Explain the next permitted action."],
    ["no-leak", "Do not expose inaccessible role names, data, or controls."],
  ],
);

const onboardingTargetingRequirements = requirements(
  "onboarding.targeting",
  "ONBOARD.TARGET",
  [
    ["semantic-identifiers", "Anchor tours to stable semantic identifiers rather than fragile CSS selectors."],
    ["present", "Handle a target element that is present."],
    ["loading", "Handle a target element that is not yet loaded."],
    ["breakpoint-hidden", "Handle a target hidden by the current breakpoint."],
    ["scroll-container", "Handle a target inside a scroll container."],
    ["tab", "Handle a target inside a tab."],
    ["modal", "Handle a target inside a modal."],
    ["feature-flag", "Handle a target behind a feature flag."],
    ["role", "Handle a target unavailable for the current role."],
    ["missing-data", "Handle a target whose dynamic data is missing."],
    ["route-change", "Handle a route change during a tour."],
    ["fallback", "Skip, substitute, or explain an unavailable target without crashing or trapping the user."],
  ],
);

const onboardingDeviceRequirements = requirements("onboarding.devices", "ONBOARD.DEVICE", [
  ["small-phone", "Support onboarding on small phones."],
  ["large-phone", "Support onboarding on large phones."],
  ["foldable", "Support foldable-width layouts where supported."],
  ["tablet-portrait", "Support portrait tablets."],
  ["tablet-landscape", "Support landscape tablets."],
  ["laptop", "Support laptop screens."],
  ["desktop", "Support desktop screens."],
  ["wide-desktop", "Support wide desktop screens."],
]);

const onboardingMobileSafetyRequirements = requirements(
  "onboarding.mobile-safety",
  "ONBOARD.MOBILE",
  [
    ["onscreen", "Keep onboarding popovers on-screen."],
    ["target-visible", "Do not cover the control being explained."],
    ["navigation", "Do not block required navigation."],
    ["overflow", "Do not create horizontal overflow."],
    ["scrolling", "Do not trap scrolling."],
    ["fixed-navigation", "Do not hide required actions beneath fixed navigation."],
    ["keyboard", "Do not conflict with the mobile keyboard."],
    ["mobile-pattern", "Use bottom sheets or full-width guidance when popovers are unsuitable."],
  ],
);

const onboardingAccessibilityRequirements = requirements(
  "onboarding.accessibility",
  "ONBOARD.A11Y",
  [
    ["semantics", "Use correct dialog and popover semantics."],
    ["announcement", "Announce the step title and step count."],
    ["keyboard", "Support keyboard navigation."],
    ["escape", "Handle Escape."],
    ["focus", "Provide visible focus."],
    ["focus-restoration", "Restore focus after onboarding closes."],
    ["screen-reader", "Provide screen-reader instructions."],
    ["reduced-motion", "Respect reduced-motion preferences."],
    ["contrast", "Provide sufficient contrast."],
    ["no-hover-only", "Do not rely on hover-only information."],
    ["no-timeout", "Do not force a timeout."],
    ["touch-target", "Use at least 44px primary touch targets."],
    ["no-trap", "Never trap a user in onboarding."],
  ],
);

const onboardingAnalyticsRequirements = requirements(
  "onboarding.analytics",
  "ONBOARD.ANALYTICS",
  [
    ["tour-started", "Record a privacy-safe tour-started event."],
    ["step-viewed", "Record a privacy-safe step-viewed event."],
    ["step-skipped", "Record a privacy-safe step-skipped event."],
    ["tour-dismissed", "Record a privacy-safe tour-dismissed event."],
    ["tour-completed", "Record a privacy-safe tour-completed event."],
    ["tour-restarted", "Record a privacy-safe tour-restarted event."],
    ["help-opened", "Record a privacy-safe help-topic-opened event."],
    ["upgrade-viewed", "Record a privacy-safe upgrade-explanation-viewed event."],
    ["support-selected", "Record a privacy-safe support-link-selected event."],
    ["no-sensitive-values", "Do not record sensitive form values or private user content."],
  ],
);

const onboardingManagementRequirements = requirements(
  "onboarding.management",
  "ONBOARD.MANAGE",
  [
    ["available-tours", "Let users view available tours from an account or help area."],
    ["restart", "Let users restart a tour from an account or help area."],
    ["reset", "Let users reset onboarding from an account or help area."],
    ["search", "Let users search help from an account or help area."],
    ["completed", "Let users view recently completed tours."],
    ["support", "Let users open support."],
    ["design-lab-previews", "Preview every onboarding step, role, device size, and unavailable-target fallback in the Design Lab."],
  ],
);

const racingProductionRequirements = requirements(
  "racing.production-structures",
  "RACING.STRUCT",
  [
    ["hero", "Capture the reusable public hero and calls-to-action contract."],
    ["todays-races", "Capture today's races."],
    ["meeting-cards", "Capture meeting cards."],
    ["race-cards", "Capture race cards."],
    ["live", "Capture live race states."],
    ["upcoming", "Capture upcoming race states."],
    ["resulted", "Capture resulted race states."],
    ["replay", "Capture replay-available states."],
    ["date-navigation", "Capture date navigation."],
    ["state-filters", "Capture state filters."],
    ["status-filters", "Capture status filters."],
    ["sort", "Capture sort controls."],
    ["search", "Capture search."],
    ["track-groupings", "Capture track groupings."],
    ["runner-counts", "Capture runner counts."],
    ["result-counts", "Capture result counts."],
    ["video-counts", "Capture video counts."],
    ["dog-profiles", "Capture dog profiles."],
    ["track-profiles", "Capture track profiles."],
    ["race-details", "Capture race details."],
    ["results", "Capture results."],
    ["breeding", "Capture breeding context."],
    ["statistics", "Capture statistics."],
    ["box-win-rate", "Capture box win-rate presentation."],
    ["trainer-leaderboards", "Capture trainer leaderboards."],
    ["track-records", "Capture track records."],
    ["source-disclosure", "Capture data-source disclosures."],
    ["update-disclosure", "Capture update-time disclosures."],
    ["responsible-use", "Capture responsible-use notices."],
    ["schema", "Capture each production data presentation's schema and columns."],
    ["layout", "Capture each production data presentation's filters, layouts, and interactions."],
    ["missing-data", "Capture missing-data behaviour."],
    ["typed-snapshot", "Use typed fixtures or a read-only snapshot rather than hard-coded transient production statistics."],
  ],
);

const racingFixtureRequirements = requirements("racing.fixtures", "RACING.FIX", [
  ["complete", "Create a complete-record fixture."],
  ["partial", "Create a partial-record fixture."],
  ["missing", "Create a missing-values fixture."],
  ["zero", "Create a zero-values fixture."],
  ["delayed", "Create a delayed-feed fixture."],
  ["corrected", "Create a corrected-record fixture."],
  ["no-results", "Create a no-results fixture."],
  ["source-conflict", "Create a duplicate-source-conflict fixture."],
  ["suspended", "Create a suspended-race fixture."],
  ["abandoned", "Create an abandoned-race fixture."],
  ["replay-unavailable", "Create an unavailable-replay fixture."],
  ["unknown-dog", "Create an unknown-dog fixture."],
  ["unknown-track", "Create an unknown-track fixture."],
  ["missing-breeding", "Create a missing-breeding-data fixture."],
  ["source-outage", "Create a data-source-outage fixture."],
  ["safe-errors", "Never display stack traces, raw provider errors, database identifiers, or secrets."],
]);

const publicRouteRequirements = requirements("routes.public", "ROUTE.PUBLIC", [
  ["home", "Register and cover /."],
  ["about", "Register and cover /about."],
  ["contact", "Register and cover /contact."],
  ["pricing", "Register and cover /pricing."],
  ["privacy", "Register and cover /privacy."],
  ["terms", "Register and cover /terms."],
  ["responsible-use", "Register and cover /responsible-use."],
  ["sign-in", "Register and cover /sign-in."],
  ["callback", "Register and cover /callback."],
  ["auth-loading", "Represent authentication redirect loading."],
  ["auth-success", "Represent authentication success."],
  ["auth-cancelled", "Represent authentication cancellation."],
  ["auth-expired", "Represent expired authentication."],
  ["auth-provider-failure", "Represent authentication-provider failure."],
  ["safe-return", "Provide a validated internal post-authentication return."],
  ["not-found", "Provide a public 404."],
  ["recoverable-error", "Provide a public recoverable-error state."],
  ["maintenance", "Provide a public maintenance state."],
  ["offline", "Provide a public offline state where supported."],
  ["legal-public", "Keep public legal pages available without authentication."],
  ["real-cta", "Make every primary public call to action lead to a real next step."],
  ["no-open-redirect", "Prevent open redirects during sign-in and callback handling."],
  ["auth-retry", "Offer a safe retry after an authentication callback failure."],
  ["pricing-truth", "Keep plans and entitlements shown by pricing accurate."],
  ["payment-proof", "Never treat query parameters as payment proof."],
  ["a11y", "Preserve keyboard focus, semantic labels, and 44px primary touch targets."],
  ["responsive", "Avoid horizontal overflow at phone, tablet, and desktop breakpoints."],
]);

const racingRouteRequirements = requirements("routes.racing", "ROUTE.RACING", [
  ["breeding", "Register and cover /breeding."],
  ["dogs", "Register and cover /dogs."],
  ["dog-detail", "Register and cover /dogs/[id]."],
  ["races", "Register and cover /races."],
  ["race-detail", "Register and cover /races/[id]."],
  ["results", "Register and cover /results."],
  ["statistics", "Register and cover /statistics."],
  ["tracks", "Register and cover /tracks."],
  ["track-detail", "Register and cover /tracks/[id]."],
  ["search-race", "Support search by race."],
  ["search-meeting", "Support search by meeting."],
  ["search-track", "Support search by track."],
  ["search-dog", "Support search by dog."],
  ["search-date", "Support search by date."],
  ["search-distance", "Support search by distance."],
  ["search-grade", "Support search by grade."],
  ["search-state", "Support search by state."],
  ["search-status", "Support search by status."],
  ["date-navigation", "Support date navigation."],
  ["filter-live", "Support a live filter."],
  ["filter-upcoming", "Support an upcoming filter."],
  ["filter-resulted", "Support a resulted filter."],
  ["filter-replay", "Support a replay filter."],
  ["sort-time", "Support sort by race time."],
  ["sort-relevance", "Support sort by relevance."],
  ["open-meeting", "Support opening a meeting."],
  ["open-race", "Support opening a race."],
  ["open-dog", "Support opening a dog."],
  ["open-track", "Support opening a track."],
  ["open-replay", "Support opening a replay."],
  ["previous-next", "Support moving between previous and next races."],
  ["return-context", "Return to the original filtered list."],
  ["preserve-context", "Preserve search, filters, date, and scroll context."],
  ["delayed-records", "Render incomplete or delayed records safely."],
  ["meaningful-result", "Make filters, cards, and detail links yield a result or clear no-data state."],
  ["safe-missing", "Handle missing dynamic records without exposing internals."],
  ["status-distinction", "Visually distinguish live, upcoming, completed, abandoned, postponed, and replay states."],
  ["validate-id", "Validate race, dog, and track identifiers."],
  ["source-completeness", "Identify unavailable or incomplete statistics source data."],
  ["zero-vs-missing", "Do not confuse zero with missing data."],
  ["mobile-tables", "Keep racing tables usable on phones."],
  ["row-a11y", "Make rows and cards navigable by keyboard and screen reader."],
  ["no-invention", "Do not invent racing statistics."],
]);

const communityRouteRequirements = requirements(
  "routes.community",
  "ROUTE.COMMUNITY",
  [
    ["discover", "Register and cover /discover."],
    ["feed", "Register and cover /feed."],
    ["forum", "Register and cover /forum."],
    ["forum-category", "Register and cover /forum/[slug]."],
    ["forum-thread", "Register and cover /forum/threads/[id]."],
    ["groups", "Register and cover /groups."],
    ["group-detail", "Register and cover /groups/[slug]."],
    ["group-thread", "Register and cover /groups/threads/[id]."],
    ["messages", "Register and cover /messages."],
    ["message-detail", "Register and cover /messages/[id]."],
    ["message-friends", "Register and cover /messages/friends."],
    ["profile", "Register and cover /p/[handle]."],
    ["pulse", "Register and cover /pulse."],
    ["pulse-detail", "Register and cover /pulse/[id]."],
    ["pulse-friends", "Register and cover /pulse/friends."],
    ["search-people", "Support searching people."],
    ["search-pages", "Support searching pages."],
    ["search-businesses", "Support searching businesses."],
    ["search-greyhounds", "Support searching greyhounds."],
    ["public-profile", "Support viewing a public profile."],
    ["private-profile", "Represent a private profile safely."],
    ["friend-send", "Support sending a friend request."],
    ["friend-accept", "Support accepting a friend request."],
    ["friend-decline", "Support declining a friend request."],
    ["friend-cancel", "Support cancelling a friend request."],
    ["friend-remove", "Support removing a friend."],
    ["follow", "Support following."],
    ["unfollow", "Support unfollowing."],
    ["block", "Support blocking."],
    ["unblock", "Support unblocking."],
    ["report", "Support reporting."],
    ["post-create", "Support creating a post."],
    ["post-edit", "Support editing a post."],
    ["post-delete", "Support deleting a post."],
    ["post-media", "Support adding post media."],
    ["like", "Support liking."],
    ["unlike", "Support unliking."],
    ["react", "Support reacting."],
    ["comment", "Support commenting."],
    ["comment-edit", "Support editing a comment."],
    ["comment-delete", "Support deleting a comment."],
    ["save", "Support saving."],
    ["unsave", "Support unsaving."],
    ["share", "Support sharing."],
    ["hide", "Support hiding."],
    ["group-join", "Support joining a group."],
    ["group-leave", "Support leaving a group."],
    ["group-request", "Support requesting group access."],
    ["group-approve", "Support authorised membership approval."],
    ["thread-create", "Support creating a thread."],
    ["thread-reply", "Support replying to a thread."],
    ["thread-moderate", "Support authorised thread moderation."],
    ["conversation-start", "Support starting a conversation."],
    ["conversation-continue", "Support continuing a conversation."],
    ["conversation-search", "Support searching conversations."],
    ["send-text", "Support sending text."],
    ["send-image", "Support sending an image."],
    ["send-video", "Support sending video."],
    ["send-audio", "Support sending audio."],
    ["send-document", "Support sending a document."],
    ["message-react", "Support reacting to a message."],
    ["message-reply", "Support replying to a message."],
    ["message-edit", "Support editing messages where supported."],
    ["message-delete", "Support deleting messages where supported."],
    ["delivery-state", "Show truthful message delivery state."],
    ["read-state", "Show message read state."],
    ["message-failed", "Handle a failed message."],
    ["upload-retry", "Support retrying a failed rich-media upload."],
    ["voice-start", "Support starting a voice call."],
    ["video-start", "Support starting a video call."],
    ["call-accept", "Support accepting a call."],
    ["call-decline", "Support declining a call."],
    ["call-end", "Support ending a call."],
    ["mute", "Support muting."],
    ["unmute", "Support unmuting."],
    ["camera-enable", "Support enabling the camera."],
    ["camera-disable", "Support disabling the camera."],
    ["device-switch", "Support switching call devices."],
    ["permission-unavailable", "Handle unavailable media permissions."],
    ["connection-dropped", "Handle a dropped call connection."],
    ["missed-call", "Handle a missed call."],
    ["participant-block", "Support blocking a call or message participant."],
    ["participant-report", "Support reporting a call or message participant."],
    ["immediate-feedback", "Give immediate feedback for create, like, comment, save, share, and message controls."],
    ["privacy-boundaries", "Do not leak protected content in signed-out, blocked, private, or missing-thread states."],
    ["relationship-consistency", "Update membership and friendship state consistently across surfaces."],
    ["upload-recovery", "Let users retry or remove failed rich-media uploads."],
    ["call-state", "Communicate call connection and permission states clearly."],
    ["delivery-truth", "Never claim a message was delivered when it was not."],
    ["fixture-privacy", "Do not derive Design Lab private-content fixtures from production data."],
  ],
);

const marketplaceRouteRequirements = requirements(
  "routes.marketplace",
  "ROUTE.MARKET",
  [
    ["listings", "Register and cover /listings."],
    ["listing-detail", "Register and cover /listings/[id]."],
    ["listing-new", "Register and cover /listings/new."],
    ["marketplace", "Register and cover /marketplace."],
    ["marketplace-detail", "Register and cover /marketplace/[id]."],
    ["marketplace-new", "Register and cover /marketplace/new."],
    ["edit-route", "Discover or create listing-edit routes."],
    ["manage-route", "Discover or create listing-management routes."],
    ["seller-inventory-route", "Discover or create seller-inventory routes."],
    ["enquiries-route", "Discover or create listing-enquiry routes."],
    ["drafts-route", "Discover or create listing-draft routes."],
    ["archived-route", "Discover or create archived-listing routes."],
    ["unavailable-route", "Discover or create sold or unavailable-listing routes."],
    ["verification-route", "Discover or create verification routes."],
    ["ownership-route", "Discover or create ownership-evidence routes."],
    ["media-route", "Discover or create media-management routes."],
    ["search", "Support marketplace search."],
    ["filter", "Support marketplace filtering."],
    ["sort", "Support marketplace sorting."],
    ["pagination", "Support pagination or infinite loading."],
    ["carousel", "Support viewing the media carousel."],
    ["primary-image", "Support selecting a primary image."],
    ["seller-profile", "Support opening the seller profile."],
    ["save", "Support saving a listing."],
    ["unsave", "Support unsaving a listing."],
    ["enquire", "Support making an enquiry."],
    ["share", "Support sharing a listing."],
    ["report", "Support reporting a listing."],
    ["draft", "Support creating a draft."],
    ["publish", "Support publishing."],
    ["edit", "Support editing."],
    ["unpublish", "Support unpublishing."],
    ["archive", "Support archiving."],
    ["mark-unavailable", "Support marking a listing unavailable."],
    ["delete", "Support deletion where permitted."],
    ["upload-images", "Support image uploads."],
    ["upload-video", "Support video uploads."],
    ["reorder-media", "Support reordering media."],
    ["remove-media", "Support removing media."],
    ["media-disclosure", "Support truthful media disclosures."],
    ["ownership-evidence", "Support ownership or verification evidence where applicable."],
    ["inventory-separation", "Keep six verified dog cards separate from active listing inventory."],
    ["illustrative-disclosure", "Disclose illustrative media without implying seller, animal, or transaction verification."],
    ["auth-ownership", "Enforce authentication and ownership for create, edit, save, and enquiry paths."],
    ["hide-seller-controls", "Do not show seller controls to unauthorised users."],
    ["safe-missing", "Do not leak private information for missing sellers or listings."],
    ["upload-recovery", "Make media upload failures recoverable."],
    ["explicit-status", "Show listing status explicitly."],
    ["save-feedback", "Give immediate save and unsave feedback."],
    ["no-get-mutation", "Do not trigger destructive mutations through a public GET request."],
  ],
);

const accountRouteRequirements = requirements("routes.account", "ROUTE.ACCOUNT", [
  ["home", "Register and cover /account."],
  ["appearance", "Register and cover /account/appearance."],
  ["billing", "Register and cover /account/billing."],
  ["notifications", "Register and cover /account/notifications."],
  ["pages", "Register and cover /account/pages."],
  ["page-detail", "Register and cover /account/pages/[id]."],
  ["privacy", "Register and cover /account/privacy."],
  ["profile", "Register and cover /account/profile."],
  ["saved-listings", "Register and cover /account/saved-listings."],
  ["security", "Register and cover /account/security."],
  ["support", "Register and cover /account/support."],
  ["team", "Register and cover /account/team."],
  ["usage", "Register and cover /account/usage."],
  ["page-create", "Discover or create managed-page creation."],
  ["page-edit", "Discover or create managed-page editing."],
  ["page-transfer", "Discover or create managed-page ownership transfer."],
  ["page-delete", "Discover or create managed-page deletion."],
  ["team-invite", "Discover or create team invitations."],
  ["invite-accept", "Discover or create invitation acceptance."],
  ["invite-reject", "Discover or create invitation rejection."],
  ["team-leave", "Discover or create leaving a team."],
  ["member-remove", "Discover or create removing a team member."],
  ["member-role", "Discover or create changing a member role."],
  ["checkout", "Discover or create subscription checkout."],
  ["billing-return", "Discover or create billing return."],
  ["billing-cancel", "Discover or create billing cancellation."],
  ["payment-failure", "Discover or create payment failure."],
  ["invoices", "Discover or create invoice access."],
  ["account-delete", "Discover or create account deletion."],
  ["data-export", "Discover or create data export."],
  ["ticket-detail", "Discover or create support-ticket details."],
  ["onboarding-management", "Discover or create onboarding and help management."],
  ["validate", "Validate every account form before mutation."],
  ["mutation-feedback", "Give every mutation pending, success, and recoverable-failure feedback."],
  ["billing-intent", "Preserve plan intent on billing return paths."],
  ["no-query-payment-proof", "Never treat billing query parameters as payment proof."],
  ["safe-auth-return", "Let signed-out users authenticate and return safely without an open redirect."],
  ["sensitive-confirmation", "Require suitable confirmation for security-sensitive changes."],
  ["least-privilege", "Enforce least privilege for team role changes."],
  ["last-owner", "Prevent removal of the last required owner or administrator without safe transfer."],
  ["notification-scope", "Explain notification channel and scope."],
  ["export-delete-status", "Communicate the real status of data export and deletion requests."],
  ["restart-reset-tour", "Allow onboarding tours to be restarted or reset from support or help."],
]);

const administrationRouteRequirements = requirements(
  "routes.administration",
  "ROUTE.ADMIN",
  [
    ["home", "Register and cover /admin."],
    ["account-deletion", "Register and cover /admin/account-deletion."],
    ["actions", "Register and cover /admin/actions."],
    ["audit", "Register and cover /admin/audit."],
    ["bespoke", "Register and cover /admin/bespoke."],
    ["billing", "Register and cover /admin/billing."],
    ["billing-events", "Register and cover /admin/billing-events."],
    ["bug-reports", "Register and cover /admin/bug-reports."],
    ["compliance", "Register and cover /admin/compliance."],
    ["dog-ownership", "Register and cover /admin/dog-ownership."],
    ["entitlements", "Register and cover /admin/entitlements."],
    ["exports", "Register and cover /admin/exports."],
    ["feed", "Register and cover /admin/feed."],
    ["feedback", "Register and cover /admin/feedback."],
    ["invitations", "Register and cover /admin/invitations."],
    ["invoices", "Register and cover /admin/invoices."],
    ["jobs", "Register and cover /admin/jobs."],
    ["listings", "Register and cover /admin/listings."],
    ["organizations", "Register and cover /admin/organizations."],
    ["page-rules", "Register and cover /admin/page-rules."],
    ["payments", "Register and cover /admin/payments."],
    ["plans", "Register and cover /admin/plans."],
    ["reports", "Register and cover /admin/reports."],
    ["retention", "Register and cover /admin/retention."],
    ["safety", "Register and cover /admin/safety."],
    ["site-content", "Register and cover /admin/site-content."],
    ["source-health", "Register and cover /admin/source-health."],
    ["subscriptions", "Register and cover /admin/subscriptions."],
    ["support", "Register and cover /admin/support."],
    ["usage", "Register and cover /admin/usage."],
    ["users", "Register and cover /admin/users."],
    ["webhooks", "Register and cover /admin/webhooks."],
    ["moderator-nav", "Exclude administrator-only mutations from moderator navigation."],
    ["server-authz", "Protect every privileged mutation server-side."],
    ["allowlist-status", "Allowlist privileged status values."],
    ["required-reason", "Do not allow required mutation reasons to be bypassed."],
    ["danger-confirm", "Require confirmation for dangerous actions."],
    ["self-lockout", "Block operator self-lockout."],
    ["last-owner-admin", "Enforce last-owner and last-administrator protections."],
    ["safe-failure", "Show a safe reference and retry path for sensitive failures."],
    ["secret-safety", "Never expose internal errors, secrets, or provider payloads."],
    ["audit-mutation", "Record actor, target, reason, timestamp, and result for every privileged mutation."],
    ["preserve-queue", "Preserve queue filters and pagination."],
    ["deduplicate", "Prevent repeated submissions from duplicating actions."],
    ["webhook-idempotency", "Make webhook reprocessing idempotent."],
    ["read-only", "Prevent read-only operators from triggering mutations."],
  ],
);

const aiToolsRouteRequirements = requirements("routes.ai-tools", "ROUTE.AI", [
  ["agents", "Register and cover /agents."],
  ["related-routes", "Discover and register related tool, agent, session, history, and configuration routes."],
  ["gate-explanation", "Explain the next permitted action at feature and tier gates."],
  ["capability-truth", "Describe agent capabilities and limitations accurately."],
  ["secret-safety", "Do not expose secrets, internal prompts, or credentials."],
  ["unsupported-hidden", "Do not present unsupported actions as available."],
  ["states", "Represent pending, running, completed, interrupted, and failed states."],
  ["cancel", "Let users safely cancel a supported running task."],
  ["limitations", "Identify limitations of generated recommendations."],
  ["no-silent-mutation", "Do not let AI output silently mutate protected data."],
  ["mutation-authz", "Apply the same permission checks to AI mutations as manual actions."],
]);

const designLabRouteRequirements = requirements("design-lab.routes", "DL.ROUTE", [
  ["master", "Provide a central /design-lab screen explorer."],
  ["demo-experience", "Register and cover /design-lab/demo-experience."],
  ["dock-skins", "Register and cover /design-lab/dock-skins."],
  ["role-blueprints", "Register and cover /design-lab/role-blueprints."],
  ["feed-device-preview", "Register and cover /feed/device-preview."],
  ["marketplace", "Register and cover /marketplace/design-lab."],
  ["every-route", "Include every registered route and meaningful component in the central explorer."],
]);

const designLabSelectorRequirements = requirements(
  "design-lab.selectors",
  "DL.SELECT",
  [
    ["product-area", "Let reviewers select product area."],
    ["route", "Let reviewers select route."],
    ["record", "Let reviewers select a dynamic sample record."],
    ["role", "Let reviewers select role."],
    ["tier", "Let reviewers select subscription tier."],
    ["auth", "Let reviewers select authentication state."],
    ["permissions", "Let reviewers select permissions."],
    ["feature-flags", "Let reviewers select feature flags."],
    ["device-width", "Let reviewers select device width."],
    ["orientation", "Let reviewers select device orientation."],
    ["navigation", "Let reviewers select navigation style."],
    ["dock", "Let reviewers select dock style."],
    ["appearance", "Let reviewers select appearance or theme."],
    ["data-state", "Let reviewers select data state."],
    ["network-state", "Let reviewers select network state."],
    ["error-state", "Let reviewers select error state."],
    ["sponsored", "Let reviewers select sponsored-demo state where applicable."],
    ["tour", "Let reviewers select an onboarding tour."],
    ["tour-step", "Let reviewers select an onboarding step."],
    ["reduced-motion", "Let reviewers select reduced-motion mode."],
    ["high-contrast", "Let reviewers select high-contrast test mode."],
    ["long-content", "Let reviewers select long-content stress mode."],
    ["missing-image", "Let reviewers select missing-image mode."],
    ["slow-network", "Let reviewers select slow-network mode."],
  ],
);

const designLabStateRequirements = requirements("design-lab.states", "DL.STATE", [
  ["default", "Provide a default fixture where suitable."],
  ["initial-loading", "Provide an initial-loading fixture where suitable."],
  ["background-refresh", "Provide a background-refresh fixture where suitable."],
  ["skeleton", "Provide a skeleton-loading fixture where suitable."],
  ["empty", "Provide an empty fixture where suitable."],
  ["no-results", "Provide a no-search-results fixture where suitable."],
  ["partial", "Provide a partial-data fixture where suitable."],
  ["stale", "Provide a stale-data fixture where suitable."],
  ["delayed", "Provide a delayed-data fixture where suitable."],
  ["recoverable-error", "Provide a recoverable-error fixture where suitable."],
  ["permission-denied", "Provide a permission-denied fixture where suitable."],
  ["auth-required", "Provide an authentication-required fixture where suitable."],
  ["subscription-required", "Provide a subscription-required fixture where suitable."],
  ["feature-disabled", "Provide a feature-disabled fixture where suitable."],
  ["private", "Provide a private fixture where suitable."],
  ["blocked", "Provide a blocked fixture where suitable."],
  ["deleted", "Provide a deleted fixture where suitable."],
  ["archived", "Provide an archived fixture where suitable."],
  ["suspended", "Provide a suspended fixture where suitable."],
  ["missing-record", "Provide a missing-record fixture where suitable."],
  ["offline", "Provide an offline fixture where suitable."],
  ["success", "Provide a success fixture where suitable."],
  ["optimistic", "Provide an optimistic-update fixture where suitable."],
  ["mutation-pending", "Provide a mutation-pending fixture where suitable."],
  ["mutation-failed", "Provide a mutation-failed fixture where suitable."],
  ["long-text", "Provide a long-text fixture where suitable."],
  ["large-volume", "Provide a large-data-volume fixture where suitable."],
  ["missing-media", "Provide a missing-media fixture where suitable."],
  ["broken-media", "Provide a broken-media fixture where suitable."],
]);

const designLabUrlRequirements = requirements("design-lab.url-state", "DL.URL", [
  ["route", "Persist route in the Design Lab URL."],
  ["fixture", "Persist fixture in the Design Lab URL."],
  ["role", "Persist role in the Design Lab URL."],
  ["tier", "Persist tier in the Design Lab URL."],
  ["auth", "Persist auth in the Design Lab URL."],
  ["permissions", "Persist permissions in the Design Lab URL."],
  ["device", "Persist device in the Design Lab URL."],
  ["orientation", "Persist orientation in the Design Lab URL."],
  ["theme", "Persist theme in the Design Lab URL."],
  ["dock", "Persist dock in the Design Lab URL."],
  ["state", "Persist state in the Design Lab URL."],
  ["tour", "Persist tour in the Design Lab URL."],
  ["tour-step", "Persist tourStep in the Design Lab URL."],
  ["sponsored-demo", "Persist sponsoredDemo in the Design Lab URL."],
  ["reduced-motion", "Persist reducedMotion in the Design Lab URL."],
  ["reproduce", "Make a copied Design Lab URL reproduce the same review state."],
]);

const designLabSafetyRequirements = requirements("design-lab.safety", "DL.SAFE", [
  ["noindex", "Mark every Design Lab route noindex."],
  ["production-disabled", "Disable production access unless explicitly enabled."],
  ["no-production-data", "Do not require production data."],
  ["fixture-privacy", "Use synthetic, sanitised, or intentionally public fixtures."],
  ["no-production-mutation", "Prevent Design Lab actions from mutating production systems."],
  ["simulate-destructive", "Simulate destructive actions."],
  ["switchable-access", "Make auth and permission states switchable without weakening production security."],
  ["server-gate", "Enforce production gating server-side."],
  ["no-private-content", "Do not include private user content in fixtures."],
]);

const designLabInspectorRequirements = requirements(
  "design-lab.inspector",
  "DL.INSPECT",
  [
    ["route", "Show the route in the screen contract inspector."],
    ["actors", "Show actors in the screen contract inspector."],
    ["stories", "Show user stories in the screen contract inspector."],
    ["entry-points", "Show entry points in the screen contract inspector."],
    ["roles", "Show roles in the screen contract inspector."],
    ["tiers", "Show tiers in the screen contract inspector."],
    ["permissions", "Show permissions in the screen contract inspector."],
    ["feature-flags", "Show feature flags in the screen contract inspector."],
    ["forms", "Show forms in the screen contract inspector."],
    ["fields", "Show fields in the screen contract inspector."],
    ["primary-actions", "Show primary actions in the screen contract inspector."],
    ["secondary-actions", "Show secondary actions in the screen contract inspector."],
    ["data", "Show data dependencies in the screen contract inspector."],
    ["states", "Show supported states in the screen contract inspector."],
    ["onboarding", "Show onboarding steps in the screen contract inspector."],
    ["accessibility", "Show accessibility notes in the screen contract inspector."],
    ["responsive", "Show responsive notes in the screen contract inspector."],
    ["tests", "Show test coverage in the screen contract inspector."],
    ["gaps", "Show known gaps in the screen contract inspector."],
  ],
);

const systemStateRequirements = requirements("system-states", "SYSTEM", [
  ["not-found", "Provide a safe 404 Not Found experience."],
  ["forbidden", "Provide a safe 403 Forbidden experience."],
  ["auth-required", "Provide an authentication-required experience."],
  ["subscription-required", "Provide a subscription-required experience."],
  ["feature-unavailable", "Provide a feature-unavailable experience."],
  ["private", "Provide a private-content experience."],
  ["blocked", "Provide a blocked-relationship experience."],
  ["deleted", "Provide a deleted-content experience."],
  ["invitation-expired", "Provide an expired-invitation experience."],
  ["invitation-invalid", "Provide an invalid-invitation experience."],
  ["maintenance", "Provide a maintenance experience."],
  ["offline", "Provide an offline experience."],
  ["recoverable-error", "Provide an unexpected recoverable-error experience."],
  ["unsupported-browser", "Provide an unsupported-browser experience only where genuinely necessary."],
  ["auth-callback-loading", "Provide authentication-callback loading."],
  ["auth-callback-failure", "Provide authentication-callback failure."],
  ["billing-loading", "Provide billing-return loading."],
  ["billing-failure", "Provide billing-return failure."],
  ["upload-failure", "Provide upload failure."],
  ["rate-limit", "Provide rate-limit reached."],
  ["design-lab", "Represent every system state in the Design Lab."],
  ["automated-tests", "Cover every system state with automated tests."],
  ["specific-recovery", "Do not collapse failures with different recovery actions into one generic screen."],
]);

const globalFunctionalityRequirements = requirements(
  "global.functionality",
  "GLOBAL.FUNC",
  [
    ["actions", "Make every visible action work."],
    ["links", "Make every link resolve to a valid destination."],
    ["dynamic-fixture", "Provide a valid representative fixture for every dynamic route."],
    ["forms", "Submit every form to a real or safely simulated destination."],
    ["server-authz", "Enforce every mutation permission server-side."],
    ["destructive-confirm", "Require suitable confirmation for every destructive action."],
    ["pending", "Provide pending feedback for every asynchronous action."],
    ["duplicate", "Prevent duplicate submissions."],
    ["history", "Make back and forward navigation work correctly."],
    ["deep-refresh", "Make hard refresh work on deep routes."],
    ["query-validation", "Validate query parameters."],
    ["missing-record", "Handle missing records safely."],
  ],
);

const globalAccessibilityRequirements = requirements(
  "global.accessibility",
  "GLOBAL.A11Y",
  [
    ["keyboard", "Provide complete keyboard navigation."],
    ["focus-order", "Keep focus order aligned with visual order."],
    ["focus-visible", "Keep focus visible."],
    ["focus-restore", "Restore focus after modal closure."],
    ["headings", "Nest semantic headings correctly."],
    ["names", "Give every control an accessible name."],
    ["labels", "Give every form field a persistent label."],
    ["errors", "Associate errors programmatically with fields."],
    ["live-regions", "Use suitable live regions for status updates."],
    ["touch", "Make primary touch targets at least 44px."],
    ["colour", "Do not use colour as the only source of meaning."],
    ["motion", "Respect reduced-motion settings."],
    ["tables", "Keep tables understandable to screen readers."],
    ["dialogs", "Do not trap dialog users incorrectly."],
  ],
);

const responsiveWidthRequirements = requirements(
  "global.responsive-widths",
  "GLOBAL.WIDTH",
  [
    ["320", "Test representative layouts at 320px."],
    ["360", "Test representative layouts at 360px."],
    ["375", "Test representative layouts at 375px."],
    ["390", "Test representative layouts at 390px."],
    ["430", "Test representative layouts at 430px."],
    ["768", "Test representative layouts at 768px."],
    ["820", "Test representative layouts at 820px."],
    ["1024", "Test representative layouts at 1024px."],
    ["1280", "Test representative layouts at 1280px."],
    ["1440", "Test representative layouts at 1440px."],
    ["1920", "Test representative layouts at 1920px."],
  ],
);

const responsiveBehaviourRequirements = requirements(
  "global.responsive-behaviour",
  "GLOBAL.RESP",
  [
    ["overflow", "Prevent horizontal page overflow."],
    ["dialogs", "Prevent clipped dialogs."],
    ["menus", "Keep menu items accessible."],
    ["fixed-nav", "Prevent overlapping fixed navigation."],
    ["primary-action", "Keep primary actions visible."],
    ["tables", "Keep tables readable."],
    ["filters", "Keep filter bars usable."],
    ["media", "Preserve media ratios."],
    ["tour", "Keep onboarding popovers within the viewport."],
    ["keyboard", "Use correct mobile keyboard behaviour."],
    ["tablet", "Support portrait and landscape tablet behaviour."],
  ],
);

const privacySecurityRequirements = requirements(
  "global.privacy-security",
  "GLOBAL.SEC",
  [
    ["signed-out", "Never send protected content to signed-out users."],
    ["blocked", "Never send protected content to blocked users."],
    ["thread-metadata", "Prevent inference of private threads through metadata."],
    ["safe-errors", "Return safe errors for unauthorised actions."],
    ["server-authority", "Never treat UI hiding as authorisation."],
    ["open-redirect", "Prevent open redirects."],
    ["payment-proof", "Do not treat payment-return parameters as payment proof."],
    ["internal-ids", "Do not expose internal IDs unnecessarily."],
    ["reference-codes", "Use safe reference codes for sensitive errors."],
    ["client-secrets", "Keep production secrets out of client bundles."],
    ["fixture-privacy", "Keep private production data out of Design Lab fixtures."],
  ],
);

const dataIntegrityRequirements = requirements(
  "global.data-integrity",
  "GLOBAL.DATA",
  [
    ["missing-zero", "Keep missing values distinct from zero."],
    ["delayed", "Label delayed data."],
    ["conflicts", "Handle source conflicts explicitly."],
    ["statistics", "Do not invent statistics."],
    ["currency", "Format currency consistently."],
    ["time", "Use the correct timezone and clear date and time labels."],
    ["refresh-race", "Do not let loading data overwrite newer user changes."],
    ["optimistic", "Reconcile optimistic updates with server results."],
    ["idempotency", "Keep repeated webhook or job execution idempotent."],
  ],
);

const outputRequirements = requirements("outputs", "OUTPUT", [
  ["screen-registry", "Produce or update the machine-readable screen and route registry."],
  ["story-matrix", "Produce or update the user-story matrix."],
  ["route-inventory", "Produce or update the route inventory."],
  ["action-inventory", "Produce or update the action inventory."],
  ["form-field-registry", "Produce or update the form and field registry."],
  ["permissions-matrix", "Produce or update the role, tier, and permission matrix."],
  ["state-matrix", "Produce or update the screen-state matrix."],
  ["tour-registry", "Produce or update the onboarding-tour registry."],
  ["fixture-registry", "Produce or update the Design Lab fixture registry."],
  ["coverage-report", "Produce or update the production-to-Design-Lab coverage report."],
  ["broken-link-report", "Produce or update the broken-link report."],
  ["missing-screen-report", "Produce or update the missing-screen report."],
  ["missing-action-report", "Produce or update the missing-action report."],
  ["accessibility-audit", "Produce or update the accessibility audit."],
  ["responsive-audit", "Produce or update the responsive audit."],
  ["automated-tests", "Produce or update automated route and interaction tests."],
  ["completion-report", "Produce or update the final completion report."],
]);

const documentationPathRequirements = requirements(
  "documentation.recommended-paths",
  "DOC.PATH",
  [
    ["route", "Merge route inventory into docs/product/route-inventory.md where appropriate."],
    ["stories", "Merge user stories into docs/product/user-story-matrix.md where appropriate."],
    ["actions", "Merge actions into docs/product/action-inventory.md where appropriate."],
    ["forms", "Merge forms and fields into docs/product/form-field-registry.md where appropriate."],
    ["permissions", "Merge permissions into docs/product/permissions-matrix.md where appropriate."],
    ["states", "Merge states into docs/product/state-matrix.md where appropriate."],
    ["onboarding", "Merge onboarding into docs/product/onboarding-map.md where appropriate."],
    ["design-lab", "Merge Design Lab coverage into docs/product/design-lab-coverage.md where appropriate."],
    ["parity", "Merge production parity into docs/product/production-parity.md where appropriate."],
    ["final", "Merge the final audit into docs/product/final-audit-report.md where appropriate."],
    ["no-duplicate", "Do not duplicate existing authoritative documentation."],
  ],
);

const automatedGateRequirements = requirements(
  "verification.automated-gates",
  "VERIFY.GATE",
  [
    ["app-route-in-lab", "Fail when a registered application route is absent from the Design Lab."],
    ["lab-route-exists", "Fail when a Design Lab route references a nonexistent production screen."],
    ["internal-link", "Fail when an internal link resolves to a missing route."],
    ["primary-action", "Fail when a primary action has no handler or destination."],
    ["field-label", "Fail when a form field lacks a label."],
    ["state-fixture", "Fail when a required state fixture is missing."],
    ["access-metadata", "Fail when a route lacks role or authentication metadata."],
    ["signed-out-protected", "Fail when a protected route can render protected data while signed out."],
    ["lab-indexable", "Fail when a Design Lab route is indexable."],
    ["lab-production-mutation", "Fail when a Design Lab action can mutate production data."],
    ["tour-target", "Fail when a tour references a nonexistent target."],
    ["tour-keyboard", "Fail when a tour cannot be completed with the keyboard."],
    ["overflow", "Fail when a representative viewport produces horizontal overflow."],
    ["unauthorised-destructive", "Fail when a destructive action is available to an unauthorised role."],
  ],
);

const testLevelRequirements = requirements("verification.test-levels", "VERIFY.LEVEL", [
  ["existing-stack", "Use the project's existing test stack where possible."],
  ["route", "Include route-level tests."],
  ["component", "Include component interaction tests."],
  ["e2e", "Include representative end-to-end journeys."],
]);

const endToEndRequirements = requirements(
  "verification.e2e-journeys",
  "VERIFY.E2E",
  [
    ["visitor", "Validate a visitor exploring home, racing, pricing, responsible use, legal pages, and contact."],
    ["safe-sign-in-return", "Validate a visitor signing in and safely returning to the intended internal page."],
    ["racing-context", "Validate race search, filters, race, runner, track, and context-preserving return."],
    ["community-profile", "Validate community search and viewing a permitted public profile."],
    ["feed", "Validate creating a Feed post, reacting, commenting, saving, and sharing."],
    ["group", "Validate joining a group and participating in a thread."],
    ["pulse-media", "Validate starting a Pulse conversation and sending supported rich media."],
    ["call", "Validate starting and completing or safely exiting a voice or video call."],
    ["buyer", "Validate marketplace filtering, listing detail, save, and enquiry."],
    ["seller-publish", "Validate seller creation, validation, preview, and publishing."],
    ["seller-ownership", "Validate a seller editing or archiving only their own listing."],
    ["account-settings", "Validate updating profile, privacy, notifications, and security settings."],
    ["billing", "Validate billing review and safe checkout return."],
    ["team", "Validate a team owner inviting a member and safely managing their role."],
    ["moderator", "Validate a moderator processing an allowed queue item."],
    ["moderator-denied", "Validate a moderator being denied an administrator-only mutation."],
    ["administrator", "Validate an administrator performing an audited mutation with a required reason."],
    ["ai", "Validate launching an available AI tool and seeing accurate running, completed, and failure states."],
    ["first-run", "Validate a new user completing first-run onboarding."],
    ["restart-tour", "Validate an existing user restarting a contextual product-area tour."],
    ["mobile-onboarding", "Validate mobile onboarding without clipping, overflow, or blocked controls."],
    ["lab-reproduction", "Validate reproducing every journey with Design Lab fixtures and no production mutation."],
  ],
);

const completionEvidenceRequirements = requirements(
  "completion.evidence",
  "COMPLETE.EVIDENCE",
  [
    ["production-inspected", "Provide evidence that the public website was inspected."],
    ["route-tree-inspected", "Provide evidence that the complete local route tree was inspected."],
    ["navigation-inspected", "Provide evidence that navigation and deep links were inspected."],
    ["actors-mapped", "Provide evidence that every supported actor was mapped."],
    ["forms-mapped", "Provide evidence that every form and field was mapped."],
    ["actions-mapped", "Provide evidence that every action was mapped."],
    ["states-represented", "Provide evidence that every meaningful state was represented."],
    ["screens-implemented", "Provide evidence that missing screens and actions were implemented."],
    ["production-lab-coverage", "Provide evidence that every production screen has Design Lab coverage."],
    ["tour-lab-coverage", "Provide evidence that every onboarding tour has Design Lab coverage."],
    ["tests-pass", "Provide evidence that all acceptance tests pass."],
    ["exclusions", "Explicitly justify every remaining exclusion with an owner and reason."],
    ["beyond-seed", "Do not declare completion from the supplied seed route list alone."],
  ],
);

const prohibitedPlaceholderRequirements = requirements(
  "completion.prohibited-placeholders",
  "COMPLETE.NO_PLACEHOLDER",
  [
    ["add-later", "Do not leave an 'Add later' placeholder."],
    ["todo", "Do not leave a TODO placeholder."],
    ["coming-soon", "Do not leave a 'Coming soon' placeholder."],
    ["mock-this", "Do not leave a 'Mock this' placeholder."],
    ["handle-errors", "Do not leave a vague 'Handle errors' placeholder."],
    ["support-mobile", "Do not leave a vague 'Support mobile' placeholder."],
    ["add-accessibility", "Do not leave a vague 'Add accessibility' placeholder."],
    ["explicit-exclusion", "Implement, test, or explicitly exclude each requirement with owner and reason."],
  ],
);

const userUnderstandingRequirements = requirements(
  "completion.user-understanding",
  "COMPLETE.UNDERSTAND",
  [
    ["location", "Ensure every user can understand where they are."],
    ["information", "Ensure every user can understand the information they are viewing."],
    ["actions", "Ensure every user can understand what they can do."],
    ["unavailable", "Ensure every user can understand why an action may be unavailable."],
    ["next", "Ensure every user can understand what will happen next."],
    ["recover", "Ensure every user can understand how to recover when something fails."],
    ["help", "Ensure every user can understand where to find assistance."],
  ],
);

export const PRODUCT_MASTER_REQUIREMENTS: readonly ProductMasterRequirement[] = [
  ...outcomeRequirements,
  ...auditSourceRequirements,
  ...productionCrawlRequirements,
  ...routeRegistryRequirements,
  ...storyContractRequirements,
  ...storyCapabilityRequirements,
  ...actionControlRequirements,
  ...actionBehaviourRequirements,
  ...formContractRequirements,
  ...fieldContractRequirements,
  ...onboardingSurfaceRequirements,
  ...onboardingBehaviourRequirements,
  ...onboardingPersistenceRequirements,
  ...onboardingRoleRequirements,
  ...onboardingAccessRequirements,
  ...onboardingTargetingRequirements,
  ...onboardingDeviceRequirements,
  ...onboardingMobileSafetyRequirements,
  ...onboardingAccessibilityRequirements,
  ...onboardingAnalyticsRequirements,
  ...onboardingManagementRequirements,
  ...racingProductionRequirements,
  ...racingFixtureRequirements,
  ...publicRouteRequirements,
  ...racingRouteRequirements,
  ...communityRouteRequirements,
  ...marketplaceRouteRequirements,
  ...accountRouteRequirements,
  ...administrationRouteRequirements,
  ...aiToolsRouteRequirements,
  ...designLabRouteRequirements,
  ...designLabSelectorRequirements,
  ...designLabStateRequirements,
  ...designLabUrlRequirements,
  ...designLabSafetyRequirements,
  ...designLabInspectorRequirements,
  ...systemStateRequirements,
  ...globalFunctionalityRequirements,
  ...globalAccessibilityRequirements,
  ...responsiveWidthRequirements,
  ...responsiveBehaviourRequirements,
  ...privacySecurityRequirements,
  ...dataIntegrityRequirements,
  ...outputRequirements,
  ...documentationPathRequirements,
  ...automatedGateRequirements,
  ...testLevelRequirements,
  ...endToEndRequirements,
  ...completionEvidenceRequirements,
  ...prohibitedPlaceholderRequirements,
  ...userUnderstandingRequirements,
];

export const PRODUCT_MASTER_REQUIREMENT_TOTAL =
  PRODUCT_MASTER_REQUIREMENTS.length;
