import type { ProductMasterRequirementStatus } from "./product-master-requirements";

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_EVIDENCE_FILE =
  "src/components/product-action-type-control-catalogue-evidence.ts" as const;
export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_SCANNER_FILE =
  "scripts/action-type-source-catalogue.ts" as const;
export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_TEST_FILE =
  "src/components/product-action-type-control-catalogue-evidence.test.ts" as const;

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_SCOPE =
  "Deterministic source-static catalogue of production-reachable TSX control primitives. The scanner records every matching source control by stable path, owning symbol, primitive, and semantic signature, or records a verified empty list. Small categories freeze the ordered identities directly; high-cardinality categories freeze the same ordered identities by exact count and SHA-256 digest. This evidence does not establish rendered control count, hydration, visibility, clickability, keyboard operation, focus treatment, accessible naming, runtime authorization, mutation success, or production parity.";

export const PRODUCT_ACTION_TYPE_REQUIREMENT_IDS = [
  "ACTION.TYPE.buttons",
  "ACTION.TYPE.links",
  "ACTION.TYPE.icon-buttons",
  "ACTION.TYPE.cards",
  "ACTION.TYPE.tabs",
  "ACTION.TYPE.accordions",
  "ACTION.TYPE.filters",
  "ACTION.TYPE.sort",
  "ACTION.TYPE.dates",
  "ACTION.TYPE.search",
  "ACTION.TYPE.pagination",
  "ACTION.TYPE.menus",
  "ACTION.TYPE.toggles",
  "ACTION.TYPE.checkboxes",
  "ACTION.TYPE.radios",
  "ACTION.TYPE.selects",
  "ACTION.TYPE.sliders",
  "ACTION.TYPE.uploads",
  "ACTION.TYPE.media",
  "ACTION.TYPE.likes",
  "ACTION.TYPE.saves",
  "ACTION.TYPE.shares",
  "ACTION.TYPE.comments",
  "ACTION.TYPE.messages",
  "ACTION.TYPE.calls",
  "ACTION.TYPE.video",
  "ACTION.TYPE.notifications",
  "ACTION.TYPE.billing",
  "ACTION.TYPE.admin",
] as const;

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_REQUIREMENT_IDS = [
  "ACTION.TYPE.buttons",
  "ACTION.TYPE.links",
  "ACTION.TYPE.icon-buttons",
  "ACTION.TYPE.cards",
  "ACTION.TYPE.tabs",
  "ACTION.TYPE.accordions",
  "ACTION.TYPE.sort",
  "ACTION.TYPE.toggles",
  "ACTION.TYPE.pagination",
  "ACTION.TYPE.menus",
  "ACTION.TYPE.filters",
  "ACTION.TYPE.saves",
  "ACTION.TYPE.likes",
  "ACTION.TYPE.shares",
  "ACTION.TYPE.calls",
  "ACTION.TYPE.messages",
  "ACTION.TYPE.comments",
  "ACTION.TYPE.notifications",
  "ACTION.TYPE.billing",
  "ACTION.TYPE.admin",
  "ACTION.TYPE.media",
  "ACTION.TYPE.dates",
  "ACTION.TYPE.search",
  "ACTION.TYPE.checkboxes",
  "ACTION.TYPE.radios",
  "ACTION.TYPE.selects",
  "ACTION.TYPE.sliders",
  "ACTION.TYPE.uploads",
  "ACTION.TYPE.video",
] as const;

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_OPEN_REQUIREMENT_IDS = [] as const;

export type ProductActionTypeRequirementId =
  (typeof PRODUCT_ACTION_TYPE_REQUIREMENT_IDS)[number];
export type ProductActionTypeControlCatalogueRequirementId =
  (typeof PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_REQUIREMENT_IDS)[number];

export type ProductActionTypeControlCatalogueSnapshot = {
  state: "present" | "absent";
  controlIds?: readonly string[];
  controlCount?: number;
  controlDigest?: string;
};

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE: Readonly<
  Record<
    ProductActionTypeControlCatalogueRequirementId,
    ProductActionTypeControlCatalogueSnapshot
  >
> = {
  "ACTION.TYPE.buttons": {
    state: "present",
    controlCount: 228,
    controlDigest:
      "9068451c8b87ac1621b3ec0252553824ad142b9634471455c6886272a702bf2b",
  },
  "ACTION.TYPE.links": {
    state: "present",
    controlCount: 328,
    controlDigest:
      "27a6ad296c292ab4d3e09ef3791d430880f88df236bee2d1b73e23a37b586998",
  },
  "ACTION.TYPE.icon-buttons": {
    state: "present",
    controlIds: [
      "src/app/admin/admin-operation-status.tsx::AdminOperationStatus::ACTION.TYPE.icon-buttons::button::type=button|aria-label=Dismiss success message",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=cameraEnabled ? "Turn camera off" : "Turn camera on"',
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=Leave call",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=micEnabled ? "Mute microphone" : "Unmute microphone"',
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=screenShareEnabled ? "Stop screen sharing" : "Share screen"',
      "src/components/demo-read-only-guard.tsx::DemoReadOnlyGuard::ACTION.TYPE.icon-buttons::button::type=button|aria-label=Dismiss demo notice",
      'src/components/hub/hub-conversation-dock.tsx::QuickChatWindow::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Close quick chat with ${conversation.otherName}`',
      "src/components/hub/hub-conversation-dock.tsx::QuickChatWindow::ACTION.TYPE.icon-buttons::button::type=submit|aria-label=Send message",
      'src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.icon-buttons::button::type=button|aria-label=pendingVideo ? `Starting video call with ${friend.displayName}` : `Video call ${friend.displayName}`',
      'src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.icon-buttons::button::type=button|aria-label=pendingVoice ? `Starting voice call with ${friend.displayName}` : `Voice call ${friend.displayName}`',
      'src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.icon-buttons::button::type=submit|aria-label=`Start chat with ${friend.displayName}`',
      'src/components/hub/hub-messenger-panel.tsx::HubMessengerPanel::ACTION.TYPE.icon-buttons::button::type=submit|aria-label=`Accept friend request from ${request.displayName}`',
      'src/components/hub/hub-messenger-panel.tsx::HubMessengerPanel::ACTION.TYPE.icon-buttons::button::type=submit|aria-label=`Decline friend request from ${request.displayName}`',
      'src/components/instant-feed-controls.tsx::InstantFeedCommentForm::ACTION.TYPE.icon-buttons::button::type=submit|aria-label=parentCommentId ? "Add reply" : "Add comment"',
      "src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.icon-buttons::button::type=button|aria-label=reaction.label",
      "src/components/interactive-help.tsx::InteractiveHelp::ACTION.TYPE.icon-buttons::button::type=button",
      "src/components/interactive-help.tsx::InteractiveHelp::ACTION.TYPE.icon-buttons::button::type=button|aria-label=Dismiss onboarding help",
      'src/components/listing-card-media-carousel.tsx::ListingCardMediaCarousel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Show next image for ${listingTitle}`',
      'src/components/listing-card-media-carousel.tsx::ListingCardMediaCarousel::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Show previous image for ${listingTitle}`',
      "src/components/marketplace-dog-player-card.tsx::CardBack::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Show the front of ${dog.name}'s card`",
      'src/components/media-attachment-fields.tsx::MediaAttachmentFields::ACTION.TYPE.icon-buttons::button::type=button|aria-label=item.step === "done" ? `Remove ${item.filename}` : `Cancel upload of ${item.filename}`',
      'src/components/profile-media-status.tsx::ProfileMediaStatus::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Cancel ${label.toLowerCase()} upload`',
      'src/components/recipient-picker.tsx::RecipientPicker::ACTION.TYPE.icon-buttons::button::type=button|aria-label=`Clear recipient ${selected.displayName}`',
    ],
  },
  "ACTION.TYPE.cards": {
    state: "present",
    controlIds: [
      "src/app/account/page.tsx::SignedInAccount::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/admin/page.tsx::AdminPage::ACTION.TYPE.cards::Link::unlabelled-source-control::instance-1",
      "src/app/admin/page.tsx::AdminPage::ACTION.TYPE.cards::Link::unlabelled-source-control::instance-2",
      "src/app/discover/page.tsx::DiscoverPage::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/discover/page.tsx::DiscoveryGroup::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/listings/page.tsx::MarketplaceDogListingPlayerCard::ACTION.TYPE.cards::MarketplaceDogPlayerCard::unlabelled-source-control",
      "src/app/listings/page.tsx::MarketplaceProfileShowcase::ACTION.TYPE.cards::MarketplaceDogPlayerCard::unlabelled-source-control",
      "src/app/p/[handle]/page.tsx::StorefrontBody::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/page.tsx::FeatureCard::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/app/page.tsx::HomePage::ACTION.TYPE.cards::FeatureCard::unlabelled-source-control",
      'src/app/races/page.tsx::NextToGoStrip::ACTION.TYPE.cards::Link::aria-label=`Open ${meeting.track.name} race ${race.raceNumber} at ${formatRaceTime(race.raceTime)}`',
      'src/app/races/page.tsx::RaceRowLink::ACTION.TYPE.cards::Link::aria-label=`Open ${trackName}, ${state} race ${race.raceNumber} at ${formatRaceTime(race.raceTime)}. Status: ${status.label}`',
      'src/app/races/page.tsx::RacesPage::ACTION.TYPE.cards::Link::aria-label=`Open replay for race ${race.raceNumber} at ${race.meeting.track.name}`',
      'src/components/dog-search.tsx::DogSearchInner::ACTION.TYPE.cards::Link::id=`${listboxId}-option-${i}`|role=option',
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.cards::a::unlabelled-source-control",
      "src/components/marketplace-dog-player-card.tsx::MarketplaceDogPlayerCard::ACTION.TYPE.cards::div::unlabelled-source-control",
      'src/components/race-meeting-navigation.tsx::RaceMeetingNavigation::ACTION.TYPE.cards::Link::aria-label=`Next race, Race ${next.raceNumber}`',
      'src/components/race-meeting-navigation.tsx::RaceMeetingNavigation::ACTION.TYPE.cards::Link::aria-label=`Previous race, Race ${previous.raceNumber}`',
      "src/components/race-meeting-navigation.tsx::RaceMeetingNavigation::ACTION.TYPE.cards::Link::unlabelled-source-control",
      "src/components/site-header.tsx::MobileNavigationMenu::ACTION.TYPE.cards::MobileMenuLink::unlabelled-source-control",
    ],
  },
  "ACTION.TYPE.tabs": {
    state: "present",
    controlIds: [
      "src/app/feed/page.tsx::FeedPage::ACTION.TYPE.tabs::Link::text=For You",
      "src/app/feed/page.tsx::FeedPage::ACTION.TYPE.tabs::Link::text=Latest",
    ],
  },
  "ACTION.TYPE.accordions": {
    state: "present",
    controlIds: [
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.accordions::summary::text=Transfer ownership",
      "src/app/contact/page.tsx::ContactPage::ACTION.TYPE.accordions::summary::text=Show a safe example",
      "src/app/dogs/[id]/page.tsx::DogProfilePage::ACTION.TYPE.accordions::summary::unlabelled-source-control",
      "src/app/pricing/page.tsx::PricingPage::ACTION.TYPE.accordions::summary::unlabelled-source-control",
      "src/components/account-support-help-centre.tsx::AccountSupportHelpCentre::ACTION.TYPE.accordions::summary::text=Available guided tours ( )",
      "src/components/feed-comments-panel.tsx::CommentCard::ACTION.TYPE.accordions::summary::text=Reply",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.accordions::summary::text=Edit",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.accordions::summary::aria-label=Post options",
      "src/components/header-nav.tsx::HeaderNav::ACTION.TYPE.accordions::summary::unlabelled-source-control",
      "src/components/instant-feed-controls.tsx::InstantFeedPostComposer::ACTION.TYPE.accordions::summary::text=Topic and audience",
      "src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.accordions::summary::aria-label=Choose a reaction",
      "src/components/interactive-help.tsx::InteractiveHelpMenuControls::ACTION.TYPE.accordions::summary::text=Recently completed",
      "src/components/interactive-help.tsx::InteractiveHelpMenuControls::ACTION.TYPE.accordions::summary::text=Understand plan upgrades",
    ],
  },
  "ACTION.TYPE.sort": {
    state: "present",
    controlIds: [
      "src/app/admin/feed/page.tsx::AdminFeedPage::ACTION.TYPE.sort::input::name=sortOrder|type=number|aria-label=Topic sort order",
      "src/app/admin/listings/page.tsx::AdminListingsPage::ACTION.TYPE.sort::input::name=sortOrder|type=number",
      "src/app/feed/page.tsx::FeedPage::ACTION.TYPE.sort::Link::text=For You",
      "src/app/feed/page.tsx::FeedPage::ACTION.TYPE.sort::Link::text=Latest",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.sort::AutoSubmitSelect::name=sort|aria-label=Sort listings",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.sort::AutoSubmitSelect::name=sort|aria-label=Sort races",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.sort::button::type=submit|text=Filter",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.sort::AutoSubmitSelect::name=sort|aria-label=Results order",
    ],
  },
  "ACTION.TYPE.toggles": {
    state: "present",
    controlIds: [
      "src/components/agent-demo-console.tsx::AgentDemoConsoleInner::ACTION.TYPE.toggles::m.button::type=button",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.toggles::button::type=button|aria-label=cameraEnabled ? "Turn camera off" : "Turn camera on"',
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.toggles::button::type=button|aria-label=micEnabled ? "Mute microphone" : "Unmute microphone"',
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.toggles::button::type=button|aria-label=screenShareEnabled ? "Stop screen sharing" : "Share screen"',
      "src/components/feed-comments-panel.tsx::CommentReactionButton::ACTION.TYPE.toggles::button::type=button",
      "src/components/hub/hub-left-sidebar.tsx::IdentityButton::ACTION.TYPE.toggles::button::type=submit",
      "src/components/instant-feed-controls.tsx::InstantFeedMuteButton::ACTION.TYPE.toggles::button::type=button",
      'src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.toggles::button::type=button|aria-label=`${reactionType ? "Remove" : "Add"} ${selected.label} reaction`',
      "src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.toggles::button::type=button|aria-label=reaction.label",
      "src/components/instant-feed-controls.tsx::InstantFeedSaveButton::ACTION.TYPE.toggles::button::type=button",
      "src/components/instant-feed-controls.tsx::InstantFeedTopicFollowButton::ACTION.TYPE.toggles::button::type=button",
      "src/components/instant-save-listing-button.tsx::InstantSaveListingButton::ACTION.TYPE.toggles::button::type=button",
      "src/components/marketplace-dog-player-card.tsx::MarketplaceDogPlayerCard::ACTION.TYPE.toggles::button::type=button::instance-1",
      "src/components/marketplace-dog-player-card.tsx::MarketplaceDogPlayerCard::ACTION.TYPE.toggles::button::type=button::instance-2",
      "src/components/marketplace-dog-player-card.tsx::MarketplaceDogPlayerCard::ACTION.TYPE.toggles::button::type=button::instance-3",
      "src/components/media-focal-point-editor.tsx::MediaFocalPointEditor::ACTION.TYPE.toggles::button::type=button|text=Desktop",
      "src/components/media-focal-point-editor.tsx::MediaFocalPointEditor::ACTION.TYPE.toggles::button::type=button|text=Mobile",
    ],
  },
  "ACTION.TYPE.pagination": {
    state: "present",
    controlIds: [
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.pagination::Link::text=Next",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.pagination::Link::text=Previous",
      "src/app/listings/page.tsx::MarketplacePagination::ACTION.TYPE.pagination::Link::text=Next",
      "src/app/listings/page.tsx::MarketplacePagination::ACTION.TYPE.pagination::Link::text=Previous",
      "src/components/feed-comments-panel.tsx::FeedCommentsPanel::ACTION.TYPE.pagination::button::type=button",
    ],
  },
  "ACTION.TYPE.menus": {
    state: "present",
    controlIds: [
      "src/app/admin/admin-nav.tsx::AdminNav::ACTION.TYPE.menus::SheetTrigger::aria-label=Open admin navigation|text=Menu",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.menus::summary::aria-label=Post options",
      "src/components/header-nav.tsx::HeaderNav::ACTION.TYPE.menus::summary::unlabelled-source-control",
      "src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.menus::summary::aria-label=Choose a reaction",
      "src/components/mobile-bottom-dock.tsx::MobileBottomDock::ACTION.TYPE.menus::SheetTrigger::aria-label=More navigation",
      'src/components/site-header.tsx::SiteHeader::ACTION.TYPE.menus::SheetTrigger::aria-label=`Open account menu for ${user.name}`::instance-1',
      'src/components/site-header.tsx::SiteHeader::ACTION.TYPE.menus::SheetTrigger::aria-label=`Open account menu for ${user.name}`::instance-2',
      'src/components/site-header.tsx::SiteHeader::ACTION.TYPE.menus::SheetTrigger::aria-label=`Open account menu for ${user.name}`::instance-3',
      "src/components/site-header.tsx::SiteHeader::ACTION.TYPE.menus::SheetTrigger::aria-label=Open navigation menu::instance-1",
      "src/components/site-header.tsx::SiteHeader::ACTION.TYPE.menus::SheetTrigger::aria-label=Open navigation menu::instance-2",
    ],
  },
  "ACTION.TYPE.filters": {
    state: "present",
    controlIds: [
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.filters::AutoSubmitSelect::name=role|aria-label=Filter users by role",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.filters::AutoSubmitSelect::name=tier|aria-label=Filter users by tier",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.filters::button::type=submit|text=Filter",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.filters::Link::text=Clear filters",
      "src/app/listings/page.tsx::ListingsResults::ACTION.TYPE.filters::Link::text=Clear filters",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.filters::AutoSubmitSelect::name=category|aria-label=Category",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.filters::AutoSubmitSelect::name=sort|aria-label=Sort listings",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.filters::button::type=submit|text=Search",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.filters::input::name=q|placeholder=Title or description",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.filters::Link::text=Clear",
      "src/app/races/page.tsx::FilterChip::ACTION.TYPE.filters::Link::unlabelled-source-control",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::AutoSubmitSelect::name=sort|aria-label=Sort races",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::button::type=submit|text=Filter::instance-1",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::button::type=submit|text=Filter::instance-2",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::button::type=submit|text=Search",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::FilterChip::text=All",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::FilterChip::unlabelled-source-control::instance-1",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::FilterChip::unlabelled-source-control::instance-2",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::input::name=date|type=date|aria-label=Choose race date",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::input::name=q|type=search|placeholder=Search track, runner, R4, 520m",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::Link::text=All dates",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.filters::Link::unlabelled-source-control",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.filters::AutoSubmitSelect::name=date|aria-label=Results date",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.filters::AutoSubmitSelect::name=sort|aria-label=Results order",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.filters::AutoSubmitSelect::name=trackId|aria-label=Results track",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.filters::button::type=submit|text=Filter",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.filters::Link::text=Clear",
      "src/app/tracks/page.tsx::TracksPage::ACTION.TYPE.filters::AutoSubmitSelect::name=state|aria-label=Filter tracks by state",
      "src/app/tracks/page.tsx::TracksPage::ACTION.TYPE.filters::button::text=Filter",
    ],
  },
  "ACTION.TYPE.saves": {
    state: "present",
    controlIds: [
      "src/app/account/page.tsx::SignedInAccount::ACTION.TYPE.saves::SubmitButton::text=Save profile",
      "src/app/account/pages/[id]/page.tsx::EditCustomPage::ACTION.TYPE.saves::SubmitButton::text=Save changes",
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.saves::SubmitButton::text=Save role",
      "src/app/admin/form-controls.tsx::AdminCreateUserForm::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control",
      "src/app/admin/form-controls.tsx::AdminOrganizationForms::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control::instance-1",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control::instance-2",
      "src/app/admin/form-controls.tsx::AdminRetentionForms::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control",
      "src/app/admin/form-controls.tsx::AdminSourceHealthForm::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.saves::AdminSubmitButton::unlabelled-source-control",
      "src/app/admin/page-rules/page.tsx::PageRulesAdmin::ACTION.TYPE.saves::SubmitButton::text=Save rules",
      "src/app/admin/safety/page.tsx::AdminSafetyPage::ACTION.TYPE.saves::button::text=Save phrase",
      "src/app/admin/site-content/page.tsx::SiteContentAdmin::ACTION.TYPE.saves::SubmitButton::text=Save pricing",
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.saves::InstantSaveListingButton::unlabelled-source-control",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.saves::SubmitButton::name=submissionIntent|text=Save as draft",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.saves::button::type=submit|text=Save",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.saves::InstantFeedSaveButton::unlabelled-source-control",
      "src/components/instant-feed-controls.tsx::InstantFeedOwnerControls::ACTION.TYPE.saves::button::type=submit|text=Save changes",
      "src/components/instant-feed-controls.tsx::InstantFeedSaveButton::ACTION.TYPE.saves::button::type=button",
      "src/components/instant-save-listing-button.tsx::InstantSaveListingButton::ACTION.TYPE.saves::button::type=button",
      "src/components/listing-edit-form.tsx::ListingEditForm::ACTION.TYPE.saves::button::type=submit",
      "src/components/marketplace-dog-player-card.tsx::MarketplaceDogPlayerCard::ACTION.TYPE.saves::button::type=button",
    ],
  },
  "ACTION.TYPE.likes": {
    state: "present",
    controlIds: [
      "src/app/messages/[id]/page.tsx::MessageThreadPage::ACTION.TYPE.likes::SubmitButton::unlabelled-source-control",
      "src/components/feed-comments-panel.tsx::CommentCard::ACTION.TYPE.likes::CommentReactionButton::unlabelled-source-control",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.likes::InstantFeedReactionButton::unlabelled-source-control",
      'src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.likes::button::type=button|aria-label=`${reactionType ? "Remove" : "Add"} ${selected.label} reaction`',
      "src/components/instant-feed-controls.tsx::InstantFeedReactionButton::ACTION.TYPE.likes::button::type=button|aria-label=reaction.label",
    ],
  },
  "ACTION.TYPE.shares": {
    state: "present",
    controlIds: [
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.shares::ListingShareButton::unlabelled-source-control",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.shares::button::type=button|aria-label=screenShareEnabled ? "Stop screen sharing" : "Share screen"',
      "src/components/instant-feed-controls.tsx::InstantFeedPostComposer::ACTION.TYPE.shares::button::type=button|text=Share an update...",
      "src/components/instant-feed-controls.tsx::InstantFeedShareControls::ACTION.TYPE.shares::button::type=button",
      "src/components/instant-feed-controls.tsx::InstantFeedShareControls::ACTION.TYPE.shares::button::type=button|aria-label=Share link|text=Link",
      "src/components/listing-share-button.tsx::ListingShareButton::ACTION.TYPE.shares::button::type=button",
    ],
  },
  "ACTION.TYPE.calls": {
    state: "present",
    controlIds: [
      "src/app/messages/friends/page.tsx::PulseFriendsPage::ACTION.TYPE.calls::Link::text=Video call",
      "src/app/messages/friends/page.tsx::PulseFriendsPage::ACTION.TYPE.calls::Link::text=Voice call",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::a::text=Calls are a Pro feature",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=`Accept ${incomingInvite.callType} call from ${incomingInvite.fromName}`',
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=`Decline ${incomingInvite.callType} call from ${incomingInvite.fromName}`',
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=Call device settings",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=cameraEnabled ? "Turn camera off" : "Turn camera on"',
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=Leave call",
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=micEnabled ? "Mute microphone" : "Unmute microphone"',
      'src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|aria-label=screenShareEnabled ? "Stop screen sharing" : "Share screen"',
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Connecting...",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Dismiss",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Join call",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Try again",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Video call",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::button::type=button|text=Voice call",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::select::unlabelled-source-control::instance-1",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::select::unlabelled-source-control::instance-2",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.calls::select::unlabelled-source-control::instance-3",
      'src/components/hub/hub-conversation-dock.tsx::QuickChatWindow::ACTION.TYPE.calls::Link::aria-label=canStartCall ? `Start voice call with ${conversation.otherName}` : "Voice calls are a Pro feature"',
      'src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.calls::button::type=button|aria-label=pendingVideo ? `Starting video call with ${friend.displayName}` : `Video call ${friend.displayName}`',
      'src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.calls::button::type=button|aria-label=pendingVoice ? `Starting voice call with ${friend.displayName}` : `Voice call ${friend.displayName}`',
      "src/components/hub/hub-friends-list.tsx::HubFriendsList::ACTION.TYPE.calls::Link::aria-label=Calls are a Pro feature",
      'src/components/hub/hub-incoming-call.tsx::HubIncomingCall::ACTION.TYPE.calls::button::type=button|aria-label=`Answer ${invite.callType} call from ${invite.fromName}`|text=Answer',
      "src/components/hub/hub-incoming-call.tsx::HubIncomingCall::ACTION.TYPE.calls::button::type=button|text=Decline",
    ],
  },
  "ACTION.TYPE.messages": {
    state: "present",
    controlCount: 63,
    controlDigest:
      "a37042cffd7ebba803c93c210ad7e08de1e6d142d8765b97d7e078edabb20552",
  },
  "ACTION.TYPE.comments": {
    state: "present",
    controlIds: [
      "src/app/forum/page.tsx::ForumPage::ACTION.TYPE.comments::Link::unlabelled-source-control",
      "src/app/forum/page.tsx::ThreadRow::ACTION.TYPE.comments::Link::unlabelled-source-control",
      "src/app/forum/threads/[id]/page.tsx::ForumThreadPage::ACTION.TYPE.comments::SubmitButton::text=Post reply",
      "src/components/feed-comments-panel.tsx::CommentCard::ACTION.TYPE.comments::CommentReactionButton::unlabelled-source-control",
      "src/components/feed-comments-panel.tsx::CommentCard::ACTION.TYPE.comments::InstantFeedCommentForm::unlabelled-source-control",
      "src/components/feed-comments-panel.tsx::CommentCard::ACTION.TYPE.comments::summary::text=Reply",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.comments::button::type=button|text=Delete",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.comments::button::type=submit|text=Save",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.comments::input::name=body|aria-label=Edit comment",
      "src/components/feed-comments-panel.tsx::CommentOwnerActions::ACTION.TYPE.comments::summary::text=Edit",
      "src/components/feed-comments-panel.tsx::CommentReactionButton::ACTION.TYPE.comments::button::type=button",
      "src/components/feed-comments-panel.tsx::FeedCommentsPanel::ACTION.TYPE.comments::button::type=button::instance-1",
      "src/components/feed-comments-panel.tsx::FeedCommentsPanel::ACTION.TYPE.comments::button::type=button::instance-2",
      "src/components/feed-comments-panel.tsx::FeedCommentsPanel::ACTION.TYPE.comments::button::type=button|text=Hide comments",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.comments::a::text=comment",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.comments::a::unlabelled-source-control",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.comments::InstantFeedCommentForm::unlabelled-source-control",
      'src/components/instant-feed-controls.tsx::InstantFeedCommentForm::ACTION.TYPE.comments::button::type=submit|aria-label=parentCommentId ? "Add reply" : "Add comment"',
      'src/components/instant-feed-controls.tsx::InstantFeedCommentForm::ACTION.TYPE.comments::input::name=body|aria-label=parentCommentId ? "Reply" : "Comment"|placeholder=parentCommentId ? "Write a reply" : "Add a comment"',
    ],
  },
  "ACTION.TYPE.notifications": {
    state: "present",
    controlIds: [
      "src/app/account/notifications/page.tsx::AccountNotificationsPage::ACTION.TYPE.notifications::button::text=Mark all read",
      "src/app/account/notifications/page.tsx::AccountNotificationsPage::ACTION.TYPE.notifications::Link::text=Back to account",
      "src/app/account/notifications/page.tsx::NotificationList::ACTION.TYPE.notifications::button::text=Mark read",
      "src/app/account/notifications/page.tsx::NotificationList::ACTION.TYPE.notifications::Link::text=Open",
      "src/app/account/page.tsx::SignedInAccount::ACTION.TYPE.notifications::Link::text=Notifications",
      "src/components/site-header.tsx::AccountMenuItems::ACTION.TYPE.notifications::AccountLink::text=Notifications",
    ],
  },
  "ACTION.TYPE.billing": {
    state: "present",
    controlCount: 63,
    controlDigest:
      "ee5475f47d34709597773340de89d466cb2be3cbc31b3b0841c67ca7f75926f0",
  },
  "ACTION.TYPE.admin": {
    state: "present",
    controlCount: 140,
    controlDigest:
      "f77dcc4800744b85e8a767db90fb39b220111b7476dad169625c8a04f1337bd2",
  },
  "ACTION.TYPE.media": {
    state: "present",
    controlCount: 76,
    controlDigest:
      "f392082ccef8d05c1e82af6dee658906479aebeb360bdfc7f9016b1631a2c15e",
  },
  "ACTION.TYPE.dates": {
    state: "present",
    controlIds: [
      "src/app/admin/form-controls.tsx::AdminExportForm::ACTION.TYPE.dates::input::name=expiresAt|type=datetime-local|aria-label=Export expiry",
      "src/app/admin/form-controls.tsx::AdminOrganizationForms::ACTION.TYPE.dates::input::name=expiresAt|type=datetime-local|aria-label=Invitation expiry",
      "src/app/admin/form-controls.tsx::AdminRetentionForms::ACTION.TYPE.dates::input::name=scheduledFor|type=datetime-local|aria-label=Scheduled for",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.dates::input::name=date|type=date|aria-label=Choose race date",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.dates::Link::text=All dates",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.dates::Link::unlabelled-source-control",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.dates::AutoSubmitSelect::name=date|aria-label=Results date",
    ],
  },
  "ACTION.TYPE.search": {
    state: "present",
    controlIds: [
      "src/app/discover/page.tsx::DiscoverPage::ACTION.TYPE.search::input::id=discover-query|name=q|type=search|placeholder=Search people, pages, businesses, or dogs",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.search::input::name=q|placeholder=Title or description",
      "src/app/messages/[id]/page.tsx::MessageThreadPage::ACTION.TYPE.search::input::id=message-search|name=q|type=search|placeholder=Search this conversation",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.search::input::name=q|type=search|placeholder=Search track, runner, R4, 520m",
      "src/components/account-support-help-centre.tsx::AccountSupportHelpCentre::ACTION.TYPE.search::input::name=q|type=search|placeholder=Search races, billing, privacy, marketplace…",
      "src/components/dog-search.tsx::DogSearchInner::ACTION.TYPE.search::Input::id=dog-search-input|type=text|role=combobox|aria-label=Search for a greyhound by name|placeholder=Search for a greyhound...",
      "src/components/hub/add-friend-search.tsx::AddFriendSearch::ACTION.TYPE.search::input::type=search|placeholder=Name or kennel",
      "src/components/recipient-picker.tsx::RecipientPicker::ACTION.TYPE.search::input::id=inputId|type=text|role=combobox|placeholder=Search profiles by name",
      "src/components/site-header.tsx::MobileNavigationMenu::ACTION.TYPE.search::input::name=q|type=search|aria-label=Search races, tracks, runners|placeholder=Search races, tracks, runners",
      "src/components/site-header.tsx::SiteHeader::ACTION.TYPE.search::input::name=q|type=search|aria-label=Search races, tracks, runners|placeholder=Search races, tracks, runners",
      "src/components/site-header.tsx::SiteHeader::ACTION.TYPE.search::input::name=q|type=search|aria-label=Search races, tracks, runners|placeholder=Search racing",
    ],
  },
  "ACTION.TYPE.checkboxes": {
    state: "present",
    controlIds: [
      "src/app/account/pages/[id]/page.tsx::MediaSlot::ACTION.TYPE.checkboxes::input::name=removeField|type=checkbox",
      "src/app/account/profile/page.tsx::ProfileStudioPage::ACTION.TYPE.checkboxes::input::name=removeAvatar|type=checkbox",
      "src/app/account/profile/page.tsx::ProfileStudioPage::ACTION.TYPE.checkboxes::input::name=removeCover|type=checkbox",
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox::instance-1",
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox::instance-2",
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox::instance-3",
      "src/app/admin/form-controls.tsx::AdminCreateUserForm::ACTION.TYPE.checkboxes::input::name=verified|type=checkbox",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.checkboxes::input::name=enabled|type=checkbox",
      "src/app/admin/form-controls.tsx::AdminRetentionForms::ACTION.TYPE.checkboxes::input::name=enabled|type=checkbox",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.checkboxes::input::name=banned|type=checkbox",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.checkboxes::input::name=cancelDeletion|type=checkbox",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.checkboxes::input::name=verified|type=checkbox",
      "src/app/admin/listings/page.tsx::ListingActions::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox",
      "src/app/admin/page-rules/page.tsx::PageRulesAdmin::ACTION.TYPE.checkboxes::input::name=cardGenerationEnabled|type=checkbox",
      "src/app/admin/page-rules/page.tsx::PageRulesAdmin::ACTION.TYPE.checkboxes::input::name=rule.name|type=checkbox",
      "src/app/admin/site-content/page.tsx::SiteContentAdmin::ACTION.TYPE.checkboxes::input::name=`${plan.id}_highlighted`|type=checkbox",
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox::instance-1",
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox::instance-2",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.checkboxes::input::name=legalAcknowledged|type=checkbox",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.checkboxes::input::name=negotiable|type=checkbox",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.checkboxes::input::name=welfareAcknowledged|type=checkbox",
      "src/app/messages/[id]/page.tsx::MessageThreadPage::ACTION.TYPE.checkboxes::input::name=confirmation|type=checkbox",
      "src/components/listing-edit-form.tsx::ListingEditForm::ACTION.TYPE.checkboxes::input::name=negotiable|type=checkbox",
    ],
  },
  "ACTION.TYPE.radios": { state: "absent", controlIds: [] },
  "ACTION.TYPE.selects": {
    state: "present",
    controlIds: [
      "src/app/account/page.tsx::SignedInAccount::ACTION.TYPE.selects::select::name=contactVisibility",
      "src/app/account/page.tsx::SignedInAccount::ACTION.TYPE.selects::select::name=profileVisibility",
      "src/app/account/pages/[id]/page.tsx::EditCustomPage::ACTION.TYPE.selects::select::id=business-category|name=businessCategory",
      "src/app/account/pages/[id]/page.tsx::EditCustomPage::ACTION.TYPE.selects::select::id=contact-visibility|name=contactVisibility",
      "src/app/account/pages/[id]/page.tsx::EditCustomPage::ACTION.TYPE.selects::select::id=sale-status|name=saleStatus",
      "src/app/account/team/team-invite-form.tsx::TeamInviteForm::ACTION.TYPE.selects::select::name=role",
      "src/app/account/team/team-management.tsx::TeamMemberRow::ACTION.TYPE.selects::select::name=role",
      "src/app/admin/bespoke/page.tsx::BespokeAdmin::ACTION.TYPE.selects::select::name=status|aria-label=Bespoke request status",
      "src/app/admin/feed/page.tsx::PostModerationForm::ACTION.TYPE.selects::select::name=action|aria-label=Moderation action",
      "src/app/admin/form-controls.tsx::AdminBugReportForm::ACTION.TYPE.selects::select::name=severity|aria-label=Severity",
      "src/app/admin/form-controls.tsx::AdminBugReportForm::ACTION.TYPE.selects::select::name=status|aria-label=Status",
      "src/app/admin/form-controls.tsx::AdminCreateUserForm::ACTION.TYPE.selects::select::name=role|aria-label=Role",
      "src/app/admin/form-controls.tsx::AdminCreateUserForm::ACTION.TYPE.selects::select::name=tier|aria-label=Subscription tier",
      "src/app/admin/form-controls.tsx::AdminOrganizationForms::ACTION.TYPE.selects::select::name=role|aria-label=Invitation role",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::PlanSelect::unlabelled-source-control::instance-1",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::PlanSelect::unlabelled-source-control::instance-2",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::select::name=currency|aria-label=Currency",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::select::name=featureKey|aria-label=Entitlement feature",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::select::name=interval|aria-label=Billing interval",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::select::name=status|aria-label=Plan status",
      "src/app/admin/form-controls.tsx::AdminPlanForms::ACTION.TYPE.selects::select::name=status|aria-label=Price status",
      "src/app/admin/form-controls.tsx::AdminSourceHealthForm::ACTION.TYPE.selects::select::name=status|aria-label=Source status",
      "src/app/admin/form-controls.tsx::AdminStatusForm::ACTION.TYPE.selects::select::name=status|aria-label=Status",
      "src/app/admin/form-controls.tsx::AdminSupportTicketForm::ACTION.TYPE.selects::select::name=category|aria-label=Category",
      "src/app/admin/form-controls.tsx::AdminSupportTicketForm::ACTION.TYPE.selects::select::name=priority|aria-label=Priority",
      "src/app/admin/form-controls.tsx::AdminSupportTicketForm::ACTION.TYPE.selects::select::name=status|aria-label=Status",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.selects::select::name=role",
      "src/app/admin/form-controls.tsx::AdminUserAccessForm::ACTION.TYPE.selects::select::name=tier",
      "src/app/admin/form-controls.tsx::PlanSelect::ACTION.TYPE.selects::select::name=planId|aria-label=Plan",
      "src/app/admin/reports/page.tsx::ReportResolutionForm::ACTION.TYPE.selects::select::name=action|aria-label=Resolution action",
      "src/app/admin/safety/page.tsx::AdminSafetyPage::ACTION.TYPE.selects::select::name=action",
      "src/app/admin/safety/page.tsx::AdminSafetyPage::ACTION.TYPE.selects::select::name=target",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.selects::AutoSubmitSelect::name=role|aria-label=Filter users by role",
      "src/app/admin/users/page.tsx::AdminUsersPage::ACTION.TYPE.selects::AutoSubmitSelect::name=tier|aria-label=Filter users by tier",
      "src/app/agents/page.tsx::AgentsPage::ACTION.TYPE.selects::select::name=agentType",
      "src/app/contact/page.tsx::ContactPage::ACTION.TYPE.selects::select::id=support-category|name=category",
      "src/app/dogs/[id]/page.tsx::DogProfilePage::ACTION.TYPE.selects::select::name=role",
      "src/app/listings/[id]/page.tsx::ListingDetailPage::ACTION.TYPE.selects::select::name=reason|aria-label=Reason for report",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=categoryId",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=condition",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=contactPreference",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=dogId",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=state",
      "src/app/listings/new/page.tsx::NewListingPage::ACTION.TYPE.selects::select::name=type",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.selects::AutoSubmitSelect::name=category|aria-label=Category",
      "src/app/listings/page.tsx::ListingsToolbar::ACTION.TYPE.selects::AutoSubmitSelect::name=sort|aria-label=Sort listings",
      "src/app/messages/[id]/page.tsx::MessageThreadPage::ACTION.TYPE.selects::select::name=reason|aria-label=Report reason",
      "src/app/races/page.tsx::RacesPage::ACTION.TYPE.selects::AutoSubmitSelect::name=sort|aria-label=Sort races",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.selects::AutoSubmitSelect::name=date|aria-label=Results date",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.selects::AutoSubmitSelect::name=sort|aria-label=Results order",
      "src/app/results/page.tsx::ResultsFilters::ACTION.TYPE.selects::AutoSubmitSelect::name=trackId|aria-label=Results track",
      "src/app/tracks/page.tsx::TracksPage::ACTION.TYPE.selects::AutoSubmitSelect::name=state|aria-label=Filter tracks by state",
      "src/components/auto-submit-select.tsx::AutoSubmitSelect::ACTION.TYPE.selects::select::aria-label=ariaLabel",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.selects::select::unlabelled-source-control::instance-1",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.selects::select::unlabelled-source-control::instance-2",
      "src/components/conversation-call-panel.tsx::ConversationCallPanel::ACTION.TYPE.selects::select::unlabelled-source-control::instance-3",
      "src/components/feed-post-card.tsx::FeedPostCard::ACTION.TYPE.selects::select::name=reason|aria-label=Report reason",
      "src/components/instant-feed-controls.tsx::InstantFeedOwnerControls::ACTION.TYPE.selects::select::name=visibility|aria-label=Post visibility",
      "src/components/instant-feed-controls.tsx::InstantFeedPostComposer::ACTION.TYPE.selects::select::name=topicId",
      "src/components/instant-feed-controls.tsx::InstantFeedPostComposer::ACTION.TYPE.selects::select::name=visibility",
      "src/components/interactive-help.tsx::InteractiveHelpMenuControls::ACTION.TYPE.selects::select::id=intentFieldId",
      "src/components/listing-edit-form.tsx::ListingEditForm::ACTION.TYPE.selects::select::name=categoryId",
      "src/components/listing-edit-form.tsx::ListingEditForm::ACTION.TYPE.selects::select::name=contactPreference",
    ],
  },
  "ACTION.TYPE.sliders": {
    state: "present",
    controlIds: [
      "src/components/media-focal-point-editor.tsx::MediaFocalPointEditor::ACTION.TYPE.sliders::input::id=horizontalId|name=xName|type=range",
      "src/components/media-focal-point-editor.tsx::MediaFocalPointEditor::ACTION.TYPE.sliders::input::id=verticalId|name=yName|type=range",
      "src/components/media-focal-point-editor.tsx::MediaFocalPointEditor::ACTION.TYPE.sliders::input::name=zoomName|type=range",
    ],
  },
  "ACTION.TYPE.uploads": {
    state: "present",
    controlIds: [
      "src/components/media-attachment-fields.tsx::MediaAttachmentFields::ACTION.TYPE.uploads::input::type=file|accept=.vtt,text/vtt",
      'src/components/media-attachment-fields.tsx::MediaAttachmentFields::ACTION.TYPE.uploads::input::type=file|accept=acceptedMediaTypes.join(",")',
    ],
  },
  "ACTION.TYPE.video": {
    state: "present",
    controlIds: [
      "src/app/listings/[id]/page.tsx::ListingAttachment::ACTION.TYPE.video::ProcessedVideo::unlabelled-source-control",
      "src/app/messages/[id]/page.tsx::MessageAttachment::ACTION.TYPE.video::ProcessedVideo::unlabelled-source-control",
      "src/app/races/[id]/page.tsx::PreviousRaceVideoSection::ACTION.TYPE.video::RaceReplayPlayer::unlabelled-source-control",
      "src/app/races/[id]/page.tsx::RacePage::ACTION.TYPE.video::RaceReplayPlayer::unlabelled-source-control",
      "src/components/feed-post-card.tsx::FeedMedia::ACTION.TYPE.video::ProcessedVideo::unlabelled-source-control",
      "src/components/hub/hub-conversation-dock.tsx::MessageAttachment::ACTION.TYPE.video::ProcessedVideo::unlabelled-source-control",
      "src/components/media-attachment-fields.tsx::MediaPreview::ACTION.TYPE.video::video::src=item.previewUrl|controls=true",
      "src/components/processed-video.tsx::ProcessedVideo::ACTION.TYPE.video::video::aria-label=label|controls=true",
      "src/components/race-replay-player.tsx::RaceReplayPlayer::ACTION.TYPE.video::video::controls=true",
    ],
  },
};

export type ProductActionTypeControlCatalogueEvidenceRecord = {
  status: ProductMasterRequirementStatus;
  evidence: readonly string[];
};

const COMMON_EVIDENCE = [
  PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_EVIDENCE_FILE,
  PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_SCANNER_FILE,
  PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_TEST_FILE,
] as const;

export const PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_MASTER_EVIDENCE =
  Object.fromEntries(
    PRODUCT_ACTION_TYPE_CONTROL_CATALOGUE_REQUIREMENT_IDS.map(
      (requirementId) => [
        requirementId,
        { status: "tested" as const, evidence: COMMON_EVIDENCE },
      ],
    ),
  ) as unknown as Readonly<
    Record<
      ProductActionTypeControlCatalogueRequirementId,
      ProductActionTypeControlCatalogueEvidenceRecord
    >
  >;
